// Package httpboundary provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpboundary

// CallerHeader One caller-owned header and its ordered values.
type CallerHeader struct {
	// Name Caller-supplied header name. The caller owns this extension key; SDK fixed header names use their generated protocol constants.
	Name CallerHeaderName `json:"name"`

	// Values Ordered caller-supplied values for one header name, including duplicates and empty values.
	Values CallerHeaderValues `json:"values"`
}

// CallerHeaderMap Caller-owned extension names map to their ordered string values. Each key must originate from caller input; this open shape does not authorize SDK-invented fixed header names.
type CallerHeaderMap map[string]CallerHeaderValues

// CallerHeaderName Caller-supplied header name. The caller owns this extension key; SDK fixed header names use their generated protocol constants.
type CallerHeaderName = string

// CallerHeaderRecords Ordered caller-owned header records; repeated names remain distinct before HTTP canonicalization.
type CallerHeaderRecords = []CallerHeader

// CallerHeaderValue Caller-supplied HTTP header value, preserved without normalization.
type CallerHeaderValue = string

// CallerHeaderValues Ordered caller-supplied values for one header name, including duplicates and empty values.
type CallerHeaderValues = []CallerHeaderValue
