// Package sharedphotos provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package sharedphotos

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	externalRef0 "github.com/portpowered/go-icloud/pkg/dependencymodels/cloudkit"
)

// Defines values for SharedAssetRecordRecordType.
const (
	CPLAsset SharedAssetRecordRecordType = "CPLAsset"
)

// Valid indicates whether the value is a known member of the SharedAssetRecordRecordType enum.
func (e SharedAssetRecordRecordType) Valid() bool {
	switch e {
	case CPLAsset:
		return true
	default:
		return false
	}
}

// Defines values for SharedImageExtension.
const (
	DotHeic SharedImageExtension = ".heic"
	DotJpeg SharedImageExtension = ".jpeg"
	DotJpg  SharedImageExtension = ".jpg"
	DotPng  SharedImageExtension = ".png"
)

// Valid indicates whether the value is a known member of the SharedImageExtension enum.
func (e SharedImageExtension) Valid() bool {
	switch e {
	case DotHeic:
		return true
	case DotJpeg:
		return true
	case DotJpg:
		return true
	case DotPng:
		return true
	default:
		return false
	}
}

// Defines values for SharedMasterField.
const (
	OriginalCreationDate SharedMasterField = "originalCreationDate"
	ResOriginalFileSize  SharedMasterField = "resOriginalFileSize"
)

// Valid indicates whether the value is a known member of the SharedMasterField enum.
func (e SharedMasterField) Valid() bool {
	switch e {
	case OriginalCreationDate:
		return true
	case ResOriginalFileSize:
		return true
	default:
		return false
	}
}

// Defines values for SharedMasterRecordRecordType.
const (
	CPLMaster SharedMasterRecordRecordType = "CPLMaster"
)

// Valid indicates whether the value is a known member of the SharedMasterRecordRecordType enum.
func (e SharedMasterRecordRecordType) Valid() bool {
	switch e {
	case CPLMaster:
		return true
	default:
		return false
	}
}

// Defines values for SharedPluginField.
const (
	LikeCount     SharedPluginField = "likeCount"
	LikedByCaller SharedPluginField = "likedByCaller"
)

// Valid indicates whether the value is a known member of the SharedPluginField enum.
func (e SharedPluginField) Valid() bool {
	switch e {
	case LikeCount:
		return true
	case LikedByCaller:
		return true
	default:
		return false
	}
}

// Defines values for SharedStreamContentType.
const (
	Plaintext SharedStreamContentType = "plain/text"
)

// Valid indicates whether the value is a known member of the SharedStreamContentType enum.
func (e SharedStreamContentType) Valid() bool {
	switch e {
	case Plaintext:
		return true
	default:
		return false
	}
}

// SharedAlbum Example: {"albumctag":"synthetic-stream-tag","albumguid":"synthetic-stream-0","albumlocation":"https://stream-content.example.invalid/synthetic/","attributes":{"allowcontributions":false,"creationDate":"1700000000000","ispublic":false,"name":"Synthetic stream 0"},"iswebuploadsupported":false,"ownerdsid":"synthetic-owner","sharingtype":"owned"}
type SharedAlbum struct {
	// Albumctag Provider string.
	Albumctag string `json:"albumctag"`

	// Albumguid Provider string.
	Albumguid string `json:"albumguid"`

	// Albumlocation Provider-issued HTTPS base URL ending in a slash. Asset routes resolve relative to this full URL, preserving nested path components.
	Albumlocation        string                `json:"albumlocation"`
	Attributes           SharedAlbumAttributes `json:"attributes"`
	Iswebuploadsupported bool                  `json:"iswebuploadsupported"`

	// Ownerdsid Provider string.
	Ownerdsid string                    `json:"ownerdsid"`
	Publicurl nullable.Nullable[string] `json:"publicurl,omitempty"`

	// Sharingtype Provider string.
	Sharingtype string `json:"sharingtype"`
}

// SharedAlbumAttributes defines model for SharedAlbumAttributes.
type SharedAlbumAttributes struct {
	Allowcontributions bool `json:"allowcontributions"`

	// CreationDate Unix milliseconds as a decimal string.
	CreationDate string `json:"creationDate"`
	Ispublic     bool   `json:"ispublic"`

	// Name Provider string.
	Name string `json:"name"`
}

// SharedAlbumsRequest Example: {}
type SharedAlbumsRequest = map[string]interface{}

// SharedAlbumsResponse Example: {"albums":[{"albumctag":"synthetic-stream-tag","albumguid":"synthetic-stream-0","albumlocation":"https://stream-content.example.invalid/synthetic/","attributes":{"allowcontributions":false,"creationDate":"1700000000000","ispublic":false,"name":"Synthetic stream 0"},"iswebuploadsupported":false,"ownerdsid":"synthetic-owner","sharingtype":"owned"}]}
type SharedAlbumsResponse struct {
	Albums []SharedAlbum `json:"albums"`
}

// SharedAssetFields defines model for SharedAssetFields.
type SharedAssetFields struct {
	AddedDate            *SharedNumberValue                `json:"addedDate,omitempty"`
	AssetDate            *SharedNumberValue                `json:"assetDate,omitempty"`
	MasterRef            *SharedReferenceValue             `json:"masterRef,omitempty"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedAssetRecord defines model for SharedAssetRecord.
type SharedAssetRecord struct {
	Fields               *SharedAssetFields                `json:"fields,omitempty"`
	PluginFields         *SharedPluginFields               `json:"pluginFields,omitempty"`
	RecordName           string                            `json:"recordName"`
	RecordType           SharedAssetRecordRecordType       `json:"recordType"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedAssetRecordRecordType defines model for SharedAssetRecord.RecordType.
type SharedAssetRecordRecordType string

// SharedAssetsRequest Example: {"albumctag":"synthetic-stream-tag","albumguid":"synthetic-stream-0","limit":"200","offset":"0"}
type SharedAssetsRequest struct {
	// Albumctag Provider string.
	Albumctag string `json:"albumctag"`

	// Albumguid Provider string.
	Albumguid string `json:"albumguid"`

	// Limit Provider string.
	Limit string `json:"limit"`

	// Offset Provider string.
	Offset string `json:"offset"`
}

// SharedBooleanValue defines model for SharedBooleanValue.
type SharedBooleanValue struct {
	Value bool `json:"value"`
}

// SharedCountRequest Example: {"albumguid":"synthetic-stream-0"}
type SharedCountRequest struct {
	// Albumguid Provider string.
	Albumguid string `json:"albumguid"`
}

// SharedCountResponse Example: {"albumassetcount":1}
type SharedCountResponse struct {
	Albumassetcount int64 `json:"albumassetcount"`
}

// SharedImageExtension defines model for SharedImageExtension.
type SharedImageExtension string

// SharedIntegerValue defines model for SharedIntegerValue.
type SharedIntegerValue struct {
	Value int64 `json:"value"`
}

// SharedJSONValueWrapper defines model for SharedJSONValueWrapper.
type SharedJSONValueWrapper struct {
	// Value Arbitrary extensible CloudKit JSON preserved without numeric coercion.
	Value                *externalRef0.JsonValue           `json:"value,omitempty"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedMasterField defines model for SharedMasterField.
type SharedMasterField string

// SharedMasterFields defines model for SharedMasterFields.
type SharedMasterFields struct {
	FilenameEnc                 *SharedStringValue                `json:"filenameEnc,omitempty"`
	ItemType                    *SharedStringValue                `json:"itemType,omitempty"`
	OriginalCreationDate        *SharedNumberValue                `json:"originalCreationDate,omitempty"`
	ResJPEGMedFileSize          *SharedNumberValue                `json:"resJPEGMedFileSize,omitempty"`
	ResJPEGMedFileType          *SharedStringValue                `json:"resJPEGMedFileType,omitempty"`
	ResJPEGMedHeight            *SharedNumberValue                `json:"resJPEGMedHeight,omitempty"`
	ResJPEGMedRes               *SharedResourceValue              `json:"resJPEGMedRes,omitempty"`
	ResJPEGMedWidth             *SharedNumberValue                `json:"resJPEGMedWidth,omitempty"`
	ResJPEGThumbFileSize        *SharedNumberValue                `json:"resJPEGThumbFileSize,omitempty"`
	ResJPEGThumbFileType        *SharedStringValue                `json:"resJPEGThumbFileType,omitempty"`
	ResJPEGThumbHeight          *SharedNumberValue                `json:"resJPEGThumbHeight,omitempty"`
	ResJPEGThumbRes             *SharedResourceValue              `json:"resJPEGThumbRes,omitempty"`
	ResJPEGThumbWidth           *SharedNumberValue                `json:"resJPEGThumbWidth,omitempty"`
	ResOriginalFileSize         *SharedNumberValue                `json:"resOriginalFileSize,omitempty"`
	ResOriginalFileType         *SharedStringValue                `json:"resOriginalFileType,omitempty"`
	ResOriginalHeight           *SharedNumberValue                `json:"resOriginalHeight,omitempty"`
	ResOriginalRes              *SharedResourceValue              `json:"resOriginalRes,omitempty"`
	ResOriginalVidComplFileSize *SharedNumberValue                `json:"resOriginalVidComplFileSize,omitempty"`
	ResOriginalVidComplFileType *SharedStringValue                `json:"resOriginalVidComplFileType,omitempty"`
	ResOriginalVidComplHeight   *SharedNumberValue                `json:"resOriginalVidComplHeight,omitempty"`
	ResOriginalVidComplRes      *SharedResourceValue              `json:"resOriginalVidComplRes,omitempty"`
	ResOriginalVidComplWidth    *SharedNumberValue                `json:"resOriginalVidComplWidth,omitempty"`
	ResOriginalWidth            *SharedNumberValue                `json:"resOriginalWidth,omitempty"`
	ResVidMedFileSize           *SharedNumberValue                `json:"resVidMedFileSize,omitempty"`
	ResVidMedFileType           *SharedStringValue                `json:"resVidMedFileType,omitempty"`
	ResVidMedHeight             *SharedNumberValue                `json:"resVidMedHeight,omitempty"`
	ResVidMedRes                *SharedResourceValue              `json:"resVidMedRes,omitempty"`
	ResVidMedWidth              *SharedNumberValue                `json:"resVidMedWidth,omitempty"`
	ResVidSmallFileSize         *SharedNumberValue                `json:"resVidSmallFileSize,omitempty"`
	ResVidSmallFileType         *SharedStringValue                `json:"resVidSmallFileType,omitempty"`
	ResVidSmallHeight           *SharedNumberValue                `json:"resVidSmallHeight,omitempty"`
	ResVidSmallRes              *SharedResourceValue              `json:"resVidSmallRes,omitempty"`
	ResVidSmallWidth            *SharedNumberValue                `json:"resVidSmallWidth,omitempty"`
	AdditionalProperties        map[string]externalRef0.JsonValue `json:"-"`
}

// SharedMasterRecord defines model for SharedMasterRecord.
type SharedMasterRecord struct {
	Fields               *SharedMasterFields               `json:"fields,omitempty"`
	PluginFields         *SharedPluginFields               `json:"pluginFields,omitempty"`
	RecordName           string                            `json:"recordName"`
	RecordType           SharedMasterRecordRecordType      `json:"recordType"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedMasterRecordRecordType defines model for SharedMasterRecord.RecordType.
type SharedMasterRecordRecordType string

// SharedNumberValue defines model for SharedNumberValue.
type SharedNumberValue struct {
	Value                json.Number                       `json:"value"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedOtherRecord defines model for SharedOtherRecord.
type SharedOtherRecord struct {
	RecordType           *string                           `json:"recordType,omitempty"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedPhotoRecord defines model for SharedPhotoRecord.
type SharedPhotoRecord struct {
	union json.RawMessage
}

// SharedPluginField defines model for SharedPluginField.
type SharedPluginField string

// SharedPluginFields defines model for SharedPluginFields.
type SharedPluginFields struct {
	LikeCount     *SharedIntegerValue     `json:"likeCount,omitempty"`
	LikedByCaller *SharedJSONValueWrapper `json:"likedByCaller,omitempty"`
}

// SharedRecordsResponse defines model for SharedRecordsResponse.
type SharedRecordsResponse struct {
	Records              *[]SharedPhotoRecord              `json:"records,omitempty"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedReferenceValue defines model for SharedReferenceValue.
type SharedReferenceValue struct {
	// Value Value inside REFERENCE / REFERENCE_LIST typed fields (both request & response).
	Value                externalRef0.CKReference          `json:"value"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedResource defines model for SharedResource.
type SharedResource struct {
	DownloadURL          nullable.Nullable[string]         `json:"downloadURL"`
	Size                 int64                             `json:"size"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedResourceValue defines model for SharedResourceValue.
type SharedResourceValue struct {
	Value                SharedResource                    `json:"value"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// SharedStreamContentType defines model for SharedStreamContentType.
type SharedStreamContentType string

// SharedStringValue defines model for SharedStringValue.
type SharedStringValue struct {
	Value                string                            `json:"value"`
	AdditionalProperties map[string]externalRef0.JsonValue `json:"-"`
}

// Getter for additional properties for SharedAssetFields. Returns the specified
// element and whether it was found
func (a SharedAssetFields) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedAssetFields
func (a *SharedAssetFields) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedAssetFields to handle AdditionalProperties
func (a *SharedAssetFields) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["addedDate"]; found {
		err = json.Unmarshal(raw, &a.AddedDate)
		if err != nil {
			return fmt.Errorf("error reading 'addedDate': %w", err)
		}
		delete(object, "addedDate")
	}

	if raw, found := object["assetDate"]; found {
		err = json.Unmarshal(raw, &a.AssetDate)
		if err != nil {
			return fmt.Errorf("error reading 'assetDate': %w", err)
		}
		delete(object, "assetDate")
	}

	if raw, found := object["masterRef"]; found {
		err = json.Unmarshal(raw, &a.MasterRef)
		if err != nil {
			return fmt.Errorf("error reading 'masterRef': %w", err)
		}
		delete(object, "masterRef")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedAssetFields to handle AdditionalProperties
func (a SharedAssetFields) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AddedDate != nil {
		object["addedDate"], err = json.Marshal(a.AddedDate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'addedDate': %w", err)
		}
	}

	if a.AssetDate != nil {
		object["assetDate"], err = json.Marshal(a.AssetDate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'assetDate': %w", err)
		}
	}

	if a.MasterRef != nil {
		object["masterRef"], err = json.Marshal(a.MasterRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'masterRef': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedAssetRecord. Returns the specified
// element and whether it was found
func (a SharedAssetRecord) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedAssetRecord
func (a *SharedAssetRecord) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedAssetRecord to handle AdditionalProperties
func (a *SharedAssetRecord) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fields"]; found {
		err = json.Unmarshal(raw, &a.Fields)
		if err != nil {
			return fmt.Errorf("error reading 'fields': %w", err)
		}
		delete(object, "fields")
	}

	if raw, found := object["pluginFields"]; found {
		err = json.Unmarshal(raw, &a.PluginFields)
		if err != nil {
			return fmt.Errorf("error reading 'pluginFields': %w", err)
		}
		delete(object, "pluginFields")
	}

	if raw, found := object["recordName"]; found {
		err = json.Unmarshal(raw, &a.RecordName)
		if err != nil {
			return fmt.Errorf("error reading 'recordName': %w", err)
		}
		delete(object, "recordName")
	}

	if raw, found := object["recordType"]; found {
		err = json.Unmarshal(raw, &a.RecordType)
		if err != nil {
			return fmt.Errorf("error reading 'recordType': %w", err)
		}
		delete(object, "recordType")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedAssetRecord to handle AdditionalProperties
func (a SharedAssetRecord) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Fields != nil {
		object["fields"], err = json.Marshal(a.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fields': %w", err)
		}
	}

	if a.PluginFields != nil {
		object["pluginFields"], err = json.Marshal(a.PluginFields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pluginFields': %w", err)
		}
	}

	object["recordName"], err = json.Marshal(a.RecordName)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'recordName': %w", err)
	}

	object["recordType"], err = json.Marshal(a.RecordType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'recordType': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedJSONValueWrapper. Returns the specified
// element and whether it was found
func (a SharedJSONValueWrapper) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedJSONValueWrapper
func (a *SharedJSONValueWrapper) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedJSONValueWrapper to handle AdditionalProperties
func (a *SharedJSONValueWrapper) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedJSONValueWrapper to handle AdditionalProperties
func (a SharedJSONValueWrapper) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Value != nil {
		object["value"], err = json.Marshal(a.Value)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'value': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedMasterFields. Returns the specified
// element and whether it was found
func (a SharedMasterFields) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedMasterFields
func (a *SharedMasterFields) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedMasterFields to handle AdditionalProperties
func (a *SharedMasterFields) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["filenameEnc"]; found {
		err = json.Unmarshal(raw, &a.FilenameEnc)
		if err != nil {
			return fmt.Errorf("error reading 'filenameEnc': %w", err)
		}
		delete(object, "filenameEnc")
	}

	if raw, found := object["itemType"]; found {
		err = json.Unmarshal(raw, &a.ItemType)
		if err != nil {
			return fmt.Errorf("error reading 'itemType': %w", err)
		}
		delete(object, "itemType")
	}

	if raw, found := object["originalCreationDate"]; found {
		err = json.Unmarshal(raw, &a.OriginalCreationDate)
		if err != nil {
			return fmt.Errorf("error reading 'originalCreationDate': %w", err)
		}
		delete(object, "originalCreationDate")
	}

	if raw, found := object["resJPEGMedFileSize"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGMedFileSize)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGMedFileSize': %w", err)
		}
		delete(object, "resJPEGMedFileSize")
	}

	if raw, found := object["resJPEGMedFileType"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGMedFileType)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGMedFileType': %w", err)
		}
		delete(object, "resJPEGMedFileType")
	}

	if raw, found := object["resJPEGMedHeight"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGMedHeight)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGMedHeight': %w", err)
		}
		delete(object, "resJPEGMedHeight")
	}

	if raw, found := object["resJPEGMedRes"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGMedRes)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGMedRes': %w", err)
		}
		delete(object, "resJPEGMedRes")
	}

	if raw, found := object["resJPEGMedWidth"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGMedWidth)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGMedWidth': %w", err)
		}
		delete(object, "resJPEGMedWidth")
	}

	if raw, found := object["resJPEGThumbFileSize"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGThumbFileSize)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGThumbFileSize': %w", err)
		}
		delete(object, "resJPEGThumbFileSize")
	}

	if raw, found := object["resJPEGThumbFileType"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGThumbFileType)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGThumbFileType': %w", err)
		}
		delete(object, "resJPEGThumbFileType")
	}

	if raw, found := object["resJPEGThumbHeight"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGThumbHeight)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGThumbHeight': %w", err)
		}
		delete(object, "resJPEGThumbHeight")
	}

	if raw, found := object["resJPEGThumbRes"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGThumbRes)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGThumbRes': %w", err)
		}
		delete(object, "resJPEGThumbRes")
	}

	if raw, found := object["resJPEGThumbWidth"]; found {
		err = json.Unmarshal(raw, &a.ResJPEGThumbWidth)
		if err != nil {
			return fmt.Errorf("error reading 'resJPEGThumbWidth': %w", err)
		}
		delete(object, "resJPEGThumbWidth")
	}

	if raw, found := object["resOriginalFileSize"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalFileSize)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalFileSize': %w", err)
		}
		delete(object, "resOriginalFileSize")
	}

	if raw, found := object["resOriginalFileType"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalFileType)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalFileType': %w", err)
		}
		delete(object, "resOriginalFileType")
	}

	if raw, found := object["resOriginalHeight"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalHeight)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalHeight': %w", err)
		}
		delete(object, "resOriginalHeight")
	}

	if raw, found := object["resOriginalRes"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalRes)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalRes': %w", err)
		}
		delete(object, "resOriginalRes")
	}

	if raw, found := object["resOriginalVidComplFileSize"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalVidComplFileSize)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalVidComplFileSize': %w", err)
		}
		delete(object, "resOriginalVidComplFileSize")
	}

	if raw, found := object["resOriginalVidComplFileType"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalVidComplFileType)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalVidComplFileType': %w", err)
		}
		delete(object, "resOriginalVidComplFileType")
	}

	if raw, found := object["resOriginalVidComplHeight"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalVidComplHeight)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalVidComplHeight': %w", err)
		}
		delete(object, "resOriginalVidComplHeight")
	}

	if raw, found := object["resOriginalVidComplRes"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalVidComplRes)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalVidComplRes': %w", err)
		}
		delete(object, "resOriginalVidComplRes")
	}

	if raw, found := object["resOriginalVidComplWidth"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalVidComplWidth)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalVidComplWidth': %w", err)
		}
		delete(object, "resOriginalVidComplWidth")
	}

	if raw, found := object["resOriginalWidth"]; found {
		err = json.Unmarshal(raw, &a.ResOriginalWidth)
		if err != nil {
			return fmt.Errorf("error reading 'resOriginalWidth': %w", err)
		}
		delete(object, "resOriginalWidth")
	}

	if raw, found := object["resVidMedFileSize"]; found {
		err = json.Unmarshal(raw, &a.ResVidMedFileSize)
		if err != nil {
			return fmt.Errorf("error reading 'resVidMedFileSize': %w", err)
		}
		delete(object, "resVidMedFileSize")
	}

	if raw, found := object["resVidMedFileType"]; found {
		err = json.Unmarshal(raw, &a.ResVidMedFileType)
		if err != nil {
			return fmt.Errorf("error reading 'resVidMedFileType': %w", err)
		}
		delete(object, "resVidMedFileType")
	}

	if raw, found := object["resVidMedHeight"]; found {
		err = json.Unmarshal(raw, &a.ResVidMedHeight)
		if err != nil {
			return fmt.Errorf("error reading 'resVidMedHeight': %w", err)
		}
		delete(object, "resVidMedHeight")
	}

	if raw, found := object["resVidMedRes"]; found {
		err = json.Unmarshal(raw, &a.ResVidMedRes)
		if err != nil {
			return fmt.Errorf("error reading 'resVidMedRes': %w", err)
		}
		delete(object, "resVidMedRes")
	}

	if raw, found := object["resVidMedWidth"]; found {
		err = json.Unmarshal(raw, &a.ResVidMedWidth)
		if err != nil {
			return fmt.Errorf("error reading 'resVidMedWidth': %w", err)
		}
		delete(object, "resVidMedWidth")
	}

	if raw, found := object["resVidSmallFileSize"]; found {
		err = json.Unmarshal(raw, &a.ResVidSmallFileSize)
		if err != nil {
			return fmt.Errorf("error reading 'resVidSmallFileSize': %w", err)
		}
		delete(object, "resVidSmallFileSize")
	}

	if raw, found := object["resVidSmallFileType"]; found {
		err = json.Unmarshal(raw, &a.ResVidSmallFileType)
		if err != nil {
			return fmt.Errorf("error reading 'resVidSmallFileType': %w", err)
		}
		delete(object, "resVidSmallFileType")
	}

	if raw, found := object["resVidSmallHeight"]; found {
		err = json.Unmarshal(raw, &a.ResVidSmallHeight)
		if err != nil {
			return fmt.Errorf("error reading 'resVidSmallHeight': %w", err)
		}
		delete(object, "resVidSmallHeight")
	}

	if raw, found := object["resVidSmallRes"]; found {
		err = json.Unmarshal(raw, &a.ResVidSmallRes)
		if err != nil {
			return fmt.Errorf("error reading 'resVidSmallRes': %w", err)
		}
		delete(object, "resVidSmallRes")
	}

	if raw, found := object["resVidSmallWidth"]; found {
		err = json.Unmarshal(raw, &a.ResVidSmallWidth)
		if err != nil {
			return fmt.Errorf("error reading 'resVidSmallWidth': %w", err)
		}
		delete(object, "resVidSmallWidth")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedMasterFields to handle AdditionalProperties
func (a SharedMasterFields) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.FilenameEnc != nil {
		object["filenameEnc"], err = json.Marshal(a.FilenameEnc)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'filenameEnc': %w", err)
		}
	}

	if a.ItemType != nil {
		object["itemType"], err = json.Marshal(a.ItemType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'itemType': %w", err)
		}
	}

	if a.OriginalCreationDate != nil {
		object["originalCreationDate"], err = json.Marshal(a.OriginalCreationDate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'originalCreationDate': %w", err)
		}
	}

	if a.ResJPEGMedFileSize != nil {
		object["resJPEGMedFileSize"], err = json.Marshal(a.ResJPEGMedFileSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGMedFileSize': %w", err)
		}
	}

	if a.ResJPEGMedFileType != nil {
		object["resJPEGMedFileType"], err = json.Marshal(a.ResJPEGMedFileType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGMedFileType': %w", err)
		}
	}

	if a.ResJPEGMedHeight != nil {
		object["resJPEGMedHeight"], err = json.Marshal(a.ResJPEGMedHeight)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGMedHeight': %w", err)
		}
	}

	if a.ResJPEGMedRes != nil {
		object["resJPEGMedRes"], err = json.Marshal(a.ResJPEGMedRes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGMedRes': %w", err)
		}
	}

	if a.ResJPEGMedWidth != nil {
		object["resJPEGMedWidth"], err = json.Marshal(a.ResJPEGMedWidth)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGMedWidth': %w", err)
		}
	}

	if a.ResJPEGThumbFileSize != nil {
		object["resJPEGThumbFileSize"], err = json.Marshal(a.ResJPEGThumbFileSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGThumbFileSize': %w", err)
		}
	}

	if a.ResJPEGThumbFileType != nil {
		object["resJPEGThumbFileType"], err = json.Marshal(a.ResJPEGThumbFileType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGThumbFileType': %w", err)
		}
	}

	if a.ResJPEGThumbHeight != nil {
		object["resJPEGThumbHeight"], err = json.Marshal(a.ResJPEGThumbHeight)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGThumbHeight': %w", err)
		}
	}

	if a.ResJPEGThumbRes != nil {
		object["resJPEGThumbRes"], err = json.Marshal(a.ResJPEGThumbRes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGThumbRes': %w", err)
		}
	}

	if a.ResJPEGThumbWidth != nil {
		object["resJPEGThumbWidth"], err = json.Marshal(a.ResJPEGThumbWidth)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resJPEGThumbWidth': %w", err)
		}
	}

	if a.ResOriginalFileSize != nil {
		object["resOriginalFileSize"], err = json.Marshal(a.ResOriginalFileSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalFileSize': %w", err)
		}
	}

	if a.ResOriginalFileType != nil {
		object["resOriginalFileType"], err = json.Marshal(a.ResOriginalFileType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalFileType': %w", err)
		}
	}

	if a.ResOriginalHeight != nil {
		object["resOriginalHeight"], err = json.Marshal(a.ResOriginalHeight)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalHeight': %w", err)
		}
	}

	if a.ResOriginalRes != nil {
		object["resOriginalRes"], err = json.Marshal(a.ResOriginalRes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalRes': %w", err)
		}
	}

	if a.ResOriginalVidComplFileSize != nil {
		object["resOriginalVidComplFileSize"], err = json.Marshal(a.ResOriginalVidComplFileSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalVidComplFileSize': %w", err)
		}
	}

	if a.ResOriginalVidComplFileType != nil {
		object["resOriginalVidComplFileType"], err = json.Marshal(a.ResOriginalVidComplFileType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalVidComplFileType': %w", err)
		}
	}

	if a.ResOriginalVidComplHeight != nil {
		object["resOriginalVidComplHeight"], err = json.Marshal(a.ResOriginalVidComplHeight)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalVidComplHeight': %w", err)
		}
	}

	if a.ResOriginalVidComplRes != nil {
		object["resOriginalVidComplRes"], err = json.Marshal(a.ResOriginalVidComplRes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalVidComplRes': %w", err)
		}
	}

	if a.ResOriginalVidComplWidth != nil {
		object["resOriginalVidComplWidth"], err = json.Marshal(a.ResOriginalVidComplWidth)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalVidComplWidth': %w", err)
		}
	}

	if a.ResOriginalWidth != nil {
		object["resOriginalWidth"], err = json.Marshal(a.ResOriginalWidth)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resOriginalWidth': %w", err)
		}
	}

	if a.ResVidMedFileSize != nil {
		object["resVidMedFileSize"], err = json.Marshal(a.ResVidMedFileSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidMedFileSize': %w", err)
		}
	}

	if a.ResVidMedFileType != nil {
		object["resVidMedFileType"], err = json.Marshal(a.ResVidMedFileType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidMedFileType': %w", err)
		}
	}

	if a.ResVidMedHeight != nil {
		object["resVidMedHeight"], err = json.Marshal(a.ResVidMedHeight)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidMedHeight': %w", err)
		}
	}

	if a.ResVidMedRes != nil {
		object["resVidMedRes"], err = json.Marshal(a.ResVidMedRes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidMedRes': %w", err)
		}
	}

	if a.ResVidMedWidth != nil {
		object["resVidMedWidth"], err = json.Marshal(a.ResVidMedWidth)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidMedWidth': %w", err)
		}
	}

	if a.ResVidSmallFileSize != nil {
		object["resVidSmallFileSize"], err = json.Marshal(a.ResVidSmallFileSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidSmallFileSize': %w", err)
		}
	}

	if a.ResVidSmallFileType != nil {
		object["resVidSmallFileType"], err = json.Marshal(a.ResVidSmallFileType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidSmallFileType': %w", err)
		}
	}

	if a.ResVidSmallHeight != nil {
		object["resVidSmallHeight"], err = json.Marshal(a.ResVidSmallHeight)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidSmallHeight': %w", err)
		}
	}

	if a.ResVidSmallRes != nil {
		object["resVidSmallRes"], err = json.Marshal(a.ResVidSmallRes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidSmallRes': %w", err)
		}
	}

	if a.ResVidSmallWidth != nil {
		object["resVidSmallWidth"], err = json.Marshal(a.ResVidSmallWidth)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resVidSmallWidth': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedMasterRecord. Returns the specified
// element and whether it was found
func (a SharedMasterRecord) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedMasterRecord
func (a *SharedMasterRecord) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedMasterRecord to handle AdditionalProperties
func (a *SharedMasterRecord) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fields"]; found {
		err = json.Unmarshal(raw, &a.Fields)
		if err != nil {
			return fmt.Errorf("error reading 'fields': %w", err)
		}
		delete(object, "fields")
	}

	if raw, found := object["pluginFields"]; found {
		err = json.Unmarshal(raw, &a.PluginFields)
		if err != nil {
			return fmt.Errorf("error reading 'pluginFields': %w", err)
		}
		delete(object, "pluginFields")
	}

	if raw, found := object["recordName"]; found {
		err = json.Unmarshal(raw, &a.RecordName)
		if err != nil {
			return fmt.Errorf("error reading 'recordName': %w", err)
		}
		delete(object, "recordName")
	}

	if raw, found := object["recordType"]; found {
		err = json.Unmarshal(raw, &a.RecordType)
		if err != nil {
			return fmt.Errorf("error reading 'recordType': %w", err)
		}
		delete(object, "recordType")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedMasterRecord to handle AdditionalProperties
func (a SharedMasterRecord) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Fields != nil {
		object["fields"], err = json.Marshal(a.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fields': %w", err)
		}
	}

	if a.PluginFields != nil {
		object["pluginFields"], err = json.Marshal(a.PluginFields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pluginFields': %w", err)
		}
	}

	object["recordName"], err = json.Marshal(a.RecordName)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'recordName': %w", err)
	}

	object["recordType"], err = json.Marshal(a.RecordType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'recordType': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedNumberValue. Returns the specified
// element and whether it was found
func (a SharedNumberValue) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedNumberValue
func (a *SharedNumberValue) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedNumberValue to handle AdditionalProperties
func (a *SharedNumberValue) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedNumberValue to handle AdditionalProperties
func (a SharedNumberValue) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["value"], err = json.Marshal(a.Value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'value': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedOtherRecord. Returns the specified
// element and whether it was found
func (a SharedOtherRecord) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedOtherRecord
func (a *SharedOtherRecord) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedOtherRecord to handle AdditionalProperties
func (a *SharedOtherRecord) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["recordType"]; found {
		err = json.Unmarshal(raw, &a.RecordType)
		if err != nil {
			return fmt.Errorf("error reading 'recordType': %w", err)
		}
		delete(object, "recordType")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedOtherRecord to handle AdditionalProperties
func (a SharedOtherRecord) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.RecordType != nil {
		object["recordType"], err = json.Marshal(a.RecordType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'recordType': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedRecordsResponse. Returns the specified
// element and whether it was found
func (a SharedRecordsResponse) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedRecordsResponse
func (a *SharedRecordsResponse) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedRecordsResponse to handle AdditionalProperties
func (a *SharedRecordsResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["records"]; found {
		err = json.Unmarshal(raw, &a.Records)
		if err != nil {
			return fmt.Errorf("error reading 'records': %w", err)
		}
		delete(object, "records")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedRecordsResponse to handle AdditionalProperties
func (a SharedRecordsResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Records != nil {
		object["records"], err = json.Marshal(a.Records)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'records': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedReferenceValue. Returns the specified
// element and whether it was found
func (a SharedReferenceValue) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedReferenceValue
func (a *SharedReferenceValue) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedReferenceValue to handle AdditionalProperties
func (a *SharedReferenceValue) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedReferenceValue to handle AdditionalProperties
func (a SharedReferenceValue) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["value"], err = json.Marshal(a.Value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'value': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedResource. Returns the specified
// element and whether it was found
func (a SharedResource) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedResource
func (a *SharedResource) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedResource to handle AdditionalProperties
func (a *SharedResource) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["downloadURL"]; found {
		err = json.Unmarshal(raw, &a.DownloadURL)
		if err != nil {
			return fmt.Errorf("error reading 'downloadURL': %w", err)
		}
		delete(object, "downloadURL")
	}

	if raw, found := object["size"]; found {
		err = json.Unmarshal(raw, &a.Size)
		if err != nil {
			return fmt.Errorf("error reading 'size': %w", err)
		}
		delete(object, "size")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedResource to handle AdditionalProperties
func (a SharedResource) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["downloadURL"], err = json.Marshal(a.DownloadURL)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'downloadURL': %w", err)
	}

	object["size"], err = json.Marshal(a.Size)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'size': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedResourceValue. Returns the specified
// element and whether it was found
func (a SharedResourceValue) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedResourceValue
func (a *SharedResourceValue) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedResourceValue to handle AdditionalProperties
func (a *SharedResourceValue) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedResourceValue to handle AdditionalProperties
func (a SharedResourceValue) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["value"], err = json.Marshal(a.Value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'value': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SharedStringValue. Returns the specified
// element and whether it was found
func (a SharedStringValue) Get(fieldName string) (value externalRef0.JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SharedStringValue
func (a *SharedStringValue) Set(fieldName string, value externalRef0.JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SharedStringValue to handle AdditionalProperties
func (a *SharedStringValue) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]externalRef0.JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal externalRef0.JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SharedStringValue to handle AdditionalProperties
func (a SharedStringValue) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["value"], err = json.Marshal(a.Value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'value': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsSharedMasterRecord returns the union data inside the SharedPhotoRecord as a SharedMasterRecord
func (t SharedPhotoRecord) AsSharedMasterRecord() (SharedMasterRecord, error) {
	var body SharedMasterRecord
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSharedMasterRecord overwrites any union data inside the SharedPhotoRecord as the provided SharedMasterRecord
func (t *SharedPhotoRecord) FromSharedMasterRecord(v SharedMasterRecord) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSharedMasterRecord performs a merge with any union data inside the SharedPhotoRecord, using the provided SharedMasterRecord
func (t *SharedPhotoRecord) MergeSharedMasterRecord(v SharedMasterRecord) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSharedAssetRecord returns the union data inside the SharedPhotoRecord as a SharedAssetRecord
func (t SharedPhotoRecord) AsSharedAssetRecord() (SharedAssetRecord, error) {
	var body SharedAssetRecord
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSharedAssetRecord overwrites any union data inside the SharedPhotoRecord as the provided SharedAssetRecord
func (t *SharedPhotoRecord) FromSharedAssetRecord(v SharedAssetRecord) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSharedAssetRecord performs a merge with any union data inside the SharedPhotoRecord, using the provided SharedAssetRecord
func (t *SharedPhotoRecord) MergeSharedAssetRecord(v SharedAssetRecord) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSharedOtherRecord returns the union data inside the SharedPhotoRecord as a SharedOtherRecord
func (t SharedPhotoRecord) AsSharedOtherRecord() (SharedOtherRecord, error) {
	var body SharedOtherRecord
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSharedOtherRecord overwrites any union data inside the SharedPhotoRecord as the provided SharedOtherRecord
func (t *SharedPhotoRecord) FromSharedOtherRecord(v SharedOtherRecord) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSharedOtherRecord performs a merge with any union data inside the SharedPhotoRecord, using the provided SharedOtherRecord
func (t *SharedPhotoRecord) MergeSharedOtherRecord(v SharedOtherRecord) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SharedPhotoRecord) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SharedPhotoRecord) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
