package webtransport

import "github.com/portpowered/go-icloud/pkg/dependencymodels/photosupload"

func photoUploadDesiredKeys() []photosupload.PhotosUploadDesiredKey {
	return append(photoUploadResourceKeys(), photoUploadMetadataKeys()...)
}

func photoUploadResourceKeys() []photosupload.PhotosUploadDesiredKey {
	return []photosupload.PhotosUploadDesiredKey{
		photosupload.ResJPEGFullWidth,
		photosupload.ResJPEGFullHeight,
		photosupload.ResJPEGFullFileType,
		photosupload.ResJPEGFullFingerprint,
		photosupload.ResJPEGFullRes,
		photosupload.ResJPEGLargeWidth,
		photosupload.ResJPEGLargeHeight,
		photosupload.ResJPEGLargeFileType,
		photosupload.ResJPEGLargeFingerprint,
		photosupload.ResJPEGLargeRes,
		photosupload.ResJPEGMedWidth,
		photosupload.ResJPEGMedHeight,
		photosupload.ResJPEGMedFileType,
		photosupload.ResJPEGMedFingerprint,
		photosupload.ResJPEGMedRes,
		photosupload.ResJPEGThumbWidth,
		photosupload.ResJPEGThumbHeight,
		photosupload.ResJPEGThumbFileType,
		photosupload.ResJPEGThumbFingerprint,
		photosupload.ResJPEGThumbRes,
		photosupload.ResVidFullWidth,
		photosupload.ResVidFullHeight,
		photosupload.ResVidFullFileType,
		photosupload.ResVidFullFingerprint,
		photosupload.ResVidFullRes,
		photosupload.ResVidMedWidth,
		photosupload.ResVidMedHeight,
		photosupload.ResVidMedFileType,
		photosupload.ResVidMedFingerprint,
		photosupload.ResVidMedRes,
		photosupload.ResVidSmallWidth,
		photosupload.ResVidSmallHeight,
		photosupload.ResVidSmallFileType,
		photosupload.ResVidSmallFingerprint,
		photosupload.ResVidSmallRes,
		photosupload.ResSidecarWidth,
		photosupload.ResSidecarHeight,
		photosupload.ResSidecarFileType,
		photosupload.ResSidecarFingerprint,
		photosupload.ResSidecarRes,
	}
}

func photoUploadMetadataKeys() []photosupload.PhotosUploadDesiredKey {
	return []photosupload.PhotosUploadDesiredKey{
		photosupload.ItemType,
		photosupload.DataClassType,
		photosupload.FilenameEnc,
		photosupload.OriginalOrientation,
		photosupload.ResOriginalWidth,
		photosupload.ResOriginalHeight,
		photosupload.ResOriginalFileType,
		photosupload.ResOriginalFingerprint,
		photosupload.ResOriginalRes,
		photosupload.ResOriginalAltWidth,
		photosupload.ResOriginalAltHeight,
		photosupload.ResOriginalAltFileType,
		photosupload.ResOriginalAltFingerprint,
		photosupload.ResOriginalAltRes,
		photosupload.ResOriginalVidComplWidth,
		photosupload.ResOriginalVidComplHeight,
		photosupload.ResOriginalVidComplFileType,
		photosupload.ResOriginalVidComplFingerprint,
		photosupload.ResOriginalVidComplRes,
		photosupload.IsDeleted,
		photosupload.IsExpunged,
		photosupload.DateExpunged,
		photosupload.RemappedRef,
		photosupload.RecordName,
		photosupload.RecordType,
		photosupload.RecordChangeTag,
		photosupload.MasterRef,
		photosupload.AdjustmentRenderType,
		photosupload.AssetDate,
		photosupload.AddedDate,
		photosupload.IsFavorite,
		photosupload.IsHidden,
		photosupload.Orientation,
		photosupload.Duration,
		photosupload.AssetSubtype,
		photosupload.AssetSubtypeV2,
		photosupload.AssetHDRType,
		photosupload.BurstFlags,
		photosupload.BurstFlagsExt,
		photosupload.BurstId,
		photosupload.CaptionEnc,
		photosupload.LocationEnc,
		photosupload.LocationV2Enc,
		photosupload.LocationLatitude,
		photosupload.LocationLongitude,
		photosupload.AdjustmentType,
		photosupload.TimeZoneOffset,
		photosupload.VidComplDurValue,
		photosupload.VidComplDurScale,
		photosupload.VidComplDispValue,
		photosupload.VidComplDispScale,
		photosupload.VidComplVisibilityState,
		photosupload.CustomRenderedValue,
		photosupload.ContainerId,
		photosupload.ItemId,
		photosupload.Position,
		photosupload.IsKeyAsset,
	}
}
