// Package photosynccommand provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package photosynccommand

import (
	externalRef0 "github.com/portpowered/go-icloud/pkg/photosync"
)

// PhotosWatchRequest The saved native session supplies authentication; request.auth is overridden before execution.
//
// Example: {"request":{"auth":{"accountID":"synthetic-account","clientID":"synthetic-client","headers":[]},"options":{"albums":[],"alignRaw":"as-is","autoDelete":false,"directory":"./photos","dryRun":false,"folderStructure":"none","library":"root","livePhotoSize":"original","onlyPrintFilenames":true,"setExifDatetime":false,"size":"original","skipLivePhotos":false,"skipVideos":false,"xmpSidecar":false}},"watch":{"intervalSeconds":1,"iterations":2}}
type PhotosWatchRequest struct {
	Request externalRef0.Request      `json:"request"`
	Watch   externalRef0.WatchOptions `json:"watch"`
}
