// Package findmy provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package findmy

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/nullable"
)

// Defines values for FindMyAPIVersion.
const (
	N30 FindMyAPIVersion = "3.0"
)

// Valid indicates whether the value is a known member of the FindMyAPIVersion enum.
func (e FindMyAPIVersion) Valid() bool {
	switch e {
	case N30:
		return true
	default:
		return false
	}
}

// Defines values for FindMyAllDevices.
const (
	All FindMyAllDevices = "all"
)

// Valid indicates whether the value is a known member of the FindMyAllDevices enum.
func (e FindMyAllDevices) Valid() bool {
	switch e {
	case All:
		return true
	default:
		return false
	}
}

// Defines values for FindMyAppName.
const (
	ICloudFindWeb FindMyAppName = "iCloud Find (Web)"
)

// Valid indicates whether the value is a known member of the FindMyAppName enum.
func (e FindMyAppName) Valid() bool {
	switch e {
	case ICloudFindWeb:
		return true
	default:
		return false
	}
}

// Defines values for FindMyAppVersion.
const (
	N20 FindMyAppVersion = "2.0"
)

// Valid indicates whether the value is a known member of the FindMyAppVersion enum.
func (e FindMyAppVersion) Valid() bool {
	switch e {
	case N20:
		return true
	default:
		return false
	}
}

// Defines values for FindMyClientContextDeviceListVersion.
const (
	FindMyClientContextDeviceListVersionN1 FindMyClientContextDeviceListVersion = 1
)

// Valid indicates whether the value is a known member of the FindMyClientContextDeviceListVersion enum.
func (e FindMyClientContextDeviceListVersion) Valid() bool {
	switch e {
	case FindMyClientContextDeviceListVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for FindMyClientContextInactiveTime.
const (
	FindMyClientContextInactiveTimeN0 FindMyClientContextInactiveTime = 0
)

// Valid indicates whether the value is a known member of the FindMyClientContextInactiveTime enum.
func (e FindMyClientContextInactiveTime) Valid() bool {
	switch e {
	case FindMyClientContextInactiveTimeN0:
		return true
	default:
		return false
	}
}

// Defines values for FindMyClientContextShouldLocate.
const (
	FindMyClientContextShouldLocateTrue FindMyClientContextShouldLocate = true
)

// Valid indicates whether the value is a known member of the FindMyClientContextShouldLocate enum.
func (e FindMyClientContextShouldLocate) Valid() bool {
	switch e {
	case FindMyClientContextShouldLocateTrue:
		return true
	default:
		return false
	}
}

// Defines values for FindMyInitializeContextDeviceListVersion.
const (
	FindMyInitializeContextDeviceListVersionN1 FindMyInitializeContextDeviceListVersion = 1
)

// Valid indicates whether the value is a known member of the FindMyInitializeContextDeviceListVersion enum.
func (e FindMyInitializeContextDeviceListVersion) Valid() bool {
	switch e {
	case FindMyInitializeContextDeviceListVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for FindMyInitializeContextInactiveTime.
const (
	FindMyInitializeContextInactiveTimeN0 FindMyInitializeContextInactiveTime = 0
)

// Valid indicates whether the value is a known member of the FindMyInitializeContextInactiveTime enum.
func (e FindMyInitializeContextInactiveTime) Valid() bool {
	switch e {
	case FindMyInitializeContextInactiveTimeN0:
		return true
	default:
		return false
	}
}

// Defines values for FindMyLostRequestUserText.
const (
	FindMyLostRequestUserTextTrue FindMyLostRequestUserText = true
)

// Valid indicates whether the value is a known member of the FindMyLostRequestUserText enum.
func (e FindMyLostRequestUserText) Valid() bool {
	switch e {
	case FindMyLostRequestUserTextTrue:
		return true
	default:
		return false
	}
}

// Defines values for FindMyLostRequestLostModeEnabled.
const (
	FindMyLostRequestLostModeEnabledTrue FindMyLostRequestLostModeEnabled = true
)

// Valid indicates whether the value is a known member of the FindMyLostRequestLostModeEnabled enum.
func (e FindMyLostRequestLostModeEnabled) Valid() bool {
	switch e {
	case FindMyLostRequestLostModeEnabledTrue:
		return true
	default:
		return false
	}
}

// Defines values for FindMyLostRequestTrackingEnabled.
const (
	FindMyLostRequestTrackingEnabledTrue FindMyLostRequestTrackingEnabled = true
)

// Valid indicates whether the value is a known member of the FindMyLostRequestTrackingEnabled enum.
func (e FindMyLostRequestTrackingEnabled) Valid() bool {
	switch e {
	case FindMyLostRequestTrackingEnabledTrue:
		return true
	default:
		return false
	}
}

// Defines values for FindMyMessageRequestUserText.
const (
	FindMyMessageRequestUserTextTrue FindMyMessageRequestUserText = true
)

// Valid indicates whether the value is a known member of the FindMyMessageRequestUserText enum.
func (e FindMyMessageRequestUserText) Valid() bool {
	switch e {
	case FindMyMessageRequestUserTextTrue:
		return true
	default:
		return false
	}
}

// Defines values for FindMyRefreshRequestIsUpdatingAllLocations.
const (
	FindMyRefreshRequestIsUpdatingAllLocationsTrue FindMyRefreshRequestIsUpdatingAllLocations = true
)

// Valid indicates whether the value is a known member of the FindMyRefreshRequestIsUpdatingAllLocations enum.
func (e FindMyRefreshRequestIsUpdatingAllLocations) Valid() bool {
	switch e {
	case FindMyRefreshRequestIsUpdatingAllLocationsTrue:
		return true
	default:
		return false
	}
}

// Defines values for FindMySoundContextFmly.
const (
	FindMySoundContextFmlyTrue FindMySoundContextFmly = true
)

// Valid indicates whether the value is a known member of the FindMySoundContextFmly enum.
func (e FindMySoundContextFmly) Valid() bool {
	switch e {
	case FindMySoundContextFmlyTrue:
		return true
	default:
		return false
	}
}

// Defines values for FindMyTimezone.
const (
	USPacific FindMyTimezone = "US/Pacific"
)

// Valid indicates whether the value is a known member of the FindMyTimezone enum.
func (e FindMyTimezone) Valid() bool {
	switch e {
	case USPacific:
		return true
	default:
		return false
	}
}

// FindMyAPIVersion defines model for FindMyAPIVersion.
type FindMyAPIVersion string

// FindMyAcknowledgement Extensible command acknowledgement; physical completion is not inferred.
//
// Example: {}
type FindMyAcknowledgement map[string]FindMyUnknownJSON

// FindMyAllDevices defines model for FindMyAllDevices.
type FindMyAllDevices string

// FindMyAppName defines model for FindMyAppName.
type FindMyAppName string

// FindMyAppVersion defines model for FindMyAppVersion.
type FindMyAppVersion string

// FindMyClientContext defines model for FindMyClientContext.
type FindMyClientContext struct {
	AppName           FindMyAppName                        `json:"appName"`
	AppVersion        FindMyAppVersion                     `json:"appVersion"`
	ApiVersion        FindMyAPIVersion                     `json:"apiVersion"`
	DeviceListVersion FindMyClientContextDeviceListVersion `json:"deviceListVersion"`

	// Fmly Include family devices.
	Fmly           bool                             `json:"fmly"`
	Timezone       FindMyTimezone                   `json:"timezone"`
	InactiveTime   FindMyClientContextInactiveTime  `json:"inactiveTime"`
	ShouldLocate   *FindMyClientContextShouldLocate `json:"shouldLocate,omitempty"`
	SelectedDevice *FindMyAllDevices                `json:"selectedDevice,omitempty"`
}

// FindMyClientContextDeviceListVersion defines model for FindMyClientContext.DeviceListVersion.
type FindMyClientContextDeviceListVersion int

// FindMyClientContextInactiveTime defines model for FindMyClientContext.InactiveTime.
type FindMyClientContextInactiveTime int

// FindMyClientContextShouldLocate defines model for FindMyClientContext.ShouldLocate.
type FindMyClientContextShouldLocate bool

// FindMyCommandBytes Uninterpreted successful command body when the provider does not advertise JSON.
type FindMyCommandBytes = []byte

// FindMyCommandState Provider command state; acknowledgement does not establish physical completion.
type FindMyCommandState struct {
	CreateTimestamp      *int64                       `json:"createTimestamp,omitempty"`
	PlaySound            *bool                        `json:"playSound,omitempty"`
	StatusCode           *string                      `json:"statusCode,omitempty"`
	Strobe               *bool                        `json:"strobe,omitempty"`
	UserText             *bool                        `json:"userText,omitempty"`
	Vibrate              *bool                        `json:"vibrate,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON `json:"-"`
}

// FindMyDevice defines model for FindMyDevice.
type FindMyDevice struct {
	ActivationLocked *bool                `json:"activationLocked,omitempty"`
	AudioChannels    *[]FindMyUnknownJSON `json:"audioChannels,omitempty"`
	BaUUID           *string              `json:"baUUID,omitempty"`

	// BatteryLevel Provider battery level; no bound is inferred from a single sample.
	BatteryLevel      *float64                  `json:"batteryLevel,omitempty"`
	BatteryStatus     *string                   `json:"batteryStatus,omitempty"`
	CanWipeAfterLock  *bool                     `json:"canWipeAfterLock,omitempty"`
	DarkWake          *bool                     `json:"darkWake,omitempty"`
	DeviceClass       *string                   `json:"deviceClass,omitempty"`
	DeviceColor       nullable.Nullable[string] `json:"deviceColor,omitempty"`
	DeviceDisplayName *string                   `json:"deviceDisplayName,omitempty"`
	DeviceModel       *string                   `json:"deviceModel,omitempty"`

	// DeviceStatus Open provider status code.
	DeviceStatus *string `json:"deviceStatus,omitempty"`

	// Features Open device feature flags; absent flags do not establish capability.
	Features        *FindMyFeatures                   `json:"features,omitempty"`
	FmlyShare       *bool                             `json:"fmlyShare,omitempty"`
	Id              string                            `json:"id"`
	IsLocating      *bool                             `json:"isLocating,omitempty"`
	IsMac           *bool                             `json:"isMac,omitempty"`
	LocFoundEnabled *bool                             `json:"locFoundEnabled,omitempty"`
	Location        nullable.Nullable[FindMyLocation] `json:"location,omitempty"`
	LocationCapable *bool                             `json:"locationCapable,omitempty"`
	LocationEnabled *bool                             `json:"locationEnabled,omitempty"`

	// LockedTimestamp Named unknown provider value preserving omission separately from explicit null.
	LockedTimestamp nullable.Nullable[FindMyNullableJSON] `json:"lockedTimestamp,omitempty"`
	LostDevice      nullable.Nullable[FindMyLostState]    `json:"lostDevice,omitempty"`
	LostModeCapable *bool                                 `json:"lostModeCapable,omitempty"`
	LostModeEnabled *bool                                 `json:"lostModeEnabled,omitempty"`
	LostTimestamp   *string                               `json:"lostTimestamp,omitempty"`
	LowPowerMode    *bool                                 `json:"lowPowerMode,omitempty"`
	MaxMsgChar      *int                                  `json:"maxMsgChar,omitempty"`

	// Mesg Provider command state; acknowledgement does not establish physical completion.
	Mesg             nullable.Nullable[FindMyCommandState] `json:"mesg,omitempty"`
	ModelDisplayName *string                               `json:"modelDisplayName,omitempty"`

	// Msg Provider command state; acknowledgement does not establish physical completion.
	Msg            nullable.Nullable[FindMyCommandState] `json:"msg,omitempty"`
	Name           *string                               `json:"name,omitempty"`
	PasscodeLength *int                                  `json:"passcodeLength,omitempty"`
	PrsId          nullable.Nullable[string]             `json:"prsId,omitempty"`
	RawDeviceModel *string                               `json:"rawDeviceModel,omitempty"`

	// RemoteLock Provider command state; acknowledgement does not establish physical completion.
	RemoteLock nullable.Nullable[FindMyCommandState] `json:"remoteLock,omitempty"`

	// RemoteWipe Named unknown provider value preserving omission separately from explicit null.
	RemoteWipe nullable.Nullable[FindMyNullableJSON] `json:"remoteWipe,omitempty"`

	// Snd Provider command state; acknowledgement does not establish physical completion.
	Snd        nullable.Nullable[FindMyCommandState] `json:"snd,omitempty"`
	ThisDevice *bool                                 `json:"thisDevice,omitempty"`

	// TrackingInfo Named unknown provider value preserving omission separately from explicit null.
	TrackingInfo   nullable.Nullable[FindMyNullableJSON] `json:"trackingInfo,omitempty"`
	WipeInProgress *bool                                 `json:"wipeInProgress,omitempty"`

	// WipedTimestamp Named unknown provider value preserving omission separately from explicit null.
	WipedTimestamp       nullable.Nullable[FindMyNullableJSON] `json:"wipedTimestamp,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON          `json:"-"`
}

// FindMyEraseRequest defines model for FindMyEraseRequest.
type FindMyEraseRequest struct {
	AuthToken string `json:"authToken"`
	Text      string `json:"text"`
	Device    string `json:"device"`
	Passcode  string `json:"passcode"`
}

// FindMyEraseTokenRequest defines model for FindMyEraseTokenRequest.
type FindMyEraseTokenRequest struct {
	// DsWebAuthToken Authenticated session token; the reference can send explicit null when absent.
	DsWebAuthToken nullable.Nullable[string] `json:"dsWebAuthToken"`
}

// FindMyEraseTokenResponse Missing tokens are representable and must stop before a remote erase command.
type FindMyEraseTokenResponse struct {
	Tokens               *FindMyEraseTokens           `json:"tokens,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON `json:"-"`
}

// FindMyEraseTokens defines model for FindMyEraseTokens.
type FindMyEraseTokens struct {
	MmeFMIPWebEraseDeviceToken *string                      `json:"mmeFMIPWebEraseDeviceToken,omitempty"`
	AdditionalProperties       map[string]FindMyUnknownJSON `json:"-"`
}

// FindMyError defines model for FindMyError.
type FindMyError struct {
	// Error Named unknown provider value preserving omission separately from explicit null.
	Error nullable.Nullable[FindMyNullableJSON] `json:"error,omitempty"`

	// ErrorCode Named unknown provider value preserving omission separately from explicit null.
	ErrorCode nullable.Nullable[FindMyNullableJSON] `json:"errorCode,omitempty"`

	// Reason Named unknown provider value preserving omission separately from explicit null.
	Reason               nullable.Nullable[FindMyNullableJSON] `json:"reason,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON          `json:"-"`
}

// FindMyFeatures Open device feature flags; absent flags do not establish capability.
type FindMyFeatures struct {
	BTR *bool `json:"BTR,omitempty"`
	CLK *bool `json:"CLK,omitempty"`
	CLT *bool `json:"CLT,omitempty"`
	CWP *bool `json:"CWP,omitempty"`
	KEY *bool `json:"KEY,omitempty"`
	KPD *bool `json:"KPD,omitempty"`
	LCK *bool `json:"LCK,omitempty"`
	LKL *bool `json:"LKL,omitempty"`
	LKM *bool `json:"LKM,omitempty"`
	LLC *bool `json:"LLC,omitempty"`
	LMG *bool `json:"LMG,omitempty"`

	// LOC Location support.
	LOC *bool `json:"LOC,omitempty"`
	LST *bool `json:"LST,omitempty"`
	MCS *bool `json:"MCS,omitempty"`

	// MSG Messaging support.
	MSG *bool `json:"MSG,omitempty"`
	PIN *bool `json:"PIN,omitempty"`
	PSS *bool `json:"PSS,omitempty"`
	REM *bool `json:"REM,omitempty"`

	// SND Sound support.
	SND *bool `json:"SND,omitempty"`
	SPN *bool `json:"SPN,omitempty"`
	SVP *bool `json:"SVP,omitempty"`
	TEU *bool `json:"TEU,omitempty"`

	// WIP Remote erase support.
	WIP                  *bool                        `json:"WIP,omitempty"`
	WMG                  *bool                        `json:"WMG,omitempty"`
	XRM                  *bool                        `json:"XRM,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON `json:"-"`
}

// FindMyInitializeContext defines model for FindMyInitializeContext.
type FindMyInitializeContext struct {
	AppName           FindMyAppName                            `json:"appName"`
	AppVersion        FindMyAppVersion                         `json:"appVersion"`
	ApiVersion        FindMyAPIVersion                         `json:"apiVersion"`
	DeviceListVersion FindMyInitializeContextDeviceListVersion `json:"deviceListVersion"`
	Fmly              bool                                     `json:"fmly"`
	Timezone          FindMyTimezone                           `json:"timezone"`
	InactiveTime      FindMyInitializeContextInactiveTime      `json:"inactiveTime"`
}

// FindMyInitializeContextDeviceListVersion defines model for FindMyInitializeContext.DeviceListVersion.
type FindMyInitializeContextDeviceListVersion int

// FindMyInitializeContextInactiveTime defines model for FindMyInitializeContext.InactiveTime.
type FindMyInitializeContextInactiveTime int

// FindMyInitializeRequest Example: {"clientContext":{"apiVersion":"3.0","appName":"iCloud Find (Web)","appVersion":"2.0","deviceListVersion":1,"fmly":false,"inactiveTime":0,"timezone":"US/Pacific"}}
type FindMyInitializeRequest struct {
	ClientContext FindMyInitializeContext `json:"clientContext"`
}

// FindMyLocation defines model for FindMyLocation.
type FindMyLocation struct {
	Altitude           *float64 `json:"altitude,omitempty"`
	FloorLevel         *int     `json:"floorLevel,omitempty"`
	HorizontalAccuracy *float64 `json:"horizontalAccuracy,omitempty"`
	IsInaccurate       *bool    `json:"isInaccurate,omitempty"`
	IsOld              *bool    `json:"isOld,omitempty"`

	// Latitude Latitude in degrees.
	Latitude         *float64 `json:"latitude,omitempty"`
	LocationFinished *bool    `json:"locationFinished,omitempty"`
	LocationType     *string  `json:"locationType,omitempty"`

	// Longitude Longitude in degrees.
	Longitude    *float64 `json:"longitude,omitempty"`
	PositionType *string  `json:"positionType,omitempty"`

	// TimeStamp Provider location timestamp in milliseconds since the Unix epoch.
	TimeStamp            *int64                       `json:"timeStamp,omitempty"`
	VerticalAccuracy     *float64                     `json:"verticalAccuracy,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON `json:"-"`
}

// FindMyLostRequest defines model for FindMyLostRequest.
type FindMyLostRequest struct {
	Text            string                           `json:"text"`
	UserText        FindMyLostRequestUserText        `json:"userText"`
	OwnerNbr        string                           `json:"ownerNbr"`
	LostModeEnabled FindMyLostRequestLostModeEnabled `json:"lostModeEnabled"`
	TrackingEnabled FindMyLostRequestTrackingEnabled `json:"trackingEnabled"`
	Device          string                           `json:"device"`
	Passcode        string                           `json:"passcode"`
}

// FindMyLostRequestUserText defines model for FindMyLostRequest.UserText.
type FindMyLostRequestUserText bool

// FindMyLostRequestLostModeEnabled defines model for FindMyLostRequest.LostModeEnabled.
type FindMyLostRequestLostModeEnabled bool

// FindMyLostRequestTrackingEnabled defines model for FindMyLostRequest.TrackingEnabled.
type FindMyLostRequestTrackingEnabled bool

// FindMyLostState defines model for FindMyLostState.
type FindMyLostState struct {
	CreateTimestamp      *int64                       `json:"createTimestamp,omitempty"`
	EmailUpdates         *bool                        `json:"emailUpdates,omitempty"`
	OwnerNbr             *string                      `json:"ownerNbr,omitempty"`
	Sound                *bool                        `json:"sound,omitempty"`
	StatusCode           *string                      `json:"statusCode,omitempty"`
	StopLostMode         *bool                        `json:"stopLostMode,omitempty"`
	Text                 *string                      `json:"text,omitempty"`
	UserText             *bool                        `json:"userText,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON `json:"-"`
}

// FindMyMember defines model for FindMyMember.
type FindMyMember struct {
	AccountFormatter *int    `json:"accountFormatter,omitempty"`
	AppleId          *string `json:"appleId,omitempty"`

	// DeviceFetchStatus Open family device fetch status; LOADING members may require bounded polling.
	DeviceFetchStatus    *string                      `json:"deviceFetchStatus,omitempty"`
	FirstName            *string                      `json:"firstName,omitempty"`
	IsHSA                *bool                        `json:"isHSA,omitempty"`
	LastName             *string                      `json:"lastName,omitempty"`
	UseAuthWidget        *bool                        `json:"useAuthWidget,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON `json:"-"`
}

// FindMyMessageRequest defines model for FindMyMessageRequest.
type FindMyMessageRequest struct {
	Device   string                       `json:"device"`
	Subject  string                       `json:"subject"`
	UserText FindMyMessageRequestUserText `json:"userText"`
	Text     string                       `json:"text"`
	Sound    bool                         `json:"sound"`
	Vibrate  bool                         `json:"vibrate"`
	Strobe   bool                         `json:"strobe"`
}

// FindMyMessageRequestUserText defines model for FindMyMessageRequest.UserText.
type FindMyMessageRequestUserText bool

// FindMyNullableJSON Named unknown provider value preserving omission separately from explicit null.
type FindMyNullableJSON = json.RawMessage

// FindMyRefreshRequest Example: {"clientContext":{"apiVersion":"3.0","appName":"iCloud Find (Web)","appVersion":"2.0","deviceListVersion":1,"fmly":false,"inactiveTime":0,"timezone":"US/Pacific"},"serverContext":{"future":true}}
type FindMyRefreshRequest struct {
	ClientContext FindMyClientContext `json:"clientContext"`

	// ServerContext Provider-issued opaque refresh context; the reference clears theftLoss before reuse.
	ServerContext          nullable.Nullable[FindMyServerContext]      `json:"serverContext"`
	IsUpdatingAllLocations *FindMyRefreshRequestIsUpdatingAllLocations `json:"isUpdatingAllLocations,omitempty"`
}

// FindMyRefreshRequestIsUpdatingAllLocations defines model for FindMyRefreshRequest.IsUpdatingAllLocations.
type FindMyRefreshRequestIsUpdatingAllLocations bool

// FindMyRefreshResponse Partial refresh; absent or empty content does not imply removal of cached devices.
//
// Example: {"content":[],"serverContext":{"future":true}}
type FindMyRefreshResponse struct {
	Content *[]FindMyDevice `json:"content,omitempty"`

	// ServerContext Provider-issued opaque refresh context; the reference clears theftLoss before reuse.
	ServerContext        nullable.Nullable[FindMyServerContext] `json:"serverContext,omitempty"`
	UserInfo             nullable.Nullable[FindMyUserInfo]      `json:"userInfo,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON           `json:"-"`
}

// FindMyServerContext Provider-issued opaque refresh context; the reference clears theftLoss before reuse.
type FindMyServerContext struct {
	// TheftLoss Named unknown provider value preserving omission separately from explicit null.
	TheftLoss            nullable.Nullable[FindMyNullableJSON] `json:"theftLoss,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON          `json:"-"`
}

// FindMySoundContext defines model for FindMySoundContext.
type FindMySoundContext struct {
	Fmly FindMySoundContextFmly `json:"fmly"`
}

// FindMySoundContextFmly defines model for FindMySoundContext.Fmly.
type FindMySoundContextFmly bool

// FindMySoundRequest defines model for FindMySoundRequest.
type FindMySoundRequest struct {
	Device        string             `json:"device"`
	Subject       string             `json:"subject"`
	ClientContext FindMySoundContext `json:"clientContext"`
}

// FindMyTimezone defines model for FindMyTimezone.
type FindMyTimezone string

// FindMyUnknownJSON Extensible provider metadata retained without floating-point conversion.
type FindMyUnknownJSON = json.RawMessage

// FindMyUserInfo defines model for FindMyUserInfo.
type FindMyUserInfo struct {
	AccountFormatter     *int                         `json:"accountFormatter,omitempty"`
	FirstName            *string                      `json:"firstName,omitempty"`
	HasMembers           *bool                        `json:"hasMembers,omitempty"`
	LastName             *string                      `json:"lastName,omitempty"`
	MembersInfo          *map[string]FindMyMember     `json:"membersInfo,omitempty"`
	AdditionalProperties map[string]FindMyUnknownJSON `json:"-"`
}

// Getter for additional properties for FindMyCommandState. Returns the specified
// element and whether it was found
func (a FindMyCommandState) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyCommandState
func (a *FindMyCommandState) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyCommandState to handle AdditionalProperties
func (a *FindMyCommandState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["createTimestamp"]; found {
		err = json.Unmarshal(raw, &a.CreateTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'createTimestamp': %w", err)
		}
		delete(object, "createTimestamp")
	}

	if raw, found := object["playSound"]; found {
		err = json.Unmarshal(raw, &a.PlaySound)
		if err != nil {
			return fmt.Errorf("error reading 'playSound': %w", err)
		}
		delete(object, "playSound")
	}

	if raw, found := object["statusCode"]; found {
		err = json.Unmarshal(raw, &a.StatusCode)
		if err != nil {
			return fmt.Errorf("error reading 'statusCode': %w", err)
		}
		delete(object, "statusCode")
	}

	if raw, found := object["strobe"]; found {
		err = json.Unmarshal(raw, &a.Strobe)
		if err != nil {
			return fmt.Errorf("error reading 'strobe': %w", err)
		}
		delete(object, "strobe")
	}

	if raw, found := object["userText"]; found {
		err = json.Unmarshal(raw, &a.UserText)
		if err != nil {
			return fmt.Errorf("error reading 'userText': %w", err)
		}
		delete(object, "userText")
	}

	if raw, found := object["vibrate"]; found {
		err = json.Unmarshal(raw, &a.Vibrate)
		if err != nil {
			return fmt.Errorf("error reading 'vibrate': %w", err)
		}
		delete(object, "vibrate")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyCommandState to handle AdditionalProperties
func (a FindMyCommandState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CreateTimestamp != nil {
		object["createTimestamp"], err = json.Marshal(a.CreateTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'createTimestamp': %w", err)
		}
	}

	if a.PlaySound != nil {
		object["playSound"], err = json.Marshal(a.PlaySound)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playSound': %w", err)
		}
	}

	if a.StatusCode != nil {
		object["statusCode"], err = json.Marshal(a.StatusCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'statusCode': %w", err)
		}
	}

	if a.Strobe != nil {
		object["strobe"], err = json.Marshal(a.Strobe)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'strobe': %w", err)
		}
	}

	if a.UserText != nil {
		object["userText"], err = json.Marshal(a.UserText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'userText': %w", err)
		}
	}

	if a.Vibrate != nil {
		object["vibrate"], err = json.Marshal(a.Vibrate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vibrate': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyDevice. Returns the specified
// element and whether it was found
func (a FindMyDevice) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyDevice
func (a *FindMyDevice) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyDevice to handle AdditionalProperties
func (a *FindMyDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["activationLocked"]; found {
		err = json.Unmarshal(raw, &a.ActivationLocked)
		if err != nil {
			return fmt.Errorf("error reading 'activationLocked': %w", err)
		}
		delete(object, "activationLocked")
	}

	if raw, found := object["audioChannels"]; found {
		err = json.Unmarshal(raw, &a.AudioChannels)
		if err != nil {
			return fmt.Errorf("error reading 'audioChannels': %w", err)
		}
		delete(object, "audioChannels")
	}

	if raw, found := object["baUUID"]; found {
		err = json.Unmarshal(raw, &a.BaUUID)
		if err != nil {
			return fmt.Errorf("error reading 'baUUID': %w", err)
		}
		delete(object, "baUUID")
	}

	if raw, found := object["batteryLevel"]; found {
		err = json.Unmarshal(raw, &a.BatteryLevel)
		if err != nil {
			return fmt.Errorf("error reading 'batteryLevel': %w", err)
		}
		delete(object, "batteryLevel")
	}

	if raw, found := object["batteryStatus"]; found {
		err = json.Unmarshal(raw, &a.BatteryStatus)
		if err != nil {
			return fmt.Errorf("error reading 'batteryStatus': %w", err)
		}
		delete(object, "batteryStatus")
	}

	if raw, found := object["canWipeAfterLock"]; found {
		err = json.Unmarshal(raw, &a.CanWipeAfterLock)
		if err != nil {
			return fmt.Errorf("error reading 'canWipeAfterLock': %w", err)
		}
		delete(object, "canWipeAfterLock")
	}

	if raw, found := object["darkWake"]; found {
		err = json.Unmarshal(raw, &a.DarkWake)
		if err != nil {
			return fmt.Errorf("error reading 'darkWake': %w", err)
		}
		delete(object, "darkWake")
	}

	if raw, found := object["deviceClass"]; found {
		err = json.Unmarshal(raw, &a.DeviceClass)
		if err != nil {
			return fmt.Errorf("error reading 'deviceClass': %w", err)
		}
		delete(object, "deviceClass")
	}

	if raw, found := object["deviceColor"]; found {
		err = json.Unmarshal(raw, &a.DeviceColor)
		if err != nil {
			return fmt.Errorf("error reading 'deviceColor': %w", err)
		}
		delete(object, "deviceColor")
	}

	if raw, found := object["deviceDisplayName"]; found {
		err = json.Unmarshal(raw, &a.DeviceDisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'deviceDisplayName': %w", err)
		}
		delete(object, "deviceDisplayName")
	}

	if raw, found := object["deviceModel"]; found {
		err = json.Unmarshal(raw, &a.DeviceModel)
		if err != nil {
			return fmt.Errorf("error reading 'deviceModel': %w", err)
		}
		delete(object, "deviceModel")
	}

	if raw, found := object["deviceStatus"]; found {
		err = json.Unmarshal(raw, &a.DeviceStatus)
		if err != nil {
			return fmt.Errorf("error reading 'deviceStatus': %w", err)
		}
		delete(object, "deviceStatus")
	}

	if raw, found := object["features"]; found {
		err = json.Unmarshal(raw, &a.Features)
		if err != nil {
			return fmt.Errorf("error reading 'features': %w", err)
		}
		delete(object, "features")
	}

	if raw, found := object["fmlyShare"]; found {
		err = json.Unmarshal(raw, &a.FmlyShare)
		if err != nil {
			return fmt.Errorf("error reading 'fmlyShare': %w", err)
		}
		delete(object, "fmlyShare")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["isLocating"]; found {
		err = json.Unmarshal(raw, &a.IsLocating)
		if err != nil {
			return fmt.Errorf("error reading 'isLocating': %w", err)
		}
		delete(object, "isLocating")
	}

	if raw, found := object["isMac"]; found {
		err = json.Unmarshal(raw, &a.IsMac)
		if err != nil {
			return fmt.Errorf("error reading 'isMac': %w", err)
		}
		delete(object, "isMac")
	}

	if raw, found := object["locFoundEnabled"]; found {
		err = json.Unmarshal(raw, &a.LocFoundEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'locFoundEnabled': %w", err)
		}
		delete(object, "locFoundEnabled")
	}

	if raw, found := object["location"]; found {
		err = json.Unmarshal(raw, &a.Location)
		if err != nil {
			return fmt.Errorf("error reading 'location': %w", err)
		}
		delete(object, "location")
	}

	if raw, found := object["locationCapable"]; found {
		err = json.Unmarshal(raw, &a.LocationCapable)
		if err != nil {
			return fmt.Errorf("error reading 'locationCapable': %w", err)
		}
		delete(object, "locationCapable")
	}

	if raw, found := object["locationEnabled"]; found {
		err = json.Unmarshal(raw, &a.LocationEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'locationEnabled': %w", err)
		}
		delete(object, "locationEnabled")
	}

	if raw, found := object["lockedTimestamp"]; found {
		err = json.Unmarshal(raw, &a.LockedTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'lockedTimestamp': %w", err)
		}
		delete(object, "lockedTimestamp")
	}

	if raw, found := object["lostDevice"]; found {
		err = json.Unmarshal(raw, &a.LostDevice)
		if err != nil {
			return fmt.Errorf("error reading 'lostDevice': %w", err)
		}
		delete(object, "lostDevice")
	}

	if raw, found := object["lostModeCapable"]; found {
		err = json.Unmarshal(raw, &a.LostModeCapable)
		if err != nil {
			return fmt.Errorf("error reading 'lostModeCapable': %w", err)
		}
		delete(object, "lostModeCapable")
	}

	if raw, found := object["lostModeEnabled"]; found {
		err = json.Unmarshal(raw, &a.LostModeEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'lostModeEnabled': %w", err)
		}
		delete(object, "lostModeEnabled")
	}

	if raw, found := object["lostTimestamp"]; found {
		err = json.Unmarshal(raw, &a.LostTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'lostTimestamp': %w", err)
		}
		delete(object, "lostTimestamp")
	}

	if raw, found := object["lowPowerMode"]; found {
		err = json.Unmarshal(raw, &a.LowPowerMode)
		if err != nil {
			return fmt.Errorf("error reading 'lowPowerMode': %w", err)
		}
		delete(object, "lowPowerMode")
	}

	if raw, found := object["maxMsgChar"]; found {
		err = json.Unmarshal(raw, &a.MaxMsgChar)
		if err != nil {
			return fmt.Errorf("error reading 'maxMsgChar': %w", err)
		}
		delete(object, "maxMsgChar")
	}

	if raw, found := object["mesg"]; found {
		err = json.Unmarshal(raw, &a.Mesg)
		if err != nil {
			return fmt.Errorf("error reading 'mesg': %w", err)
		}
		delete(object, "mesg")
	}

	if raw, found := object["modelDisplayName"]; found {
		err = json.Unmarshal(raw, &a.ModelDisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'modelDisplayName': %w", err)
		}
		delete(object, "modelDisplayName")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["passcodeLength"]; found {
		err = json.Unmarshal(raw, &a.PasscodeLength)
		if err != nil {
			return fmt.Errorf("error reading 'passcodeLength': %w", err)
		}
		delete(object, "passcodeLength")
	}

	if raw, found := object["prsId"]; found {
		err = json.Unmarshal(raw, &a.PrsId)
		if err != nil {
			return fmt.Errorf("error reading 'prsId': %w", err)
		}
		delete(object, "prsId")
	}

	if raw, found := object["rawDeviceModel"]; found {
		err = json.Unmarshal(raw, &a.RawDeviceModel)
		if err != nil {
			return fmt.Errorf("error reading 'rawDeviceModel': %w", err)
		}
		delete(object, "rawDeviceModel")
	}

	if raw, found := object["remoteLock"]; found {
		err = json.Unmarshal(raw, &a.RemoteLock)
		if err != nil {
			return fmt.Errorf("error reading 'remoteLock': %w", err)
		}
		delete(object, "remoteLock")
	}

	if raw, found := object["remoteWipe"]; found {
		err = json.Unmarshal(raw, &a.RemoteWipe)
		if err != nil {
			return fmt.Errorf("error reading 'remoteWipe': %w", err)
		}
		delete(object, "remoteWipe")
	}

	if raw, found := object["snd"]; found {
		err = json.Unmarshal(raw, &a.Snd)
		if err != nil {
			return fmt.Errorf("error reading 'snd': %w", err)
		}
		delete(object, "snd")
	}

	if raw, found := object["thisDevice"]; found {
		err = json.Unmarshal(raw, &a.ThisDevice)
		if err != nil {
			return fmt.Errorf("error reading 'thisDevice': %w", err)
		}
		delete(object, "thisDevice")
	}

	if raw, found := object["trackingInfo"]; found {
		err = json.Unmarshal(raw, &a.TrackingInfo)
		if err != nil {
			return fmt.Errorf("error reading 'trackingInfo': %w", err)
		}
		delete(object, "trackingInfo")
	}

	if raw, found := object["wipeInProgress"]; found {
		err = json.Unmarshal(raw, &a.WipeInProgress)
		if err != nil {
			return fmt.Errorf("error reading 'wipeInProgress': %w", err)
		}
		delete(object, "wipeInProgress")
	}

	if raw, found := object["wipedTimestamp"]; found {
		err = json.Unmarshal(raw, &a.WipedTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'wipedTimestamp': %w", err)
		}
		delete(object, "wipedTimestamp")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyDevice to handle AdditionalProperties
func (a FindMyDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ActivationLocked != nil {
		object["activationLocked"], err = json.Marshal(a.ActivationLocked)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'activationLocked': %w", err)
		}
	}

	if a.AudioChannels != nil {
		object["audioChannels"], err = json.Marshal(a.AudioChannels)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'audioChannels': %w", err)
		}
	}

	if a.BaUUID != nil {
		object["baUUID"], err = json.Marshal(a.BaUUID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'baUUID': %w", err)
		}
	}

	if a.BatteryLevel != nil {
		object["batteryLevel"], err = json.Marshal(a.BatteryLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'batteryLevel': %w", err)
		}
	}

	if a.BatteryStatus != nil {
		object["batteryStatus"], err = json.Marshal(a.BatteryStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'batteryStatus': %w", err)
		}
	}

	if a.CanWipeAfterLock != nil {
		object["canWipeAfterLock"], err = json.Marshal(a.CanWipeAfterLock)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'canWipeAfterLock': %w", err)
		}
	}

	if a.DarkWake != nil {
		object["darkWake"], err = json.Marshal(a.DarkWake)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'darkWake': %w", err)
		}
	}

	if a.DeviceClass != nil {
		object["deviceClass"], err = json.Marshal(a.DeviceClass)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceClass': %w", err)
		}
	}

	if a.DeviceColor != nil {
		object["deviceColor"], err = json.Marshal(a.DeviceColor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceColor': %w", err)
		}
	}

	if a.DeviceDisplayName != nil {
		object["deviceDisplayName"], err = json.Marshal(a.DeviceDisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceDisplayName': %w", err)
		}
	}

	if a.DeviceModel != nil {
		object["deviceModel"], err = json.Marshal(a.DeviceModel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceModel': %w", err)
		}
	}

	if a.DeviceStatus != nil {
		object["deviceStatus"], err = json.Marshal(a.DeviceStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceStatus': %w", err)
		}
	}

	if a.Features != nil {
		object["features"], err = json.Marshal(a.Features)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'features': %w", err)
		}
	}

	if a.FmlyShare != nil {
		object["fmlyShare"], err = json.Marshal(a.FmlyShare)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fmlyShare': %w", err)
		}
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.IsLocating != nil {
		object["isLocating"], err = json.Marshal(a.IsLocating)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isLocating': %w", err)
		}
	}

	if a.IsMac != nil {
		object["isMac"], err = json.Marshal(a.IsMac)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isMac': %w", err)
		}
	}

	if a.LocFoundEnabled != nil {
		object["locFoundEnabled"], err = json.Marshal(a.LocFoundEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'locFoundEnabled': %w", err)
		}
	}

	if a.Location != nil {
		object["location"], err = json.Marshal(a.Location)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'location': %w", err)
		}
	}

	if a.LocationCapable != nil {
		object["locationCapable"], err = json.Marshal(a.LocationCapable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'locationCapable': %w", err)
		}
	}

	if a.LocationEnabled != nil {
		object["locationEnabled"], err = json.Marshal(a.LocationEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'locationEnabled': %w", err)
		}
	}

	if a.LockedTimestamp != nil {
		object["lockedTimestamp"], err = json.Marshal(a.LockedTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lockedTimestamp': %w", err)
		}
	}

	if a.LostDevice != nil {
		object["lostDevice"], err = json.Marshal(a.LostDevice)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lostDevice': %w", err)
		}
	}

	if a.LostModeCapable != nil {
		object["lostModeCapable"], err = json.Marshal(a.LostModeCapable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lostModeCapable': %w", err)
		}
	}

	if a.LostModeEnabled != nil {
		object["lostModeEnabled"], err = json.Marshal(a.LostModeEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lostModeEnabled': %w", err)
		}
	}

	if a.LostTimestamp != nil {
		object["lostTimestamp"], err = json.Marshal(a.LostTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lostTimestamp': %w", err)
		}
	}

	if a.LowPowerMode != nil {
		object["lowPowerMode"], err = json.Marshal(a.LowPowerMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lowPowerMode': %w", err)
		}
	}

	if a.MaxMsgChar != nil {
		object["maxMsgChar"], err = json.Marshal(a.MaxMsgChar)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'maxMsgChar': %w", err)
		}
	}

	if a.Mesg != nil {
		object["mesg"], err = json.Marshal(a.Mesg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mesg': %w", err)
		}
	}

	if a.ModelDisplayName != nil {
		object["modelDisplayName"], err = json.Marshal(a.ModelDisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelDisplayName': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.PasscodeLength != nil {
		object["passcodeLength"], err = json.Marshal(a.PasscodeLength)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'passcodeLength': %w", err)
		}
	}

	if a.PrsId != nil {
		object["prsId"], err = json.Marshal(a.PrsId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'prsId': %w", err)
		}
	}

	if a.RawDeviceModel != nil {
		object["rawDeviceModel"], err = json.Marshal(a.RawDeviceModel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rawDeviceModel': %w", err)
		}
	}

	if a.RemoteLock != nil {
		object["remoteLock"], err = json.Marshal(a.RemoteLock)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'remoteLock': %w", err)
		}
	}

	if a.RemoteWipe != nil {
		object["remoteWipe"], err = json.Marshal(a.RemoteWipe)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'remoteWipe': %w", err)
		}
	}

	if a.Snd != nil {
		object["snd"], err = json.Marshal(a.Snd)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'snd': %w", err)
		}
	}

	if a.ThisDevice != nil {
		object["thisDevice"], err = json.Marshal(a.ThisDevice)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'thisDevice': %w", err)
		}
	}

	if a.TrackingInfo != nil {
		object["trackingInfo"], err = json.Marshal(a.TrackingInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'trackingInfo': %w", err)
		}
	}

	if a.WipeInProgress != nil {
		object["wipeInProgress"], err = json.Marshal(a.WipeInProgress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'wipeInProgress': %w", err)
		}
	}

	if a.WipedTimestamp != nil {
		object["wipedTimestamp"], err = json.Marshal(a.WipedTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'wipedTimestamp': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyEraseTokenResponse. Returns the specified
// element and whether it was found
func (a FindMyEraseTokenResponse) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyEraseTokenResponse
func (a *FindMyEraseTokenResponse) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyEraseTokenResponse to handle AdditionalProperties
func (a *FindMyEraseTokenResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["tokens"]; found {
		err = json.Unmarshal(raw, &a.Tokens)
		if err != nil {
			return fmt.Errorf("error reading 'tokens': %w", err)
		}
		delete(object, "tokens")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyEraseTokenResponse to handle AdditionalProperties
func (a FindMyEraseTokenResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Tokens != nil {
		object["tokens"], err = json.Marshal(a.Tokens)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tokens': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyEraseTokens. Returns the specified
// element and whether it was found
func (a FindMyEraseTokens) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyEraseTokens
func (a *FindMyEraseTokens) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyEraseTokens to handle AdditionalProperties
func (a *FindMyEraseTokens) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["mmeFMIPWebEraseDeviceToken"]; found {
		err = json.Unmarshal(raw, &a.MmeFMIPWebEraseDeviceToken)
		if err != nil {
			return fmt.Errorf("error reading 'mmeFMIPWebEraseDeviceToken': %w", err)
		}
		delete(object, "mmeFMIPWebEraseDeviceToken")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyEraseTokens to handle AdditionalProperties
func (a FindMyEraseTokens) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MmeFMIPWebEraseDeviceToken != nil {
		object["mmeFMIPWebEraseDeviceToken"], err = json.Marshal(a.MmeFMIPWebEraseDeviceToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mmeFMIPWebEraseDeviceToken': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyError. Returns the specified
// element and whether it was found
func (a FindMyError) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyError
func (a *FindMyError) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyError to handle AdditionalProperties
func (a *FindMyError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["errorCode"]; found {
		err = json.Unmarshal(raw, &a.ErrorCode)
		if err != nil {
			return fmt.Errorf("error reading 'errorCode': %w", err)
		}
		delete(object, "errorCode")
	}

	if raw, found := object["reason"]; found {
		err = json.Unmarshal(raw, &a.Reason)
		if err != nil {
			return fmt.Errorf("error reading 'reason': %w", err)
		}
		delete(object, "reason")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyError to handle AdditionalProperties
func (a FindMyError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Error != nil {
		object["error"], err = json.Marshal(a.Error)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'error': %w", err)
		}
	}

	if a.ErrorCode != nil {
		object["errorCode"], err = json.Marshal(a.ErrorCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errorCode': %w", err)
		}
	}

	if a.Reason != nil {
		object["reason"], err = json.Marshal(a.Reason)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reason': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyFeatures. Returns the specified
// element and whether it was found
func (a FindMyFeatures) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyFeatures
func (a *FindMyFeatures) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyFeatures to handle AdditionalProperties
func (a *FindMyFeatures) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["BTR"]; found {
		err = json.Unmarshal(raw, &a.BTR)
		if err != nil {
			return fmt.Errorf("error reading 'BTR': %w", err)
		}
		delete(object, "BTR")
	}

	if raw, found := object["CLK"]; found {
		err = json.Unmarshal(raw, &a.CLK)
		if err != nil {
			return fmt.Errorf("error reading 'CLK': %w", err)
		}
		delete(object, "CLK")
	}

	if raw, found := object["CLT"]; found {
		err = json.Unmarshal(raw, &a.CLT)
		if err != nil {
			return fmt.Errorf("error reading 'CLT': %w", err)
		}
		delete(object, "CLT")
	}

	if raw, found := object["CWP"]; found {
		err = json.Unmarshal(raw, &a.CWP)
		if err != nil {
			return fmt.Errorf("error reading 'CWP': %w", err)
		}
		delete(object, "CWP")
	}

	if raw, found := object["KEY"]; found {
		err = json.Unmarshal(raw, &a.KEY)
		if err != nil {
			return fmt.Errorf("error reading 'KEY': %w", err)
		}
		delete(object, "KEY")
	}

	if raw, found := object["KPD"]; found {
		err = json.Unmarshal(raw, &a.KPD)
		if err != nil {
			return fmt.Errorf("error reading 'KPD': %w", err)
		}
		delete(object, "KPD")
	}

	if raw, found := object["LCK"]; found {
		err = json.Unmarshal(raw, &a.LCK)
		if err != nil {
			return fmt.Errorf("error reading 'LCK': %w", err)
		}
		delete(object, "LCK")
	}

	if raw, found := object["LKL"]; found {
		err = json.Unmarshal(raw, &a.LKL)
		if err != nil {
			return fmt.Errorf("error reading 'LKL': %w", err)
		}
		delete(object, "LKL")
	}

	if raw, found := object["LKM"]; found {
		err = json.Unmarshal(raw, &a.LKM)
		if err != nil {
			return fmt.Errorf("error reading 'LKM': %w", err)
		}
		delete(object, "LKM")
	}

	if raw, found := object["LLC"]; found {
		err = json.Unmarshal(raw, &a.LLC)
		if err != nil {
			return fmt.Errorf("error reading 'LLC': %w", err)
		}
		delete(object, "LLC")
	}

	if raw, found := object["LMG"]; found {
		err = json.Unmarshal(raw, &a.LMG)
		if err != nil {
			return fmt.Errorf("error reading 'LMG': %w", err)
		}
		delete(object, "LMG")
	}

	if raw, found := object["LOC"]; found {
		err = json.Unmarshal(raw, &a.LOC)
		if err != nil {
			return fmt.Errorf("error reading 'LOC': %w", err)
		}
		delete(object, "LOC")
	}

	if raw, found := object["LST"]; found {
		err = json.Unmarshal(raw, &a.LST)
		if err != nil {
			return fmt.Errorf("error reading 'LST': %w", err)
		}
		delete(object, "LST")
	}

	if raw, found := object["MCS"]; found {
		err = json.Unmarshal(raw, &a.MCS)
		if err != nil {
			return fmt.Errorf("error reading 'MCS': %w", err)
		}
		delete(object, "MCS")
	}

	if raw, found := object["MSG"]; found {
		err = json.Unmarshal(raw, &a.MSG)
		if err != nil {
			return fmt.Errorf("error reading 'MSG': %w", err)
		}
		delete(object, "MSG")
	}

	if raw, found := object["PIN"]; found {
		err = json.Unmarshal(raw, &a.PIN)
		if err != nil {
			return fmt.Errorf("error reading 'PIN': %w", err)
		}
		delete(object, "PIN")
	}

	if raw, found := object["PSS"]; found {
		err = json.Unmarshal(raw, &a.PSS)
		if err != nil {
			return fmt.Errorf("error reading 'PSS': %w", err)
		}
		delete(object, "PSS")
	}

	if raw, found := object["REM"]; found {
		err = json.Unmarshal(raw, &a.REM)
		if err != nil {
			return fmt.Errorf("error reading 'REM': %w", err)
		}
		delete(object, "REM")
	}

	if raw, found := object["SND"]; found {
		err = json.Unmarshal(raw, &a.SND)
		if err != nil {
			return fmt.Errorf("error reading 'SND': %w", err)
		}
		delete(object, "SND")
	}

	if raw, found := object["SPN"]; found {
		err = json.Unmarshal(raw, &a.SPN)
		if err != nil {
			return fmt.Errorf("error reading 'SPN': %w", err)
		}
		delete(object, "SPN")
	}

	if raw, found := object["SVP"]; found {
		err = json.Unmarshal(raw, &a.SVP)
		if err != nil {
			return fmt.Errorf("error reading 'SVP': %w", err)
		}
		delete(object, "SVP")
	}

	if raw, found := object["TEU"]; found {
		err = json.Unmarshal(raw, &a.TEU)
		if err != nil {
			return fmt.Errorf("error reading 'TEU': %w", err)
		}
		delete(object, "TEU")
	}

	if raw, found := object["WIP"]; found {
		err = json.Unmarshal(raw, &a.WIP)
		if err != nil {
			return fmt.Errorf("error reading 'WIP': %w", err)
		}
		delete(object, "WIP")
	}

	if raw, found := object["WMG"]; found {
		err = json.Unmarshal(raw, &a.WMG)
		if err != nil {
			return fmt.Errorf("error reading 'WMG': %w", err)
		}
		delete(object, "WMG")
	}

	if raw, found := object["XRM"]; found {
		err = json.Unmarshal(raw, &a.XRM)
		if err != nil {
			return fmt.Errorf("error reading 'XRM': %w", err)
		}
		delete(object, "XRM")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyFeatures to handle AdditionalProperties
func (a FindMyFeatures) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BTR != nil {
		object["BTR"], err = json.Marshal(a.BTR)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'BTR': %w", err)
		}
	}

	if a.CLK != nil {
		object["CLK"], err = json.Marshal(a.CLK)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'CLK': %w", err)
		}
	}

	if a.CLT != nil {
		object["CLT"], err = json.Marshal(a.CLT)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'CLT': %w", err)
		}
	}

	if a.CWP != nil {
		object["CWP"], err = json.Marshal(a.CWP)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'CWP': %w", err)
		}
	}

	if a.KEY != nil {
		object["KEY"], err = json.Marshal(a.KEY)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'KEY': %w", err)
		}
	}

	if a.KPD != nil {
		object["KPD"], err = json.Marshal(a.KPD)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'KPD': %w", err)
		}
	}

	if a.LCK != nil {
		object["LCK"], err = json.Marshal(a.LCK)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'LCK': %w", err)
		}
	}

	if a.LKL != nil {
		object["LKL"], err = json.Marshal(a.LKL)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'LKL': %w", err)
		}
	}

	if a.LKM != nil {
		object["LKM"], err = json.Marshal(a.LKM)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'LKM': %w", err)
		}
	}

	if a.LLC != nil {
		object["LLC"], err = json.Marshal(a.LLC)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'LLC': %w", err)
		}
	}

	if a.LMG != nil {
		object["LMG"], err = json.Marshal(a.LMG)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'LMG': %w", err)
		}
	}

	if a.LOC != nil {
		object["LOC"], err = json.Marshal(a.LOC)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'LOC': %w", err)
		}
	}

	if a.LST != nil {
		object["LST"], err = json.Marshal(a.LST)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'LST': %w", err)
		}
	}

	if a.MCS != nil {
		object["MCS"], err = json.Marshal(a.MCS)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'MCS': %w", err)
		}
	}

	if a.MSG != nil {
		object["MSG"], err = json.Marshal(a.MSG)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'MSG': %w", err)
		}
	}

	if a.PIN != nil {
		object["PIN"], err = json.Marshal(a.PIN)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'PIN': %w", err)
		}
	}

	if a.PSS != nil {
		object["PSS"], err = json.Marshal(a.PSS)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'PSS': %w", err)
		}
	}

	if a.REM != nil {
		object["REM"], err = json.Marshal(a.REM)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'REM': %w", err)
		}
	}

	if a.SND != nil {
		object["SND"], err = json.Marshal(a.SND)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'SND': %w", err)
		}
	}

	if a.SPN != nil {
		object["SPN"], err = json.Marshal(a.SPN)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'SPN': %w", err)
		}
	}

	if a.SVP != nil {
		object["SVP"], err = json.Marshal(a.SVP)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'SVP': %w", err)
		}
	}

	if a.TEU != nil {
		object["TEU"], err = json.Marshal(a.TEU)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'TEU': %w", err)
		}
	}

	if a.WIP != nil {
		object["WIP"], err = json.Marshal(a.WIP)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'WIP': %w", err)
		}
	}

	if a.WMG != nil {
		object["WMG"], err = json.Marshal(a.WMG)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'WMG': %w", err)
		}
	}

	if a.XRM != nil {
		object["XRM"], err = json.Marshal(a.XRM)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'XRM': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyLocation. Returns the specified
// element and whether it was found
func (a FindMyLocation) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyLocation
func (a *FindMyLocation) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyLocation to handle AdditionalProperties
func (a *FindMyLocation) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["altitude"]; found {
		err = json.Unmarshal(raw, &a.Altitude)
		if err != nil {
			return fmt.Errorf("error reading 'altitude': %w", err)
		}
		delete(object, "altitude")
	}

	if raw, found := object["floorLevel"]; found {
		err = json.Unmarshal(raw, &a.FloorLevel)
		if err != nil {
			return fmt.Errorf("error reading 'floorLevel': %w", err)
		}
		delete(object, "floorLevel")
	}

	if raw, found := object["horizontalAccuracy"]; found {
		err = json.Unmarshal(raw, &a.HorizontalAccuracy)
		if err != nil {
			return fmt.Errorf("error reading 'horizontalAccuracy': %w", err)
		}
		delete(object, "horizontalAccuracy")
	}

	if raw, found := object["isInaccurate"]; found {
		err = json.Unmarshal(raw, &a.IsInaccurate)
		if err != nil {
			return fmt.Errorf("error reading 'isInaccurate': %w", err)
		}
		delete(object, "isInaccurate")
	}

	if raw, found := object["isOld"]; found {
		err = json.Unmarshal(raw, &a.IsOld)
		if err != nil {
			return fmt.Errorf("error reading 'isOld': %w", err)
		}
		delete(object, "isOld")
	}

	if raw, found := object["latitude"]; found {
		err = json.Unmarshal(raw, &a.Latitude)
		if err != nil {
			return fmt.Errorf("error reading 'latitude': %w", err)
		}
		delete(object, "latitude")
	}

	if raw, found := object["locationFinished"]; found {
		err = json.Unmarshal(raw, &a.LocationFinished)
		if err != nil {
			return fmt.Errorf("error reading 'locationFinished': %w", err)
		}
		delete(object, "locationFinished")
	}

	if raw, found := object["locationType"]; found {
		err = json.Unmarshal(raw, &a.LocationType)
		if err != nil {
			return fmt.Errorf("error reading 'locationType': %w", err)
		}
		delete(object, "locationType")
	}

	if raw, found := object["longitude"]; found {
		err = json.Unmarshal(raw, &a.Longitude)
		if err != nil {
			return fmt.Errorf("error reading 'longitude': %w", err)
		}
		delete(object, "longitude")
	}

	if raw, found := object["positionType"]; found {
		err = json.Unmarshal(raw, &a.PositionType)
		if err != nil {
			return fmt.Errorf("error reading 'positionType': %w", err)
		}
		delete(object, "positionType")
	}

	if raw, found := object["timeStamp"]; found {
		err = json.Unmarshal(raw, &a.TimeStamp)
		if err != nil {
			return fmt.Errorf("error reading 'timeStamp': %w", err)
		}
		delete(object, "timeStamp")
	}

	if raw, found := object["verticalAccuracy"]; found {
		err = json.Unmarshal(raw, &a.VerticalAccuracy)
		if err != nil {
			return fmt.Errorf("error reading 'verticalAccuracy': %w", err)
		}
		delete(object, "verticalAccuracy")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyLocation to handle AdditionalProperties
func (a FindMyLocation) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Altitude != nil {
		object["altitude"], err = json.Marshal(a.Altitude)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'altitude': %w", err)
		}
	}

	if a.FloorLevel != nil {
		object["floorLevel"], err = json.Marshal(a.FloorLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'floorLevel': %w", err)
		}
	}

	if a.HorizontalAccuracy != nil {
		object["horizontalAccuracy"], err = json.Marshal(a.HorizontalAccuracy)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'horizontalAccuracy': %w", err)
		}
	}

	if a.IsInaccurate != nil {
		object["isInaccurate"], err = json.Marshal(a.IsInaccurate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isInaccurate': %w", err)
		}
	}

	if a.IsOld != nil {
		object["isOld"], err = json.Marshal(a.IsOld)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isOld': %w", err)
		}
	}

	if a.Latitude != nil {
		object["latitude"], err = json.Marshal(a.Latitude)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'latitude': %w", err)
		}
	}

	if a.LocationFinished != nil {
		object["locationFinished"], err = json.Marshal(a.LocationFinished)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'locationFinished': %w", err)
		}
	}

	if a.LocationType != nil {
		object["locationType"], err = json.Marshal(a.LocationType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'locationType': %w", err)
		}
	}

	if a.Longitude != nil {
		object["longitude"], err = json.Marshal(a.Longitude)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'longitude': %w", err)
		}
	}

	if a.PositionType != nil {
		object["positionType"], err = json.Marshal(a.PositionType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'positionType': %w", err)
		}
	}

	if a.TimeStamp != nil {
		object["timeStamp"], err = json.Marshal(a.TimeStamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timeStamp': %w", err)
		}
	}

	if a.VerticalAccuracy != nil {
		object["verticalAccuracy"], err = json.Marshal(a.VerticalAccuracy)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'verticalAccuracy': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyLostState. Returns the specified
// element and whether it was found
func (a FindMyLostState) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyLostState
func (a *FindMyLostState) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyLostState to handle AdditionalProperties
func (a *FindMyLostState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["createTimestamp"]; found {
		err = json.Unmarshal(raw, &a.CreateTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'createTimestamp': %w", err)
		}
		delete(object, "createTimestamp")
	}

	if raw, found := object["emailUpdates"]; found {
		err = json.Unmarshal(raw, &a.EmailUpdates)
		if err != nil {
			return fmt.Errorf("error reading 'emailUpdates': %w", err)
		}
		delete(object, "emailUpdates")
	}

	if raw, found := object["ownerNbr"]; found {
		err = json.Unmarshal(raw, &a.OwnerNbr)
		if err != nil {
			return fmt.Errorf("error reading 'ownerNbr': %w", err)
		}
		delete(object, "ownerNbr")
	}

	if raw, found := object["sound"]; found {
		err = json.Unmarshal(raw, &a.Sound)
		if err != nil {
			return fmt.Errorf("error reading 'sound': %w", err)
		}
		delete(object, "sound")
	}

	if raw, found := object["statusCode"]; found {
		err = json.Unmarshal(raw, &a.StatusCode)
		if err != nil {
			return fmt.Errorf("error reading 'statusCode': %w", err)
		}
		delete(object, "statusCode")
	}

	if raw, found := object["stopLostMode"]; found {
		err = json.Unmarshal(raw, &a.StopLostMode)
		if err != nil {
			return fmt.Errorf("error reading 'stopLostMode': %w", err)
		}
		delete(object, "stopLostMode")
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &a.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
		delete(object, "text")
	}

	if raw, found := object["userText"]; found {
		err = json.Unmarshal(raw, &a.UserText)
		if err != nil {
			return fmt.Errorf("error reading 'userText': %w", err)
		}
		delete(object, "userText")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyLostState to handle AdditionalProperties
func (a FindMyLostState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CreateTimestamp != nil {
		object["createTimestamp"], err = json.Marshal(a.CreateTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'createTimestamp': %w", err)
		}
	}

	if a.EmailUpdates != nil {
		object["emailUpdates"], err = json.Marshal(a.EmailUpdates)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'emailUpdates': %w", err)
		}
	}

	if a.OwnerNbr != nil {
		object["ownerNbr"], err = json.Marshal(a.OwnerNbr)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ownerNbr': %w", err)
		}
	}

	if a.Sound != nil {
		object["sound"], err = json.Marshal(a.Sound)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sound': %w", err)
		}
	}

	if a.StatusCode != nil {
		object["statusCode"], err = json.Marshal(a.StatusCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'statusCode': %w", err)
		}
	}

	if a.StopLostMode != nil {
		object["stopLostMode"], err = json.Marshal(a.StopLostMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stopLostMode': %w", err)
		}
	}

	if a.Text != nil {
		object["text"], err = json.Marshal(a.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	if a.UserText != nil {
		object["userText"], err = json.Marshal(a.UserText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'userText': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyMember. Returns the specified
// element and whether it was found
func (a FindMyMember) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyMember
func (a *FindMyMember) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyMember to handle AdditionalProperties
func (a *FindMyMember) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["accountFormatter"]; found {
		err = json.Unmarshal(raw, &a.AccountFormatter)
		if err != nil {
			return fmt.Errorf("error reading 'accountFormatter': %w", err)
		}
		delete(object, "accountFormatter")
	}

	if raw, found := object["appleId"]; found {
		err = json.Unmarshal(raw, &a.AppleId)
		if err != nil {
			return fmt.Errorf("error reading 'appleId': %w", err)
		}
		delete(object, "appleId")
	}

	if raw, found := object["deviceFetchStatus"]; found {
		err = json.Unmarshal(raw, &a.DeviceFetchStatus)
		if err != nil {
			return fmt.Errorf("error reading 'deviceFetchStatus': %w", err)
		}
		delete(object, "deviceFetchStatus")
	}

	if raw, found := object["firstName"]; found {
		err = json.Unmarshal(raw, &a.FirstName)
		if err != nil {
			return fmt.Errorf("error reading 'firstName': %w", err)
		}
		delete(object, "firstName")
	}

	if raw, found := object["isHSA"]; found {
		err = json.Unmarshal(raw, &a.IsHSA)
		if err != nil {
			return fmt.Errorf("error reading 'isHSA': %w", err)
		}
		delete(object, "isHSA")
	}

	if raw, found := object["lastName"]; found {
		err = json.Unmarshal(raw, &a.LastName)
		if err != nil {
			return fmt.Errorf("error reading 'lastName': %w", err)
		}
		delete(object, "lastName")
	}

	if raw, found := object["useAuthWidget"]; found {
		err = json.Unmarshal(raw, &a.UseAuthWidget)
		if err != nil {
			return fmt.Errorf("error reading 'useAuthWidget': %w", err)
		}
		delete(object, "useAuthWidget")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyMember to handle AdditionalProperties
func (a FindMyMember) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccountFormatter != nil {
		object["accountFormatter"], err = json.Marshal(a.AccountFormatter)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'accountFormatter': %w", err)
		}
	}

	if a.AppleId != nil {
		object["appleId"], err = json.Marshal(a.AppleId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'appleId': %w", err)
		}
	}

	if a.DeviceFetchStatus != nil {
		object["deviceFetchStatus"], err = json.Marshal(a.DeviceFetchStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceFetchStatus': %w", err)
		}
	}

	if a.FirstName != nil {
		object["firstName"], err = json.Marshal(a.FirstName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'firstName': %w", err)
		}
	}

	if a.IsHSA != nil {
		object["isHSA"], err = json.Marshal(a.IsHSA)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isHSA': %w", err)
		}
	}

	if a.LastName != nil {
		object["lastName"], err = json.Marshal(a.LastName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lastName': %w", err)
		}
	}

	if a.UseAuthWidget != nil {
		object["useAuthWidget"], err = json.Marshal(a.UseAuthWidget)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'useAuthWidget': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyRefreshResponse. Returns the specified
// element and whether it was found
func (a FindMyRefreshResponse) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyRefreshResponse
func (a *FindMyRefreshResponse) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyRefreshResponse to handle AdditionalProperties
func (a *FindMyRefreshResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["serverContext"]; found {
		err = json.Unmarshal(raw, &a.ServerContext)
		if err != nil {
			return fmt.Errorf("error reading 'serverContext': %w", err)
		}
		delete(object, "serverContext")
	}

	if raw, found := object["userInfo"]; found {
		err = json.Unmarshal(raw, &a.UserInfo)
		if err != nil {
			return fmt.Errorf("error reading 'userInfo': %w", err)
		}
		delete(object, "userInfo")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyRefreshResponse to handle AdditionalProperties
func (a FindMyRefreshResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Content != nil {
		object["content"], err = json.Marshal(a.Content)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'content': %w", err)
		}
	}

	if a.ServerContext != nil {
		object["serverContext"], err = json.Marshal(a.ServerContext)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'serverContext': %w", err)
		}
	}

	if a.UserInfo != nil {
		object["userInfo"], err = json.Marshal(a.UserInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'userInfo': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyServerContext. Returns the specified
// element and whether it was found
func (a FindMyServerContext) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyServerContext
func (a *FindMyServerContext) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyServerContext to handle AdditionalProperties
func (a *FindMyServerContext) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["theftLoss"]; found {
		err = json.Unmarshal(raw, &a.TheftLoss)
		if err != nil {
			return fmt.Errorf("error reading 'theftLoss': %w", err)
		}
		delete(object, "theftLoss")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyServerContext to handle AdditionalProperties
func (a FindMyServerContext) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.TheftLoss != nil {
		object["theftLoss"], err = json.Marshal(a.TheftLoss)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'theftLoss': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FindMyUserInfo. Returns the specified
// element and whether it was found
func (a FindMyUserInfo) Get(fieldName string) (value FindMyUnknownJSON, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FindMyUserInfo
func (a *FindMyUserInfo) Set(fieldName string, value FindMyUnknownJSON) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FindMyUserInfo to handle AdditionalProperties
func (a *FindMyUserInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["accountFormatter"]; found {
		err = json.Unmarshal(raw, &a.AccountFormatter)
		if err != nil {
			return fmt.Errorf("error reading 'accountFormatter': %w", err)
		}
		delete(object, "accountFormatter")
	}

	if raw, found := object["firstName"]; found {
		err = json.Unmarshal(raw, &a.FirstName)
		if err != nil {
			return fmt.Errorf("error reading 'firstName': %w", err)
		}
		delete(object, "firstName")
	}

	if raw, found := object["hasMembers"]; found {
		err = json.Unmarshal(raw, &a.HasMembers)
		if err != nil {
			return fmt.Errorf("error reading 'hasMembers': %w", err)
		}
		delete(object, "hasMembers")
	}

	if raw, found := object["lastName"]; found {
		err = json.Unmarshal(raw, &a.LastName)
		if err != nil {
			return fmt.Errorf("error reading 'lastName': %w", err)
		}
		delete(object, "lastName")
	}

	if raw, found := object["membersInfo"]; found {
		err = json.Unmarshal(raw, &a.MembersInfo)
		if err != nil {
			return fmt.Errorf("error reading 'membersInfo': %w", err)
		}
		delete(object, "membersInfo")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]FindMyUnknownJSON)
		for fieldName, fieldBuf := range object {
			var fieldVal FindMyUnknownJSON
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FindMyUserInfo to handle AdditionalProperties
func (a FindMyUserInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccountFormatter != nil {
		object["accountFormatter"], err = json.Marshal(a.AccountFormatter)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'accountFormatter': %w", err)
		}
	}

	if a.FirstName != nil {
		object["firstName"], err = json.Marshal(a.FirstName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'firstName': %w", err)
		}
	}

	if a.HasMembers != nil {
		object["hasMembers"], err = json.Marshal(a.HasMembers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hasMembers': %w", err)
		}
	}

	if a.LastName != nil {
		object["lastName"], err = json.Marshal(a.LastName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lastName': %w", err)
		}
	}

	if a.MembersInfo != nil {
		object["membersInfo"], err = json.Marshal(a.MembersInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'membersInfo': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
