// Package photomaterialize provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package photomaterialize

import (
	"encoding/json"
	"time"
)

// Defines values for BinarySignature.
const (
	BigEndianSignature    BinarySignature = "MM"
	ExifSignature         BinarySignature = "Exif"
	LittleEndianSignature BinarySignature = "II"
)

// Valid indicates whether the value is a known member of the BinarySignature enum.
func (e BinarySignature) Valid() bool {
	switch e {
	case BigEndianSignature:
		return true
	case ExifSignature:
		return true
	case LittleEndianSignature:
		return true
	default:
		return false
	}
}

// Defines values for ExifTag.
const (
	DateTimeTag  ExifTag = 306
	DigitizedTag ExifTag = 36868
	ExifIFDTag   ExifTag = 34665
	OriginalTag  ExifTag = 36867
)

// Valid indicates whether the value is a known member of the ExifTag enum.
func (e ExifTag) Valid() bool {
	switch e {
	case DateTimeTag:
		return true
	case DigitizedTag:
		return true
	case ExifIFDTag:
		return true
	case OriginalTag:
		return true
	default:
		return false
	}
}

// Defines values for JPEGMarker.
const (
	MarkerAPP1   JPEGMarker = 225
	MarkerEOI    JPEGMarker = 217
	MarkerPrefix JPEGMarker = 255
	MarkerSOI    JPEGMarker = 216
	MarkerSOS    JPEGMarker = 218
)

// Valid indicates whether the value is a known member of the JPEGMarker enum.
func (e JPEGMarker) Valid() bool {
	switch e {
	case MarkerAPP1:
		return true
	case MarkerEOI:
		return true
	case MarkerPrefix:
		return true
	case MarkerSOI:
		return true
	case MarkerSOS:
		return true
	default:
		return false
	}
}

// Defines values for LocationKey.
const (
	AltitudeKey  LocationKey = "alt"
	LatitudeKey  LocationKey = "lat"
	LongitudeKey LocationKey = "lon"
	SpeedKey     LocationKey = "speed"
	TimestampKey LocationKey = "timestamp"
)

// Valid indicates whether the value is a known member of the LocationKey enum.
func (e LocationKey) Valid() bool {
	switch e {
	case AltitudeKey:
		return true
	case LatitudeKey:
		return true
	case LongitudeKey:
		return true
	case SpeedKey:
		return true
	case TimestampKey:
		return true
	default:
		return false
	}
}

// Defines values for TiffFieldType.
const (
	ASCIIFieldType TiffFieldType = 2
	LongFieldType  TiffFieldType = 4
)

// Valid indicates whether the value is a known member of the TiffFieldType enum.
func (e TiffFieldType) Valid() bool {
	switch e {
	case ASCIIFieldType:
		return true
	case LongFieldType:
		return true
	default:
		return false
	}
}

// Defines values for TiffVersion.
const (
	ExifTiffVersion TiffVersion = 42
)

// Valid indicates whether the value is a known member of the TiffVersion enum.
func (e TiffVersion) Valid() bool {
	switch e {
	case ExifTiffVersion:
		return true
	default:
		return false
	}
}

// Defines values for Toolkit.
const (
	SourceToolkit Toolkit = "pyicloud photos-cloudkit"
)

// Valid indicates whether the value is a known member of the Toolkit enum.
func (e Toolkit) Valid() bool {
	switch e {
	case SourceToolkit:
		return true
	default:
		return false
	}
}

// Adjustment Decoded raw DEFLATE adjustmentSimpleDataEnc JSON. Unknown adjustment operations are accepted and ignored.
type Adjustment struct {
	Metadata *AdjustmentMetadata `json:"metadata,omitempty"`
}

// AdjustmentMetadata defines model for AdjustmentMetadata.
type AdjustmentMetadata struct {
	Orientation *int `json:"orientation,omitempty"`
}

// AssetFields Known CloudKit asset field names used for local metadata extraction.
type AssetFields struct {
	// AdjustmentSimpleDataEnc Base64 raw DEFLATE JSON adjustment; crdt and binary plist variants are deliberately ignored by Source.
	AdjustmentSimpleDataEnc *Field `json:"adjustmentSimpleDataEnc,omitempty"`
	AssetDate               *Field `json:"assetDate,omitempty"`
	AssetSubtypeV2          *Field `json:"assetSubtypeV2,omitempty"`
	CaptionEnc              *Field `json:"captionEnc,omitempty"`
	ExtendedDescEnc         *Field `json:"extendedDescEnc,omitempty"`
	IsDeleted               *Field `json:"isDeleted,omitempty"`
	IsFavorite              *Field `json:"isFavorite,omitempty"`
	IsHidden                *Field `json:"isHidden,omitempty"`

	// KeywordsEnc Base64 binary or XML plist array, with each item converted to a keyword string.
	KeywordsEnc *Field `json:"keywordsEnc,omitempty"`

	// LocationEnc Base64 binary or XML plist dictionary of optional location fields.
	LocationEnc    *Field `json:"locationEnc,omitempty"`
	TimeZoneOffset *Field `json:"timeZoneOffset,omitempty"`
}

// AssetRecord CloudKit asset metadata accepting both raw and normalized field values.
type AssetRecord struct {
	// Fields Known CloudKit asset field names used for local metadata extraction.
	Fields *AssetFields `json:"fields,omitempty"`
}

// BinarySignature EXIF ASCII signature is followed by two NUL bytes in the APP1 segment.
type BinarySignature string

// ExifCase defines model for ExifCase.
type ExifCase struct {
	InputHex  string `json:"inputHex"`
	Name      string `json:"name"`
	OutputHex string `json:"outputHex"`
}

// ExifTag defines model for ExifTag.
type ExifTag int

// Field defines model for Field.
type Field struct {
	// Value Field type selects the value; local adaptation tolerates absent or invalid metadata.
	Value *json.RawMessage `json:"value,omitempty"`
}

// JPEGMarker defines model for JPEGMarker.
type JPEGMarker int

// KeywordValues Plist values are open; Source converts each scalar into a string for the XMP projection.
type KeywordValues = []interface{}

// Location Decoded locationEnc binary or XML plist dictionary; timestamp is a plist date.
type Location struct {
	Alt       *float64   `json:"alt,omitempty" plist:"alt"`
	Lat       *float64   `json:"lat,omitempty" plist:"lat"`
	Lon       *float64   `json:"lon,omitempty" plist:"lon"`
	Speed     *float64   `json:"speed,omitempty" plist:"speed"`
	Timestamp *time.Time `json:"timestamp,omitempty" plist:"timestamp"`
}

// LocationKey defines model for LocationKey.
type LocationKey string

// MaterializationOracle defines model for MaterializationOracle.
type MaterializationOracle struct {
	ExifCases  *[]ExifCase `json:"exifCases,omitempty"`
	ExifHex    string      `json:"exifHex"`
	Provenance string      `json:"provenance"`
	Xmp        string      `json:"xmp"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	CreateDate        *time.Time `json:"createDate,omitempty"`
	Description       *string    `json:"description,omitempty"`
	DigitalSourceType *string    `json:"digitalSourceType,omitempty"`
	GpsAltitude       *float64   `json:"gpsAltitude,omitempty"`
	GpsLatitude       *float64   `json:"gpsLatitude,omitempty"`
	GpsLongitude      *float64   `json:"gpsLongitude,omitempty"`
	GpsSpeed          *float64   `json:"gpsSpeed,omitempty"`
	GpsTimestamp      *time.Time `json:"gpsTimestamp,omitempty"`
	Keywords          *[]string  `json:"keywords,omitempty"`
	Make              *string    `json:"make,omitempty"`
	Orientation       *int       `json:"orientation,omitempty"`
	Rating            *int       `json:"rating,omitempty"`
	Title             *string    `json:"title,omitempty"`
	Toolkit           string     `json:"toolkit"`
}

// TiffFieldType defines model for TiffFieldType.
type TiffFieldType int

// TiffVersion defines model for TiffVersion.
type TiffVersion int

// Toolkit defines model for Toolkit.
type Toolkit string
