// Package findmyapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package findmyapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	externalRef0 "github.com/portpowered/go-icloud/pkg/dependencymodels/findmy"
)

// FindMyCommandBytes Raw command reply bytes regardless of the advertised media type. The reference accepts malformed JSON and non-JSON acknowledgements; provider error objects are still classified before success.
type FindMyCommandBytes = externalRef0.FindMyCommandBytes

// FindMyEraseRequest defines model for FindMyEraseRequest.
type FindMyEraseRequest = externalRef0.FindMyEraseRequest

// FindMyEraseTokenRequest defines model for FindMyEraseTokenRequest.
type FindMyEraseTokenRequest = externalRef0.FindMyEraseTokenRequest

// FindMyEraseTokenResponse Missing tokens are representable and must stop before a remote erase command.
type FindMyEraseTokenResponse = externalRef0.FindMyEraseTokenResponse

// FindMyError defines model for FindMyError.
type FindMyError = externalRef0.FindMyError

// FindMyInitializeRequest Example: {"clientContext":{"apiVersion":"3.0","appName":"iCloud Find (Web)","appVersion":"2.0","deviceListVersion":1,"fmly":false,"inactiveTime":0,"timezone":"US/Pacific"}}
type FindMyInitializeRequest = externalRef0.FindMyInitializeRequest

// FindMyLostRequest defines model for FindMyLostRequest.
type FindMyLostRequest = externalRef0.FindMyLostRequest

// FindMyMessageRequest defines model for FindMyMessageRequest.
type FindMyMessageRequest = externalRef0.FindMyMessageRequest

// FindMyRefreshRequest Example: {"clientContext":{"apiVersion":"3.0","appName":"iCloud Find (Web)","appVersion":"2.0","deviceListVersion":1,"fmly":false,"inactiveTime":0,"timezone":"US/Pacific"},"serverContext":{"future":true}}
type FindMyRefreshRequest = externalRef0.FindMyRefreshRequest

// FindMyRefreshResponse Partial refresh; absent or empty content does not imply removal of cached devices.
//
// Example: {"content":[],"serverContext":{"future":true}}
type FindMyRefreshResponse = externalRef0.FindMyRefreshResponse

// FindMySoundRequest defines model for FindMySoundRequest.
type FindMySoundRequest = externalRef0.FindMySoundRequest

// FindMyAccept defines model for FindMyAccept.
type FindMyAccept = string

// FindMyAcceptEncoding defines model for FindMyAcceptEncoding.
type FindMyAcceptEncoding = string

// FindMyBuildNumber defines model for FindMyBuildNumber.
type FindMyBuildNumber = string

// FindMyClientID defines model for FindMyClientID.
type FindMyClientID = string

// FindMyConnection defines model for FindMyConnection.
type FindMyConnection = string

// FindMyCookie defines model for FindMyCookie.
type FindMyCookie = string

// FindMyDSID defines model for FindMyDSID.
type FindMyDSID = string

// FindMyMasteringNumber defines model for FindMyMasteringNumber.
type FindMyMasteringNumber = string

// FindMyOrigin defines model for FindMyOrigin.
type FindMyOrigin = string

// FindMyReferer defines model for FindMyReferer.
type FindMyReferer = string

// FindMyUserAgent defines model for FindMyUserAgent.
type FindMyUserAgent = string

// FindMyFailure defines model for FindMyFailure.
type FindMyFailure = FindMyError

// FindMyInitializeParams defines parameters for FindMyInitialize.
type FindMyInitializeParams struct {
	ClientId              FindMyClientID         `form:"clientId" json:"clientId"`
	Dsid                  FindMyDSID             `form:"dsid" json:"dsid"`
	ClientBuildNumber     *FindMyBuildNumber     `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`
	ClientMasteringNumber *FindMyMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *FindMyAccept          `json:"Accept,omitempty"`
	Cookie                *FindMyCookie          `json:"Cookie,omitempty"`
	Origin                *FindMyOrigin          `json:"Origin,omitempty"`
	Referer               *FindMyReferer         `json:"Referer,omitempty"`
	UserAgent             *FindMyUserAgent       `json:"User-Agent,omitempty"`
	AcceptEncoding        *FindMyAcceptEncoding  `json:"Accept-Encoding,omitempty"`
	Connection            *FindMyConnection      `json:"Connection,omitempty"`
}

// FindMyLostDeviceParams defines parameters for FindMyLostDevice.
type FindMyLostDeviceParams struct {
	ClientId              FindMyClientID         `form:"clientId" json:"clientId"`
	Dsid                  FindMyDSID             `form:"dsid" json:"dsid"`
	ClientBuildNumber     *FindMyBuildNumber     `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`
	ClientMasteringNumber *FindMyMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *FindMyAccept          `json:"Accept,omitempty"`
	Cookie                *FindMyCookie          `json:"Cookie,omitempty"`
	Origin                *FindMyOrigin          `json:"Origin,omitempty"`
	Referer               *FindMyReferer         `json:"Referer,omitempty"`
	UserAgent             *FindMyUserAgent       `json:"User-Agent,omitempty"`
	AcceptEncoding        *FindMyAcceptEncoding  `json:"Accept-Encoding,omitempty"`
	Connection            *FindMyConnection      `json:"Connection,omitempty"`
}

// FindMyPlaySoundParams defines parameters for FindMyPlaySound.
type FindMyPlaySoundParams struct {
	ClientId              FindMyClientID         `form:"clientId" json:"clientId"`
	Dsid                  FindMyDSID             `form:"dsid" json:"dsid"`
	ClientBuildNumber     *FindMyBuildNumber     `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`
	ClientMasteringNumber *FindMyMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *FindMyAccept          `json:"Accept,omitempty"`
	Cookie                *FindMyCookie          `json:"Cookie,omitempty"`
	Origin                *FindMyOrigin          `json:"Origin,omitempty"`
	Referer               *FindMyReferer         `json:"Referer,omitempty"`
	UserAgent             *FindMyUserAgent       `json:"User-Agent,omitempty"`
	AcceptEncoding        *FindMyAcceptEncoding  `json:"Accept-Encoding,omitempty"`
	Connection            *FindMyConnection      `json:"Connection,omitempty"`
}

// FindMyRefreshDevicesParams defines parameters for FindMyRefreshDevices.
type FindMyRefreshDevicesParams struct {
	ClientId              FindMyClientID         `form:"clientId" json:"clientId"`
	Dsid                  FindMyDSID             `form:"dsid" json:"dsid"`
	ClientBuildNumber     *FindMyBuildNumber     `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`
	ClientMasteringNumber *FindMyMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *FindMyAccept          `json:"Accept,omitempty"`
	Cookie                *FindMyCookie          `json:"Cookie,omitempty"`
	Origin                *FindMyOrigin          `json:"Origin,omitempty"`
	Referer               *FindMyReferer         `json:"Referer,omitempty"`
	UserAgent             *FindMyUserAgent       `json:"User-Agent,omitempty"`
	AcceptEncoding        *FindMyAcceptEncoding  `json:"Accept-Encoding,omitempty"`
	Connection            *FindMyConnection      `json:"Connection,omitempty"`
}

// FindMyEraseDeviceParams defines parameters for FindMyEraseDevice.
type FindMyEraseDeviceParams struct {
	ClientId              FindMyClientID         `form:"clientId" json:"clientId"`
	Dsid                  FindMyDSID             `form:"dsid" json:"dsid"`
	ClientBuildNumber     *FindMyBuildNumber     `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`
	ClientMasteringNumber *FindMyMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *FindMyAccept          `json:"Accept,omitempty"`
	Cookie                *FindMyCookie          `json:"Cookie,omitempty"`
	Origin                *FindMyOrigin          `json:"Origin,omitempty"`
	Referer               *FindMyReferer         `json:"Referer,omitempty"`
	UserAgent             *FindMyUserAgent       `json:"User-Agent,omitempty"`
	AcceptEncoding        *FindMyAcceptEncoding  `json:"Accept-Encoding,omitempty"`
	Connection            *FindMyConnection      `json:"Connection,omitempty"`
}

// FindMySendMessageParams defines parameters for FindMySendMessage.
type FindMySendMessageParams struct {
	ClientId              FindMyClientID         `form:"clientId" json:"clientId"`
	Dsid                  FindMyDSID             `form:"dsid" json:"dsid"`
	ClientBuildNumber     *FindMyBuildNumber     `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`
	ClientMasteringNumber *FindMyMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *FindMyAccept          `json:"Accept,omitempty"`
	Cookie                *FindMyCookie          `json:"Cookie,omitempty"`
	Origin                *FindMyOrigin          `json:"Origin,omitempty"`
	Referer               *FindMyReferer         `json:"Referer,omitempty"`
	UserAgent             *FindMyUserAgent       `json:"User-Agent,omitempty"`
	AcceptEncoding        *FindMyAcceptEncoding  `json:"Accept-Encoding,omitempty"`
	Connection            *FindMyConnection      `json:"Connection,omitempty"`
}

// FindMyObtainEraseTokenParams defines parameters for FindMyObtainEraseToken.
type FindMyObtainEraseTokenParams struct {
	Accept         *FindMyAccept         `json:"Accept,omitempty"`
	Cookie         *FindMyCookie         `json:"Cookie,omitempty"`
	Origin         *FindMyOrigin         `json:"Origin,omitempty"`
	Referer        *FindMyReferer        `json:"Referer,omitempty"`
	UserAgent      *FindMyUserAgent      `json:"User-Agent,omitempty"`
	AcceptEncoding *FindMyAcceptEncoding `json:"Accept-Encoding,omitempty"`
	Connection     *FindMyConnection     `json:"Connection,omitempty"`
}

// FindMyInitializeJSONRequestBody defines body for FindMyInitialize for application/json ContentType.
type FindMyInitializeJSONRequestBody = FindMyInitializeRequest

// FindMyLostDeviceJSONRequestBody defines body for FindMyLostDevice for application/json ContentType.
type FindMyLostDeviceJSONRequestBody = FindMyLostRequest

// FindMyPlaySoundJSONRequestBody defines body for FindMyPlaySound for application/json ContentType.
type FindMyPlaySoundJSONRequestBody = FindMySoundRequest

// FindMyRefreshDevicesJSONRequestBody defines body for FindMyRefreshDevices for application/json ContentType.
type FindMyRefreshDevicesJSONRequestBody = FindMyRefreshRequest

// FindMyEraseDeviceJSONRequestBody defines body for FindMyEraseDevice for application/json ContentType.
type FindMyEraseDeviceJSONRequestBody = FindMyEraseRequest

// FindMySendMessageJSONRequestBody defines body for FindMySendMessage for application/json ContentType.
type FindMySendMessageJSONRequestBody = FindMyMessageRequest

// FindMyObtainEraseTokenJSONRequestBody defines body for FindMyObtainEraseToken for application/json ContentType.
type FindMyObtainEraseTokenJSONRequestBody = FindMyEraseTokenRequest

// NewFindMyInitializeRequest calls the generic FindMyInitialize builder with application/json body
func NewFindMyInitializeRequest(server string, params *FindMyInitializeParams, body FindMyInitializeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindMyInitializeRequestWithBody(server, params, "application/json", bodyReader)
}

// NewFindMyInitializeRequestWithBody constructs an http.Request for the FindMyInitialize method, with any body, and a specified content type
func NewFindMyInitializeRequestWithBody(server string, params *FindMyInitializeParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/fmipservice/client/web/initClient")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.Cookie != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam1)
		}

		if params.Origin != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam2)
		}

		if params.Referer != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam3)
		}

		if params.UserAgent != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam4)
		}

		if params.AcceptEncoding != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam5)
		}

		if params.Connection != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam6)
		}

	}

	return req, nil
}

// NewFindMyLostDeviceRequest calls the generic FindMyLostDevice builder with application/json body
func NewFindMyLostDeviceRequest(server string, params *FindMyLostDeviceParams, body FindMyLostDeviceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindMyLostDeviceRequestWithBody(server, params, "application/json", bodyReader)
}

// NewFindMyLostDeviceRequestWithBody constructs an http.Request for the FindMyLostDevice method, with any body, and a specified content type
func NewFindMyLostDeviceRequestWithBody(server string, params *FindMyLostDeviceParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/fmipservice/client/web/lostDevice")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.Cookie != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam1)
		}

		if params.Origin != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam2)
		}

		if params.Referer != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam3)
		}

		if params.UserAgent != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam4)
		}

		if params.AcceptEncoding != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam5)
		}

		if params.Connection != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam6)
		}

	}

	return req, nil
}

// NewFindMyPlaySoundRequest calls the generic FindMyPlaySound builder with application/json body
func NewFindMyPlaySoundRequest(server string, params *FindMyPlaySoundParams, body FindMyPlaySoundJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindMyPlaySoundRequestWithBody(server, params, "application/json", bodyReader)
}

// NewFindMyPlaySoundRequestWithBody constructs an http.Request for the FindMyPlaySound method, with any body, and a specified content type
func NewFindMyPlaySoundRequestWithBody(server string, params *FindMyPlaySoundParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/fmipservice/client/web/playSound")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.Cookie != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam1)
		}

		if params.Origin != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam2)
		}

		if params.Referer != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam3)
		}

		if params.UserAgent != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam4)
		}

		if params.AcceptEncoding != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam5)
		}

		if params.Connection != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam6)
		}

	}

	return req, nil
}

// NewFindMyRefreshDevicesRequest calls the generic FindMyRefreshDevices builder with application/json body
func NewFindMyRefreshDevicesRequest(server string, params *FindMyRefreshDevicesParams, body FindMyRefreshDevicesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindMyRefreshDevicesRequestWithBody(server, params, "application/json", bodyReader)
}

// NewFindMyRefreshDevicesRequestWithBody constructs an http.Request for the FindMyRefreshDevices method, with any body, and a specified content type
func NewFindMyRefreshDevicesRequestWithBody(server string, params *FindMyRefreshDevicesParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/fmipservice/client/web/refreshClient")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.Cookie != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam1)
		}

		if params.Origin != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam2)
		}

		if params.Referer != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam3)
		}

		if params.UserAgent != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam4)
		}

		if params.AcceptEncoding != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam5)
		}

		if params.Connection != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam6)
		}

	}

	return req, nil
}

// NewFindMyEraseDeviceRequest calls the generic FindMyEraseDevice builder with application/json body
func NewFindMyEraseDeviceRequest(server string, params *FindMyEraseDeviceParams, body FindMyEraseDeviceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindMyEraseDeviceRequestWithBody(server, params, "application/json", bodyReader)
}

// NewFindMyEraseDeviceRequestWithBody constructs an http.Request for the FindMyEraseDevice method, with any body, and a specified content type
func NewFindMyEraseDeviceRequestWithBody(server string, params *FindMyEraseDeviceParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/fmipservice/client/web/remoteWipeWithUserAuth")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.Cookie != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam1)
		}

		if params.Origin != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam2)
		}

		if params.Referer != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam3)
		}

		if params.UserAgent != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam4)
		}

		if params.AcceptEncoding != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam5)
		}

		if params.Connection != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam6)
		}

	}

	return req, nil
}

// NewFindMySendMessageRequest calls the generic FindMySendMessage builder with application/json body
func NewFindMySendMessageRequest(server string, params *FindMySendMessageParams, body FindMySendMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindMySendMessageRequestWithBody(server, params, "application/json", bodyReader)
}

// NewFindMySendMessageRequestWithBody constructs an http.Request for the FindMySendMessage method, with any body, and a specified content type
func NewFindMySendMessageRequestWithBody(server string, params *FindMySendMessageParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/fmipservice/client/web/sendMessage")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.Cookie != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam1)
		}

		if params.Origin != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam2)
		}

		if params.Referer != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam3)
		}

		if params.UserAgent != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam4)
		}

		if params.AcceptEncoding != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam5)
		}

		if params.Connection != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam6)
		}

	}

	return req, nil
}

// NewFindMyObtainEraseTokenRequest calls the generic FindMyObtainEraseToken builder with application/json body
func NewFindMyObtainEraseTokenRequest(server string, params *FindMyObtainEraseTokenParams, body FindMyObtainEraseTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindMyObtainEraseTokenRequestWithBody(server, params, "application/json", bodyReader)
}

// NewFindMyObtainEraseTokenRequestWithBody constructs an http.Request for the FindMyObtainEraseToken method, with any body, and a specified content type
func NewFindMyObtainEraseTokenRequestWithBody(server string, params *FindMyObtainEraseTokenParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/setup/ws/1/fmipWebAuthenticate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.Cookie != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam1)
		}

		if params.Origin != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam2)
		}

		if params.Referer != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uri"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam3)
		}

		if params.UserAgent != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam4)
		}

		if params.AcceptEncoding != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam5)
		}

		if params.Connection != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam6)
		}

	}

	return req, nil
}

type FindMyInitializeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *FindMyRefreshResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *FindMyFailure
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r FindMyInitializeResponse) GetJSON200() *FindMyRefreshResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r FindMyInitializeResponse) GetJSONDefault() *FindMyFailure {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r FindMyInitializeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FindMyInitializeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindMyInitializeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FindMyInitializeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FindMyLostDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r FindMyLostDeviceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FindMyLostDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindMyLostDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FindMyLostDeviceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FindMyPlaySoundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r FindMyPlaySoundResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FindMyPlaySoundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindMyPlaySoundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FindMyPlaySoundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FindMyRefreshDevicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *FindMyRefreshResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *FindMyFailure
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r FindMyRefreshDevicesResponse) GetJSON200() *FindMyRefreshResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r FindMyRefreshDevicesResponse) GetJSONDefault() *FindMyFailure {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r FindMyRefreshDevicesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FindMyRefreshDevicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindMyRefreshDevicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FindMyRefreshDevicesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FindMyEraseDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r FindMyEraseDeviceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FindMyEraseDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindMyEraseDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FindMyEraseDeviceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FindMySendMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r FindMySendMessageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FindMySendMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindMySendMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FindMySendMessageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FindMyObtainEraseTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *FindMyEraseTokenResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *FindMyFailure
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r FindMyObtainEraseTokenResponse) GetJSON200() *FindMyEraseTokenResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r FindMyObtainEraseTokenResponse) GetJSONDefault() *FindMyFailure {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r FindMyObtainEraseTokenResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FindMyObtainEraseTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindMyObtainEraseTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FindMyObtainEraseTokenResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ParseFindMyInitializeResponse parses an HTTP response for the FindMyInitialize operation
func ParseFindMyInitializeResponse(rsp *http.Response) (*FindMyInitializeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindMyInitializeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FindMyRefreshResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest FindMyFailure
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindMyLostDeviceResponse parses an HTTP response for the FindMyLostDevice operation
func ParseFindMyLostDeviceResponse(rsp *http.Response) (*FindMyLostDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindMyLostDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFindMyPlaySoundResponse parses an HTTP response for the FindMyPlaySound operation
func ParseFindMyPlaySoundResponse(rsp *http.Response) (*FindMyPlaySoundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindMyPlaySoundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFindMyRefreshDevicesResponse parses an HTTP response for the FindMyRefreshDevices operation
func ParseFindMyRefreshDevicesResponse(rsp *http.Response) (*FindMyRefreshDevicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindMyRefreshDevicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FindMyRefreshResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest FindMyFailure
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindMyEraseDeviceResponse parses an HTTP response for the FindMyEraseDevice operation
func ParseFindMyEraseDeviceResponse(rsp *http.Response) (*FindMyEraseDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindMyEraseDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFindMySendMessageResponse parses an HTTP response for the FindMySendMessage operation
func ParseFindMySendMessageResponse(rsp *http.Response) (*FindMySendMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindMySendMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFindMyObtainEraseTokenResponse parses an HTTP response for the FindMyObtainEraseToken operation
func ParseFindMyObtainEraseTokenResponse(rsp *http.Response) (*FindMyObtainEraseTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindMyObtainEraseTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FindMyEraseTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest FindMyFailure
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
