// Package commandmodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package commandmodels

// AuthenticationStatusSummary defines model for AuthenticationStatusSummary.
type AuthenticationStatusSummary struct {
	Authenticated     bool   `json:"authenticated"`
	RequiresTwoFactor bool   `json:"requiresTwoFactor"`
	RequiresTwoStep   bool   `json:"requiresTwoStep"`
	SessionFile       string `json:"sessionFile"`
	Trusted           bool   `json:"trusted"`
}

// AuthenticationSummary defines model for AuthenticationSummary.
type AuthenticationSummary struct {
	CodeRequested bool `json:"codeRequested"`

	// DeliveryMethod Display of the SDK's schema-owned TwoFactorDeliveryMethod value; future SDK values remain visible.
	DeliveryMethod string `json:"deliveryMethod"`

	// DeliveryNotice SDK-provided public explanation of the selected authentication delivery route.
	DeliveryNotice    *string       `json:"deliveryNotice,omitempty"`
	PhoneNumbers      []PhoneChoice `json:"phoneNumbers"`
	RequiresTwoFactor bool          `json:"requiresTwoFactor"`
	RequiresTwoStep   bool          `json:"requiresTwoStep"`
	SecurityKeyNames  []string      `json:"securityKeyNames"`
	SessionFile       string        `json:"sessionFile"`
	Success           bool          `json:"success"`
	Trusted           bool          `json:"trusted"`
}

// ExportSummary defines model for ExportSummary.
type ExportSummary struct {
	SessionFile string `json:"sessionFile"`
}

// LogoutSummary defines model for LogoutSummary.
type LogoutSummary struct {
	LocalCleared    bool `json:"localCleared"`
	RemoteConfirmed bool `json:"remoteConfirmed"`
}

// PhoneChoice Visible selection values derived from the SDK challenge; integer and string provider identifiers remain preserved in private state.
type PhoneChoice struct {
	ID     string `json:"id"`
	Number string `json:"number"`
}

// ResumeSummary defines model for ResumeSummary.
type ResumeSummary struct {
	RequiresTwoFactor bool   `json:"requiresTwoFactor"`
	RequiresTwoStep   bool   `json:"requiresTwoStep"`
	SessionFile       string `json:"sessionFile"`
	Trusted           bool   `json:"trusted"`
}

// TrustedDevicesSummary defines model for TrustedDevicesSummary.
type TrustedDevicesSummary struct {
	DeviceIDs   []string `json:"deviceIDs"`
	SessionFile string   `json:"sessionFile"`
}
