// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: versioned_document.proto

// ==========================================================================
// versioned_document.proto
// Outer versioned wrapper for topotext CRDT documents.
// Extracted from iCloud.com Reminders main.js at line 99472.
// ==========================================================================

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Just in case.
	SerializationVersion *uint32    `protobuf:"varint,1,opt,name=serializationVersion" json:"serializationVersion,omitempty"`
	Version              []*Version `protobuf:"bytes,2,rep,name=version" json:"version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_versioned_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_versioned_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_versioned_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetSerializationVersion() uint32 {
	if x != nil && x.SerializationVersion != nil {
		return *x.SerializationVersion
	}
	return 0
}

func (x *Document) GetVersion() []*Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type Version struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SerializationVersion    *uint32                `protobuf:"varint,1,opt,name=serializationVersion" json:"serializationVersion,omitempty"`
	MinimumSupportedVersion *uint32                `protobuf:"varint,2,opt,name=minimumSupportedVersion" json:"minimumSupportedVersion,omitempty"`
	// Interpreted as a topotext.String.
	// Archived as bytes to ensure bit-perfect backward compatibility.
	Data          []byte `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_versioned_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_versioned_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_versioned_document_proto_rawDescGZIP(), []int{1}
}

func (x *Version) GetSerializationVersion() uint32 {
	if x != nil && x.SerializationVersion != nil {
		return *x.SerializationVersion
	}
	return 0
}

func (x *Version) GetMinimumSupportedVersion() uint32 {
	if x != nil && x.MinimumSupportedVersion != nil {
		return *x.MinimumSupportedVersion
	}
	return 0
}

func (x *Version) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_versioned_document_proto protoreflect.FileDescriptor

const file_versioned_document_proto_rawDesc = "" +
	"\n" +
	"\x18versioned_document.proto\x12\x12versioned_document\"u\n" +
	"\bDocument\x122\n" +
	"\x14serializationVersion\x18\x01 \x01(\rR\x14serializationVersion\x125\n" +
	"\aversion\x18\x02 \x03(\v2\x1b.versioned_document.VersionR\aversion\"\x8b\x01\n" +
	"\aVersion\x122\n" +
	"\x14serializationVersion\x18\x01 \x01(\rR\x14serializationVersion\x128\n" +
	"\x17minimumSupportedVersion\x18\x02 \x01(\rR\x17minimumSupportedVersion\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data"

var (
	file_versioned_document_proto_rawDescOnce sync.Once
	file_versioned_document_proto_rawDescData []byte
)

func file_versioned_document_proto_rawDescGZIP() []byte {
	file_versioned_document_proto_rawDescOnce.Do(func() {
		file_versioned_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_versioned_document_proto_rawDesc), len(file_versioned_document_proto_rawDesc)))
	})
	return file_versioned_document_proto_rawDescData
}

var file_versioned_document_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_versioned_document_proto_goTypes = []any{
	(*Document)(nil), // 0: versioned_document.Document
	(*Version)(nil),  // 1: versioned_document.Version
}
var file_versioned_document_proto_depIdxs = []int32{
	1, // 0: versioned_document.Document.version:type_name -> versioned_document.Version
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_versioned_document_proto_init() }
func file_versioned_document_proto_init() {
	if File_versioned_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_versioned_document_proto_rawDesc), len(file_versioned_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_versioned_document_proto_goTypes,
		DependencyIndexes: file_versioned_document_proto_depIdxs,
		MessageInfos:      file_versioned_document_proto_msgTypes,
	}.Build()
	File_versioned_document_proto = out.File
	file_versioned_document_proto_goTypes = nil
	file_versioned_document_proto_depIdxs = nil
}
