// Package securitykey provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package securitykey

// Defines values for COSEKeyAlgorithm.
const (
	Minus25 COSEKeyAlgorithm = -25
)

// Valid indicates whether the value is a known member of the COSEKeyAlgorithm enum.
func (e COSEKeyAlgorithm) Valid() bool {
	switch e {
	case Minus25:
		return true
	default:
		return false
	}
}

// Defines values for COSEKeyCurve.
const (
	N1 COSEKeyCurve = 1
)

// Valid indicates whether the value is a known member of the COSEKeyCurve enum.
func (e COSEKeyCurve) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for COSEKeyKeyType.
const (
	COSEKeyKeyTypeN2 COSEKeyKeyType = 2
)

// Valid indicates whether the value is a known member of the COSEKeyKeyType enum.
func (e COSEKeyKeyType) Valid() bool {
	switch e {
	case COSEKeyKeyTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for CTAPCommand.
const (
	ClientPIN        CTAPCommand = 6
	GetAssertion     CTAPCommand = 2
	GetInfo          CTAPCommand = 4
	GetNextAssertion CTAPCommand = 8
)

// Valid indicates whether the value is a known member of the CTAPCommand enum.
func (e CTAPCommand) Valid() bool {
	switch e {
	case ClientPIN:
		return true
	case GetAssertion:
		return true
	case GetInfo:
		return true
	case GetNextAssertion:
		return true
	default:
		return false
	}
}

// Defines values for ClientDataTemplate.
const (
	CollectedClientDataTemplate ClientDataTemplate = "{\"type\":%s,\"challenge\":%s,\"origin\":%s,\"crossOrigin\":false}"
)

// Valid indicates whether the value is a known member of the ClientDataTemplate enum.
func (e ClientDataTemplate) Valid() bool {
	switch e {
	case CollectedClientDataTemplate:
		return true
	default:
		return false
	}
}

// Defines values for ClientDataType.
const (
	WebauthnGet ClientDataType = "webauthn.get"
)

// Valid indicates whether the value is a known member of the ClientDataType enum.
func (e ClientDataType) Valid() bool {
	switch e {
	case WebauthnGet:
		return true
	default:
		return false
	}
}

// Defines values for CredentialType.
const (
	PublicKey CredentialType = "public-key"
)

// Valid indicates whether the value is a known member of the CredentialType enum.
func (e CredentialType) Valid() bool {
	switch e {
	case PublicKey:
		return true
	default:
		return false
	}
}

// Defines values for FrameValue.
const (
	BroadcastChannel        FrameValue = 4.294967295e+09
	CBORCapability          FrameValue = 4
	CBORCommand             FrameValue = 16
	CancelCommand           FrameValue = 17
	ContinuationHeaderBytes FrameValue = 5
	ErrorCommand            FrameValue = 63
	InitCommand             FrameValue = 6
	InitialFlag             FrameValue = 128
	InitialHeaderBytes      FrameValue = 7
	KeepaliveCommand        FrameValue = 59
	MaxPayloadBytes         FrameValue = 7609
	NonceBytes              FrameValue = 8
	ReportBytes             FrameValue = 64
	Usage                   FrameValue = 1
	UsagePage               FrameValue = 61904
)

// Valid indicates whether the value is a known member of the FrameValue enum.
func (e FrameValue) Valid() bool {
	switch e {
	case BroadcastChannel:
		return true
	case CBORCapability:
		return true
	case CBORCommand:
		return true
	case CancelCommand:
		return true
	case ContinuationHeaderBytes:
		return true
	case ErrorCommand:
		return true
	case InitCommand:
		return true
	case InitialFlag:
		return true
	case InitialHeaderBytes:
		return true
	case KeepaliveCommand:
		return true
	case MaxPayloadBytes:
		return true
	case NonceBytes:
		return true
	case ReportBytes:
		return true
	case Usage:
		return true
	case UsagePage:
		return true
	default:
		return false
	}
}

// Defines values for InfoOption.
const (
	AlwaysUv       InfoOption = "alwaysUv"
	BioEnroll      InfoOption = "bioEnroll"
	ClientPin      InfoOption = "clientPin"
	PinUvAuthToken InfoOption = "pinUvAuthToken"
	Uv             InfoOption = "uv"
)

// Valid indicates whether the value is a known member of the InfoOption enum.
func (e InfoOption) Valid() bool {
	switch e {
	case AlwaysUv:
		return true
	case BioEnroll:
		return true
	case ClientPin:
		return true
	case PinUvAuthToken:
		return true
	case Uv:
		return true
	default:
		return false
	}
}

// Defines values for InitResponseSize.
const (
	InitResponseBytes InitResponseSize = 17
)

// Valid indicates whether the value is a known member of the InitResponseSize enum.
func (e InitResponseSize) Valid() bool {
	switch e {
	case InitResponseBytes:
		return true
	default:
		return false
	}
}

// Defines values for KDFLabel.
const (
	AESKeyLabel  KDFLabel = "CTAP2 AES key"
	HMACKeyLabel KDFLabel = "CTAP2 HMAC key"
)

// Valid indicates whether the value is a known member of the KDFLabel enum.
func (e KDFLabel) Valid() bool {
	switch e {
	case AESKeyLabel:
		return true
	case HMACKeyLabel:
		return true
	default:
		return false
	}
}

// Defines values for PINCommand.
const (
	GetKeyAgreement PINCommand = 2
	GetUVToken      PINCommand = 6
)

// Valid indicates whether the value is a known member of the PINCommand enum.
func (e PINCommand) Valid() bool {
	switch e {
	case GetKeyAgreement:
		return true
	case GetUVToken:
		return true
	default:
		return false
	}
}

// Defines values for PINProtocol.
const (
	PINProtocolV1 PINProtocol = 1
	PINProtocolV2 PINProtocol = 2
)

// Valid indicates whether the value is a known member of the PINProtocol enum.
func (e PINProtocol) Valid() bool {
	switch e {
	case PINProtocolV1:
		return true
	case PINProtocolV2:
		return true
	default:
		return false
	}
}

// Defines values for PINRequestPermissions.
const (
	PINRequestPermissionsN2 PINRequestPermissions = 2
)

// Valid indicates whether the value is a known member of the PINRequestPermissions enum.
func (e PINRequestPermissions) Valid() bool {
	switch e {
	case PINRequestPermissionsN2:
		return true
	default:
		return false
	}
}

// Defines values for Status.
const (
	ChannelBusy     Status = 6
	NoCredentials   Status = 46
	RequestTooLarge Status = 57
	Success         Status = 0
	TokenRequired   Status = 54
	UVBlocked       Status = 60
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case ChannelBusy:
		return true
	case NoCredentials:
		return true
	case RequestTooLarge:
		return true
	case Success:
		return true
	case TokenRequired:
		return true
	case UVBlocked:
		return true
	default:
		return false
	}
}

// Defines values for U2FValue.
const (
	APDUHeaderBytes         U2FValue = 7
	APDUOverheadBytes       U2FValue = 9
	APDUSuccess             U2FValue = 36864
	AuthenticateInstruction U2FValue = 2
	MaxKeyHandleBytes       U2FValue = 255
	MessageCommand          U2FValue = 3
	PresenceRequired        U2FValue = 27013
	U2FHeaderBytes          U2FValue = 5
)

// Valid indicates whether the value is a known member of the U2FValue enum.
func (e U2FValue) Valid() bool {
	switch e {
	case APDUHeaderBytes:
		return true
	case APDUOverheadBytes:
		return true
	case APDUSuccess:
		return true
	case AuthenticateInstruction:
		return true
	case MaxKeyHandleBytes:
		return true
	case MessageCommand:
		return true
	case PresenceRequired:
		return true
	case U2FHeaderBytes:
		return true
	default:
		return false
	}
}

// AssertionOptions defines model for AssertionOptions.
type AssertionOptions struct {
	Up *bool `cbor:"up,omitempty" json:"up,omitempty"`
	Uv *bool `cbor:"uv,omitempty" json:"uv,omitempty"`
}

// AssertionRequest defines model for AssertionRequest.
type AssertionRequest struct {
	AllowList         *[]Credential     `cbor:"3,keyasint,omitempty" json:"allowList,omitempty"`
	ClientDataHash    []byte            `cbor:"2,keyasint" json:"clientDataHash"`
	Options           *AssertionOptions `cbor:"5,keyasint,omitempty" json:"options,omitempty"`
	PinUvAuthParam    *[]byte           `cbor:"6,keyasint,omitempty" json:"pinUvAuthParam,omitempty"`
	PinUvAuthProtocol *int              `cbor:"7,keyasint,omitempty" json:"pinUvAuthProtocol,omitempty"`
	RpId              string            `cbor:"1,keyasint" json:"rpId"`
}

// AssertionResponse defines model for AssertionResponse.
type AssertionResponse struct {
	AuthData            []byte         `cbor:"2,keyasint" json:"authData"`
	Credential          *Credential    `cbor:"1,keyasint,omitempty" json:"credential,omitempty"`
	NumberOfCredentials *int           `cbor:"5,keyasint,omitempty" json:"numberOfCredentials,omitempty"`
	Signature           []byte         `cbor:"3,keyasint" json:"signature"`
	User                *AssertionUser `cbor:"4,keyasint,omitempty" json:"user,omitempty"`
}

// AssertionUser defines model for AssertionUser.
type AssertionUser struct {
	Id *[]byte `cbor:"id,omitempty" json:"id,omitempty"`
}

// COSEKey defines model for COSEKey.
type COSEKey struct {
	Algorithm COSEKeyAlgorithm `cbor:"3,keyasint" json:"algorithm"`
	Curve     COSEKeyCurve     `cbor:"-1,keyasint" json:"curve"`
	KeyType   COSEKeyKeyType   `cbor:"1,keyasint" json:"keyType"`
	X         []byte           `cbor:"-2,keyasint" json:"x"`
	Y         []byte           `cbor:"-3,keyasint" json:"y"`
}

// COSEKeyAlgorithm defines model for COSEKey.Algorithm.
type COSEKeyAlgorithm int

// COSEKeyCurve defines model for COSEKey.Curve.
type COSEKeyCurve int

// COSEKeyKeyType defines model for COSEKey.KeyType.
type COSEKeyKeyType int

// CTAPCommand defines model for CTAPCommand.
type CTAPCommand int

// ClientData defines model for ClientData.
type ClientData struct {
	Challenge   string         `json:"challenge"`
	CrossOrigin bool           `json:"crossOrigin"`
	Origin      string         `json:"origin"`
	Type        ClientDataType `json:"type"`
}

// ClientDataTemplate defines model for ClientDataTemplate.
type ClientDataTemplate string

// ClientDataType defines model for ClientDataType.
type ClientDataType string

// Credential defines model for Credential.
type Credential struct {
	Id   []byte         `cbor:"id" json:"id"`
	Type CredentialType `cbor:"type" json:"type"`
}

// CredentialType defines model for CredentialType.
type CredentialType string

// FrameValue defines model for FrameValue.
type FrameValue int64

// InfoOption defines model for InfoOption.
type InfoOption string

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	Aaguid                   []byte           `cbor:"3,keyasint" json:"aaguid"`
	MaxCredentialCountInList *int             `cbor:"7,keyasint,omitempty" json:"maxCredentialCountInList,omitempty"`
	MaxCredentialIdLength    *int             `cbor:"8,keyasint,omitempty" json:"maxCredentialIdLength,omitempty"`
	MaxMsgSize               *int             `cbor:"5,keyasint,omitempty" json:"maxMsgSize,omitempty"`
	Options                  *map[string]bool `cbor:"4,keyasint,omitempty" json:"options,omitempty"`
	PinUvAuthProtocols       *[]int           `cbor:"6,keyasint,omitempty" json:"pinUvAuthProtocols,omitempty"`
	Versions                 []string         `cbor:"1,keyasint" json:"versions"`
}

// InitResponseSize defines model for InitResponseSize.
type InitResponseSize int

// KDFLabel defines model for KDFLabel.
type KDFLabel string

// PINCommand defines model for PINCommand.
type PINCommand int

// PINProtocol defines model for PINProtocol.
type PINProtocol int

// PINRequest defines model for PINRequest.
type PINRequest struct {
	Command         PINCommand             `cbor:"2,keyasint" json:"command"`
	KeyAgreement    *COSEKey               `cbor:"3,keyasint,omitempty" json:"keyAgreement,omitempty"`
	Permissions     *PINRequestPermissions `cbor:"9,keyasint,omitempty" json:"permissions,omitempty"`
	PermissionsRpId *string                `cbor:"10,keyasint,omitempty" json:"permissionsRpId,omitempty"`
	Protocol        PINProtocol            `cbor:"1,keyasint" json:"protocol"`
}

// PINRequestPermissions defines model for PINRequest.Permissions.
type PINRequestPermissions int

// PINResponse defines model for PINResponse.
type PINResponse struct {
	KeyAgreement *COSEKey `cbor:"1,keyasint,omitempty" json:"keyAgreement,omitempty"`
	Token        *[]byte  `cbor:"2,keyasint,omitempty" json:"token,omitempty"`
}

// Status defines model for Status.
type Status int

// U2FValue defines model for U2FValue.
type U2FValue int
