package command

const (
	photosStatusCommand        = "photos-status"
	photoAlbumsCommand         = "photo-albums"
	photoCountCommand          = "photo-count"
	photoAssetsCommand         = "photo-assets"
	photoDownloadCommand       = "photo-download"
	photoCommand               = "photo"
	photoLibrariesCommand      = "photo-libraries"
	photoCursorCommand         = "photo-cursor"
	photoChangesCommand        = "photo-changes"
	photoLibraryChangesCommand = "photo-library-changes"
	photosRecentCommand        = "photos-recently-added"
	photoUploadStatusCommand   = "photo-upload-status"
	photoVisitCommandName      = "photo-assets-visit"
	photosRecentVisitCommand   = "photos-recently-added-visit"
	sharedPhotoAlbumsCommand   = "shared-photo-albums"
	sharedPhotoCountCommand    = "shared-photo-count"
	sharedPhotosCommand        = "shared-photos"
	sharedPhotoCommand         = "shared-photo"
	sharedPhotoDownloadCommand = "shared-photo-download"
	accountDevicesCommand      = "account-devices"
	reminderAlarmsCommand      = "reminder-alarms"
	findMyDeviceCommand        = "findmy-device"
	findMySoundCommand         = "findmy-sound"
	findMyMessageCommand       = "findmy-message"
	findMyLostCommand          = "findmy-lost"
	findMyEraseCommand         = "findmy-erase"
)
