package command_test

// These literals are independent expected CLI names, Source keys and synthetic values.
const (
	testRequestFlag                     = "--request"
	testSaveResultFlag                  = "--save-result"
	testSessionFlag                     = "--session"
	testAccountIDKey                    = "accountID"
	testAssetMetadataKey                = "assetMetadata"
	testAuthorizationKey                = "Authorization"
	testContentJpgFilename              = "content.jpg"
	testDuplicateKey                    = "duplicate"
	testPhotosServiceURL                = "https://photos.example.invalid"
	testOpaqueReceiptKey                = "opaqueReceipt"
	testOpaqueStatusKey                 = "opaqueStatus"
	testPhotoAssetsVisitCommand         = "photo-assets-visit"
	testPhotoUploadFileCommand          = "photo-upload-file"
	testPhotoUploadReserveCommand       = "photo-upload-reserve"
	testPhotoUploadStatusCommand        = "photo-upload-status"
	testPreviousReceipt                 = "previous receipt"
	testReminderAttachmentUpdateCommand = "reminder-attachment-update"
	testReminderCreateCommand           = "reminder-create"
	testRequestJSONFilename             = "request.json"
	testResponsesKey                    = "responses"
	testResultJSONFilename              = "result.json"
	testSessionJSONFilename             = "session.json"
	testStoredAccount                   = "stored-account"
	testStoredClient                    = "stored-client"
	testSyntheticPhotoContent           = "synthetic photo"
	testSyntheticJob                    = "synthetic-job"
	testSyntheticPhotoID                = "synthetic-photo"
	testUnreviewedProviderFieldKey      = "unreviewedProviderField"
	testUploadURLsKey                   = "uploadURLs"
	testVersionsKey                     = "versions"
)
