package command

const (
	accountFamilyCommand          = "account-family"
	accountPlanCommand            = "account-plan"
	accountStorageCommand         = "account-storage"
	reminderLegacySnapshotCommand = "reminder-legacy-snapshot"
	reminderChangesCommand        = "reminder-changes"
	reminderSnapshotCommand       = "reminder-snapshot"
	reminderAttachmentsCommand    = "reminder-attachments"
	reminderZonesCommand          = "reminder-zones"
	reminderListsCommand          = "reminder-lists"
	reminderSyncCommand           = "reminder-sync"
	reminderTagsCommand           = "reminder-tags"
	reminderRecurrencesCommand    = "reminder-recurrence-rules"
	remindersCommand              = "reminders"
	writeReminderCreate           = "reminder-create"
	writeReminderUpdate           = "reminder-update"
	writeReminderDelete           = "reminder-delete"
	writeHashtagCreate            = "reminder-hashtag-create"
	writeHashtagUpdate            = "reminder-hashtag-update"
	writeHashtagDelete            = "reminder-hashtag-delete"
	writeRecurrenceCreate         = "reminder-recurrence-create"
	writeRecurrenceUpdate         = "reminder-recurrence-update"
	writeRecurrenceDelete         = "reminder-recurrence-delete"
	writeAttachmentCreate         = "reminder-attachment-create"
	writeAttachmentUpdate         = "reminder-attachment-update"
	writeAttachmentDelete         = "reminder-attachment-delete"
	writeLocationAdd              = "reminder-location-add"
	writePhotoUploadFile          = "photo-upload-file"
	writePhotoUploadReserve       = "photo-upload-reserve"
	writePhotoUploadSend          = "photo-upload-send"
	findMyDiscoveryError          = "discover Find My devices: %w"
	devicePasscodeEnvironment     = "GO_ICLOUD_DEVICE_PASSCODE"
	privateMetadataField          = "metadata"
	privateResponsesField         = "responses"
	privateSessionCanceledError   = "private session canceled: %w"
	secretInputCanceledError      = "secret input canceled: %w"
)
