// Package drivecontentapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package drivecontentapi

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/portpowered/go-icloud/pkg/dependencymodels/drive"
	externalRef1 "github.com/portpowered/go-icloud/pkg/dependencymodels/httpboundary"
)

// DriveError Extensible JSON error envelope; raw response bytes must also remain available.
type DriveError = externalRef0.DriveError

// DriveMultipartUpload One file field named for the source filename; multipart framing and exact content are verified separately.
type DriveMultipartUpload map[string]openapi_types.File

// DriveUploadReceipt Example: {"singleFile":{"fileChecksum":"synthetic","referenceChecksum":"synthetic","size":0,"wrappingKey":"synthetic"}}
type DriveUploadReceipt = externalRef0.DriveUploadReceipt

// DriveContentFailure Extensible JSON error envelope; raw response bytes must also remain available.
type DriveContentFailure = DriveError

// DriveDownloadContentParams defines parameters for DriveDownloadContent.
type DriveDownloadContentParams struct {
	// Cookie Optional caller or provider session cookies selected by the operation-local jar for this exact URL. Source PyiCloudSession inherits requests.Session cookie domain/path/secure selection; absent or nonmatching cookies emit no Cookie header, and an explicit caller Cookie header takes precedence.
	Cookie *externalRef1.SessionCookie `json:"Cookie,omitempty"`

	// Accept Caller content negotiation; the SDK default is the declared wildcard primitive.
	Accept *externalRef1.ContentAccept `json:"Accept,omitempty"`
}

// DriveUploadContentParams defines parameters for DriveUploadContent.
type DriveUploadContentParams struct {
	// Cookie Optional caller or provider session cookies selected by the operation-local jar for this exact URL. Source PyiCloudSession inherits requests.Session cookie domain/path/secure selection; absent or nonmatching cookies emit no Cookie header, and an explicit caller Cookie header takes precedence.
	Cookie *externalRef1.SessionCookie `json:"Cookie,omitempty"`

	// Accept Caller content negotiation; the SDK default is the declared wildcard primitive.
	Accept *externalRef1.ContentAccept `json:"Accept,omitempty"`
}

// DriveUploadContentMultipartRequestBody defines body for DriveUploadContent for multipart/form-data ContentType.
type DriveUploadContentMultipartRequestBody = DriveMultipartUpload

// NewDriveDownloadContentRequest constructs an http.Request for the DriveDownloadContent method
func NewDriveDownloadContentRequest(server string, contentPath string, params *DriveDownloadContentParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "contentPath", contentPath, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Cookie != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam0)
		}

		if params.Accept != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam1)
		}

	}

	return req, nil
}

// NewDriveUploadContentRequestWithBody constructs an http.Request for the DriveUploadContent method, with any body, and a specified content type
func NewDriveUploadContentRequestWithBody(server string, contentPath string, params *DriveUploadContentParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "contentPath", contentPath, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Cookie != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam0)
		}

		if params.Accept != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam1)
		}

	}

	return req, nil
}

type DriveDownloadContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *DriveContentFailure
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DriveDownloadContentResponse) GetJSONDefault() *DriveContentFailure {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DriveDownloadContentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DriveDownloadContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DriveDownloadContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DriveDownloadContentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DriveUploadContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DriveUploadReceipt
	// JSON2XX the response for an HTTP 2XX `application/json` response
	JSON2XX *DriveUploadReceipt
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *DriveContentFailure
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DriveUploadContentResponse) GetJSON200() *DriveUploadReceipt {
	return r.JSON200
}

// GetJSON2XX returns the response for an HTTP 2XX `application/json` response
func (r DriveUploadContentResponse) GetJSON2XX() *DriveUploadReceipt {
	return r.JSON2XX
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DriveUploadContentResponse) GetJSONDefault() *DriveContentFailure {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DriveUploadContentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DriveUploadContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DriveUploadContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DriveUploadContentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ParseDriveDownloadContentResponse parses an HTTP response for the DriveDownloadContent operation
func ParseDriveDownloadContentResponse(rsp *http.Response) (*DriveDownloadContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DriveDownloadContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest DriveContentFailure
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDriveUploadContentResponse parses an HTTP response for the DriveUploadContent operation
func ParseDriveUploadContentResponse(rsp *http.Response) (*DriveUploadContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DriveUploadContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DriveUploadReceipt
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 2:
		var dest DriveUploadReceipt
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON2XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest DriveContentFailure
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
