// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/external/bridge-proto/bridge.proto

package bridgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_OK            Status = 0
	Status_STATUS_INVALID_NONCE Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_OK",
		2: "STATUS_INVALID_NONCE",
	}
	Status_value = map[string]int32{
		"STATUS_OK":            0,
		"STATUS_INVALID_NONCE": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_external_bridge_proto_bridge_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_external_bridge_proto_bridge_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Status(num)
	return nil
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{0}
}

type Opcode int32

const (
	Opcode_OPCODE_CONTINUATION Opcode = 0
	Opcode_OPCODE_TEXT         Opcode = 1
	Opcode_OPCODE_BINARY       Opcode = 2
	Opcode_OPCODE_CLOSE        Opcode = 8
	Opcode_OPCODE_PING         Opcode = 9
	Opcode_OPCODE_PONG         Opcode = 10
)

// Enum value maps for Opcode.
var (
	Opcode_name = map[int32]string{
		0:  "OPCODE_CONTINUATION",
		1:  "OPCODE_TEXT",
		2:  "OPCODE_BINARY",
		8:  "OPCODE_CLOSE",
		9:  "OPCODE_PING",
		10: "OPCODE_PONG",
	}
	Opcode_value = map[string]int32{
		"OPCODE_CONTINUATION": 0,
		"OPCODE_TEXT":         1,
		"OPCODE_BINARY":       2,
		"OPCODE_CLOSE":        8,
		"OPCODE_PING":         9,
		"OPCODE_PONG":         10,
	}
)

func (x Opcode) Enum() *Opcode {
	p := new(Opcode)
	*p = x
	return p
}

func (x Opcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Opcode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_external_bridge_proto_bridge_proto_enumTypes[1].Descriptor()
}

func (Opcode) Type() protoreflect.EnumType {
	return &file_api_external_bridge_proto_bridge_proto_enumTypes[1]
}

func (x Opcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Opcode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Opcode(num)
	return nil
}

// Deprecated: Use Opcode.Descriptor instead.
func (Opcode) EnumDescriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{1}
}

type Framing int32

const (
	Framing_FRAMING_UNSPECIFIED         Framing = 0
	Framing_FRAMING_NONCE_VERSION       Framing = 0
	Framing_FRAMING_NONCE_ENTROPY_BYTES Framing = 8
	Framing_FRAMING_MASK_BYTES          Framing = 4
	Framing_FRAMING_KEY_BYTES           Framing = 16
	Framing_FRAMING_FIN_MASK            Framing = 128
	Framing_FRAMING_SHORT_LIMIT         Framing = 126
	Framing_FRAMING_LONG_MARKER         Framing = 127
	Framing_FRAMING_MEDIUM_LIMIT        Framing = 65536
)

// Enum value maps for Framing.
var (
	Framing_name = map[int32]string{
		0: "FRAMING_UNSPECIFIED",
		// Duplicate value: 0: "FRAMING_NONCE_VERSION",
		8:     "FRAMING_NONCE_ENTROPY_BYTES",
		4:     "FRAMING_MASK_BYTES",
		16:    "FRAMING_KEY_BYTES",
		128:   "FRAMING_FIN_MASK",
		126:   "FRAMING_SHORT_LIMIT",
		127:   "FRAMING_LONG_MARKER",
		65536: "FRAMING_MEDIUM_LIMIT",
	}
	Framing_value = map[string]int32{
		"FRAMING_UNSPECIFIED":         0,
		"FRAMING_NONCE_VERSION":       0,
		"FRAMING_NONCE_ENTROPY_BYTES": 8,
		"FRAMING_MASK_BYTES":          4,
		"FRAMING_KEY_BYTES":           16,
		"FRAMING_FIN_MASK":            128,
		"FRAMING_SHORT_LIMIT":         126,
		"FRAMING_LONG_MARKER":         127,
		"FRAMING_MEDIUM_LIMIT":        65536,
	}
)

func (x Framing) Enum() *Framing {
	p := new(Framing)
	*p = x
	return p
}

func (x Framing) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Framing) Descriptor() protoreflect.EnumDescriptor {
	return file_api_external_bridge_proto_bridge_proto_enumTypes[2].Descriptor()
}

func (Framing) Type() protoreflect.EnumType {
	return &file_api_external_bridge_proto_bridge_proto_enumTypes[2]
}

func (x Framing) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Framing) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Framing(num)
	return nil
}

// Deprecated: Use Framing.Descriptor instead.
func (Framing) EnumDescriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{2}
}

// Source-matched APNS webcourier binary field inventory. This is reconstructed
// from the pinned Python encoder/decoder, not a provider-published protocol.
type Expiration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       *uint32                `protobuf:"varint,1,opt,name=seconds,def=86400" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Expiration fields.
const (
	Default_Expiration_Seconds = uint32(86400)
)

func (x *Expiration) Reset() {
	*x = Expiration{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expiration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expiration) ProtoMessage() {}

func (x *Expiration) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expiration.ProtoReflect.Descriptor instead.
func (*Expiration) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Expiration) GetSeconds() uint32 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return Default_Expiration_Seconds
}

type ConnectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uncompressed SEC1 P-256 point: 0x04 followed by 32-byte big-endian X and Y.
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	// One zero version byte, eight-byte unsigned big-endian Unix milliseconds,
	// and eight bytes of cryptographic entropy. Signature authenticates all bytes.
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	// Two-byte 0x0103 prefix followed by ASN.1 DER ECDSA(SHA-256(nonce)).
	Signature     []byte      `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	Expiration    *Expiration `protobuf:"bytes,5,opt,name=expiration" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ConnectionRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ConnectionRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ConnectionRequest) GetExpiration() *Expiration {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Acknowledgement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Topic          []byte                 `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	MessageId      *uint64                `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	DeliveryStatus *uint64                `protobuf:"varint,3,opt,name=delivery_status,json=deliveryStatus" json:"delivery_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *Acknowledgement) GetTopic() []byte {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Acknowledgement) GetMessageId() uint64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *Acknowledgement) GetDeliveryStatus() uint64 {
	if x != nil && x.DeliveryStatus != nil {
		return *x.DeliveryStatus
	}
	return 0
}

type ClientMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Connection      *ConnectionRequest     `protobuf:"bytes,1,opt,name=connection" json:"connection,omitempty"`
	Acknowledgement *Acknowledgement       `protobuf:"bytes,2,opt,name=acknowledgement" json:"acknowledgement,omitempty"`
	Subscription    *SubscriptionRequest   `protobuf:"bytes,3,opt,name=subscription" json:"subscription,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMessage) GetConnection() *ConnectionRequest {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *ClientMessage) GetAcknowledgement() *Acknowledgement {
	if x != nil {
		return x.Acknowledgement
	}
	return nil
}

func (x *ClientMessage) GetSubscription() *SubscriptionRequest {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type ConnectionResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PushTokenBase64        []byte                 `protobuf:"bytes,1,opt,name=push_token_base64,json=pushTokenBase64" json:"push_token_base64,omitempty"`
	Status                 *uint64                `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	ServerTimestampSeconds *uint64                `protobuf:"varint,3,opt,name=server_timestamp_seconds,json=serverTimestampSeconds" json:"server_timestamp_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectionResponse) GetPushTokenBase64() []byte {
	if x != nil {
		return x.PushTokenBase64
	}
	return nil
}

func (x *ConnectionResponse) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ConnectionResponse) GetServerTimestampSeconds() uint64 {
	if x != nil && x.ServerTimestampSeconds != nil {
		return *x.ServerTimestampSeconds
	}
	return 0
}

type PushMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Topic     []byte                 `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	MessageId *uint64                `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	// UTF-8 JSON BridgePushPayload from bridge-models.openapi.yaml, optionally
	// prefixed/suffixed by transport framing bytes. Preserve unknown JSON members.
	Payload       []byte `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *PushMessage) GetTopic() []byte {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *PushMessage) GetMessageId() uint64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *PushMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AppSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         []byte                 `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSubscriptionResponse) Reset() {
	*x = AppSubscriptionResponse{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSubscriptionResponse) ProtoMessage() {}

func (x *AppSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*AppSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *AppSubscriptionResponse) GetTopic() []byte {
	if x != nil {
		return x.Topic
	}
	return nil
}

type SubscriptionPayload struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Apps          []*AppSubscriptionResponse `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionPayload) Reset() {
	*x = SubscriptionPayload{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPayload) ProtoMessage() {}

func (x *SubscriptionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionPayload.ProtoReflect.Descriptor instead.
func (*SubscriptionPayload) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *SubscriptionPayload) GetApps() []*AppSubscriptionResponse {
	if x != nil {
		return x.Apps
	}
	return nil
}

type SubscriptionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Payload              *SubscriptionPayload   `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	MessageId            *uint64                `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	Status               *uint64                `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	RetryIntervalSeconds *uint64                `protobuf:"varint,4,opt,name=retry_interval_seconds,json=retryIntervalSeconds" json:"retry_interval_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *SubscriptionResponse) GetPayload() *SubscriptionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubscriptionResponse) GetMessageId() uint64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *SubscriptionResponse) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *SubscriptionResponse) GetRetryIntervalSeconds() uint64 {
	if x != nil && x.RetryIntervalSeconds != nil {
		return *x.RetryIntervalSeconds
	}
	return 0
}

type ServerMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Connection      *ConnectionResponse    `protobuf:"bytes,1,opt,name=connection" json:"connection,omitempty"`
	Push            *PushMessage           `protobuf:"bytes,2,opt,name=push" json:"push,omitempty"`
	Subscription    *SubscriptionResponse  `protobuf:"bytes,3,opt,name=subscription" json:"subscription,omitempty"`
	Acknowledgement *Acknowledgement       `protobuf:"bytes,7,opt,name=acknowledgement" json:"acknowledgement,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_bridge_proto_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_external_bridge_proto_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *ServerMessage) GetConnection() *ConnectionResponse {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *ServerMessage) GetPush() *PushMessage {
	if x != nil {
		return x.Push
	}
	return nil
}

func (x *ServerMessage) GetSubscription() *SubscriptionResponse {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *ServerMessage) GetAcknowledgement() *Acknowledgement {
	if x != nil {
		return x.Acknowledgement
	}
	return nil
}

var File_api_external_bridge_proto_bridge_proto protoreflect.FileDescriptor

const file_api_external_bridge_proto_bridge_proto_rawDesc = "" +
	"\n" +
	"&api/external/bridge-proto/bridge.proto\x12\ricloud.bridge\"-\n" +
	"\n" +
	"Expiration\x12\x1f\n" +
	"\aseconds\x18\x01 \x01(\r:\x0586400R\aseconds\"\xa1\x01\n" +
	"\x11ConnectionRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x129\n" +
	"\n" +
	"expiration\x18\x05 \x01(\v2\x19.icloud.bridge.ExpirationR\n" +
	"expiration\"-\n" +
	"\x13SubscriptionRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"o\n" +
	"\x0fAcknowledgement\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\fR\x05topic\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageId\x12'\n" +
	"\x0fdelivery_status\x18\x03 \x01(\x04R\x0edeliveryStatus\"\xe3\x01\n" +
	"\rClientMessage\x12@\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2 .icloud.bridge.ConnectionRequestR\n" +
	"connection\x12H\n" +
	"\x0facknowledgement\x18\x02 \x01(\v2\x1e.icloud.bridge.AcknowledgementR\x0facknowledgement\x12F\n" +
	"\fsubscription\x18\x03 \x01(\v2\".icloud.bridge.SubscriptionRequestR\fsubscription\"\x92\x01\n" +
	"\x12ConnectionResponse\x12*\n" +
	"\x11push_token_base64\x18\x01 \x01(\fR\x0fpushTokenBase64\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x04R\x06status\x128\n" +
	"\x18server_timestamp_seconds\x18\x03 \x01(\x04R\x16serverTimestampSeconds\"\\\n" +
	"\vPushMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\fR\x05topic\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"/\n" +
	"\x17AppSubscriptionResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\fR\x05topic\"Q\n" +
	"\x13SubscriptionPayload\x12:\n" +
	"\x04apps\x18\x01 \x03(\v2&.icloud.bridge.AppSubscriptionResponseR\x04apps\"\xc1\x01\n" +
	"\x14SubscriptionResponse\x12<\n" +
	"\apayload\x18\x01 \x01(\v2\".icloud.bridge.SubscriptionPayloadR\apayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x04R\x06status\x124\n" +
	"\x16retry_interval_seconds\x18\x04 \x01(\x04R\x14retryIntervalSeconds\"\x95\x02\n" +
	"\rServerMessage\x12A\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2!.icloud.bridge.ConnectionResponseR\n" +
	"connection\x12.\n" +
	"\x04push\x18\x02 \x01(\v2\x1a.icloud.bridge.PushMessageR\x04push\x12G\n" +
	"\fsubscription\x18\x03 \x01(\v2#.icloud.bridge.SubscriptionResponseR\fsubscription\x12H\n" +
	"\x0facknowledgement\x18\a \x01(\v2\x1e.icloud.bridge.AcknowledgementR\x0facknowledgement*1\n" +
	"\x06Status\x12\r\n" +
	"\tSTATUS_OK\x10\x00\x12\x18\n" +
	"\x14STATUS_INVALID_NONCE\x10\x02*y\n" +
	"\x06Opcode\x12\x17\n" +
	"\x13OPCODE_CONTINUATION\x10\x00\x12\x0f\n" +
	"\vOPCODE_TEXT\x10\x01\x12\x11\n" +
	"\rOPCODE_BINARY\x10\x02\x12\x10\n" +
	"\fOPCODE_CLOSE\x10\b\x12\x0f\n" +
	"\vOPCODE_PING\x10\t\x12\x0f\n" +
	"\vOPCODE_PONG\x10\n" +
	"*\xf6\x01\n" +
	"\aFraming\x12\x17\n" +
	"\x13FRAMING_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FRAMING_NONCE_VERSION\x10\x00\x12\x1f\n" +
	"\x1bFRAMING_NONCE_ENTROPY_BYTES\x10\b\x12\x16\n" +
	"\x12FRAMING_MASK_BYTES\x10\x04\x12\x15\n" +
	"\x11FRAMING_KEY_BYTES\x10\x10\x12\x15\n" +
	"\x10FRAMING_FIN_MASK\x10\x80\x01\x12\x17\n" +
	"\x13FRAMING_SHORT_LIMIT\x10~\x12\x17\n" +
	"\x13FRAMING_LONG_MARKER\x10\x7f\x12\x1a\n" +
	"\x14FRAMING_MEDIUM_LIMIT\x10\x80\x80\x04\x1a\x02\x10\x01B@Z>github.com/portpowered/go-icloud/pkg/dependencymodels/bridgepb"

var (
	file_api_external_bridge_proto_bridge_proto_rawDescOnce sync.Once
	file_api_external_bridge_proto_bridge_proto_rawDescData []byte
)

func file_api_external_bridge_proto_bridge_proto_rawDescGZIP() []byte {
	file_api_external_bridge_proto_bridge_proto_rawDescOnce.Do(func() {
		file_api_external_bridge_proto_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_external_bridge_proto_bridge_proto_rawDesc), len(file_api_external_bridge_proto_bridge_proto_rawDesc)))
	})
	return file_api_external_bridge_proto_bridge_proto_rawDescData
}

var file_api_external_bridge_proto_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_external_bridge_proto_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_external_bridge_proto_bridge_proto_goTypes = []any{
	(Status)(0),                     // 0: icloud.bridge.Status
	(Opcode)(0),                     // 1: icloud.bridge.Opcode
	(Framing)(0),                    // 2: icloud.bridge.Framing
	(*Expiration)(nil),              // 3: icloud.bridge.Expiration
	(*ConnectionRequest)(nil),       // 4: icloud.bridge.ConnectionRequest
	(*SubscriptionRequest)(nil),     // 5: icloud.bridge.SubscriptionRequest
	(*Acknowledgement)(nil),         // 6: icloud.bridge.Acknowledgement
	(*ClientMessage)(nil),           // 7: icloud.bridge.ClientMessage
	(*ConnectionResponse)(nil),      // 8: icloud.bridge.ConnectionResponse
	(*PushMessage)(nil),             // 9: icloud.bridge.PushMessage
	(*AppSubscriptionResponse)(nil), // 10: icloud.bridge.AppSubscriptionResponse
	(*SubscriptionPayload)(nil),     // 11: icloud.bridge.SubscriptionPayload
	(*SubscriptionResponse)(nil),    // 12: icloud.bridge.SubscriptionResponse
	(*ServerMessage)(nil),           // 13: icloud.bridge.ServerMessage
}
var file_api_external_bridge_proto_bridge_proto_depIdxs = []int32{
	3,  // 0: icloud.bridge.ConnectionRequest.expiration:type_name -> icloud.bridge.Expiration
	4,  // 1: icloud.bridge.ClientMessage.connection:type_name -> icloud.bridge.ConnectionRequest
	6,  // 2: icloud.bridge.ClientMessage.acknowledgement:type_name -> icloud.bridge.Acknowledgement
	5,  // 3: icloud.bridge.ClientMessage.subscription:type_name -> icloud.bridge.SubscriptionRequest
	10, // 4: icloud.bridge.SubscriptionPayload.apps:type_name -> icloud.bridge.AppSubscriptionResponse
	11, // 5: icloud.bridge.SubscriptionResponse.payload:type_name -> icloud.bridge.SubscriptionPayload
	8,  // 6: icloud.bridge.ServerMessage.connection:type_name -> icloud.bridge.ConnectionResponse
	9,  // 7: icloud.bridge.ServerMessage.push:type_name -> icloud.bridge.PushMessage
	12, // 8: icloud.bridge.ServerMessage.subscription:type_name -> icloud.bridge.SubscriptionResponse
	6,  // 9: icloud.bridge.ServerMessage.acknowledgement:type_name -> icloud.bridge.Acknowledgement
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_external_bridge_proto_bridge_proto_init() }
func file_api_external_bridge_proto_bridge_proto_init() {
	if File_api_external_bridge_proto_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_external_bridge_proto_bridge_proto_rawDesc), len(file_api_external_bridge_proto_bridge_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_external_bridge_proto_bridge_proto_goTypes,
		DependencyIndexes: file_api_external_bridge_proto_bridge_proto_depIdxs,
		EnumInfos:         file_api_external_bridge_proto_bridge_proto_enumTypes,
		MessageInfos:      file_api_external_bridge_proto_bridge_proto_msgTypes,
	}.Build()
	File_api_external_bridge_proto_bridge_proto = out.File
	file_api_external_bridge_proto_bridge_proto_goTypes = nil
	file_api_external_bridge_proto_bridge_proto_depIdxs = nil
}
