package: photosuploadapi
generate:
  models: true
  client: true
output: pkg/dependencies/webtransport/photosuploadapi/client.gen.go
output-options:
  user-templates:
    client.tmpl: api/templates/http-request-builders.tmpl
    client-with-responses.tmpl: api/templates/http-response-parsers.tmpl
  nullable-type: true
  skip-prune: true
import-mapping:
  ./cloudkit-models.openapi.yaml: github.com/portpowered/go-icloud/pkg/dependencymodels/cloudkit
  ./photos-upload-models.openapi.yaml: github.com/portpowered/go-icloud/pkg/dependencymodels/photosupload
