package: findmyapi
generate:
  models: true
  client: true
output: internal/findmyapi/client.gen.go
output-options:
  nullable-type: true
import-mapping:
  ./findmy-models.openapi.yaml: github.com/portpowered/go-icloud/pkg/dependencymodels/findmy
