package replay_test

// Independent literals preserve synthetic controls and Source spellings.
const (
	replayExpectedExampleInvalid                       = ".example.invalid"
	replayExpectedAlbumRecordBytes                     = "AAECAwQFBgcICQoLDA0ODw=="
	replayExpectedChangesResponseValidationFailed      = "Changes response validation failed"
	replayExpectedContentType                          = "Content-Type"
	replayExpectedPyiCloudAPIResponseException         = "PyiCloudAPIResponseException"
	replayExpectedPyiCloudServiceNotActivatedException = "PyiCloudServiceNotActivatedException"
	replayExpectedReadTimeout                          = "ReadTimeout"
	replayExpectedSynthetic0                           = "Synthetic 0"
	replayExpectedAccount                              = "account-"
	replayExpectedAccountCountry                       = "account_country"
	replayExpectedAlbumDelete                          = "album_delete"
	replayExpectedAlbumRename                          = "album_rename"
	replayExpectedJSONMedia                            = "application/json"
	replayExpectedBinaryMedia                          = "application/octet-stream"
	replayExpectedAttachmentsFor                       = "attachments_for"
	replayExpectedAuthAuthenticateCached               = "auth-authenticate-cached"
	replayExpectedConnectionClose                      = "connection_close"
	replayExpectedContent                              = "content-"
	replayExpectedCreateAlbum                          = "create_album"
	replayExpectedEncoding                             = "encoding"
	replayExpectedEscapedPath                          = "escaped_path"
	replayExpectedExchanges                            = "exchanges"
	replayExpectedRelatedCallFormat                    = "execute related reminder scenario: %w"
	replayExpectedExtraHeader                          = "extra_header"
	replayExpectedFileAssetURL                         = "fileAssetURL"
	replayExpectedFileSize                             = "fileSize"
	replayExpectedSourceFileAssetURL                   = "file_asset_url"
	replayExpectedFixtures                             = "fixtures"
	replayExpectedFixturesSyntheticHTTP                = "fixtures/synthetic/http"
	replayExpectedAlbumFixturePath                     = "fixtures/synthetic/http/photos-create-album.json"
	replayExpectedForceQuery                           = "force_query"
	replayExpectedFragment                             = "fragment"
	replayExpectedFullName                             = "fullName"
	replayExpectedFullname                             = "fullname"
	replayExpectedHeaderLength                         = "header_length"
	replayExpectedInvented                             = "invented"
	replayExpectedNoOutcome                            = "no_outcome"
	replayExpectedOperation                            = "operation"
	replayExpectedOtherInvalid                         = "other.invalid"
	replayExpectedPhotosAddToAlbum                     = "photos-add-to-album"
	replayExpectedPhotosCreateAlbum                    = "photos-create-album"
	replayExpectedPhotosCreateFolder                   = "photos-create-folder"
	replayExpectedPhotosDeleteAlbum                    = "photos-delete-album"
	replayExpectedPhotosDeleteAsset                    = "photos-delete-asset"
	replayExpectedPhotosDeleteAssetRecordRejection     = "photos-delete-asset-record-rejection"
	replayExpectedPhotosFavoriteTrue                   = "photos-favorite-true"
	replayExpectedPhotosRenameAlbum                    = "photos-rename-album"
	replayExpectedPluginFields                         = "pluginFields"
	replayExpectedQueryOrder                           = "query_order"
	replayExpectedRecurrenceRulesFor                   = "recurrence_rules_for"
	replayExpectedRepresentation                       = "representation"
	replayExpectedResOriginalFileSize                  = "resOriginalFileSize"
	replayExpectedSession                              = "session="
	replayExpectedSessionUploaded                      = "session=uploaded-"
	replayExpectedSessionData                          = "session_data"
	replayExpectedSessionStateField                    = "session_token"
	replayExpectedCursorField                          = "sync_token"
	replayExpectedSynthetic                            = "synthetic"
	replayExpectedSyntheticClient                      = "synthetic-client"
	replayExpectedTagsFor                              = "tags_for"
	replayExpectedTrustedStateField                    = "trust_token"
	replayExpectedUnknownLength                        = "unknown_length"
	replayExpectedUserinfo                             = "userinfo"
)

// Independent literals retain exact cross-file Source expectations.
const (
	replayCursorErrorsFormat                        = "%v / %v / %v"
	replayLiteralShared                             = "-shared-"
	replayLiteralPathSecureHTTPOnly                 = "; Path=/; Secure; HttpOnly"
	replayLiteralContentLength                      = "Content-Length"
	replayDriveReadErrorFormat                      = "Drive SDK read: %w"
	replayLiteralLookupError                        = "LookupError"
	replayLiteralTempIDAa                           = "TempId-aa"
	replayAccountServiceErrorFormat                 = "account SDK service: %w"
	replayLiteralArguments                          = "arguments"
	replayLiteralBase64Whitespace                   = "base64-whitespace"
	replayLiteralBoundary                           = "boundary"
	replayLiteralChecksum                           = "checksum"
	replayLiteralCompletedDate                      = "completedDate"
	replayLiteralCreateFolders                      = "create_folders"
	replayLiteralCreateHashtag                      = "create_hashtag"
	replayLiteralDeleteAttachment                   = "delete_attachment"
	replayLiteralDeleteForeverFromTrash             = "delete_forever_from_trash"
	replayLiteralDeleteItems                        = "delete_items"
	replayLiteralDeleteRecurrenceRule               = "delete_recurrence_rule"
	replayLiteralDifferentDocument                  = "different-document"
	replayLiteralDocumentID                         = "document_id"
	replayLiteralDocuments                          = "documents"
	replayLiteralDownloadBinary                     = "download-binary"
	replayLiteralDueDate                            = "due_date"
	replayLiteralDuplicate                          = "duplicate"
	replayLiteralDuplicateType                      = "duplicate_type"
	replayLiteralEpilogue                           = "epilogue"
	replayLiteralErrorMessage                       = "errorMessage"
	replayLiteralErrorAuthState                     = "error_auth_state"
	replayLiteralEscapedDuplicate                   = "escaped_duplicate"
	replayLiteralExplicitHeader                     = "explicit-header"
	replayLiteralExplicitFixed                      = "explicit=fixed"
	replayLiteralExtraPart                          = "extra_part"
	replayLiteralFamilyPhotos                       = "family_photos"
	replayLiteralFilePosition                       = "file_position"
	replayLiteralFileSize                           = "file_size"
	replayLiteralFilename                           = "filename"
	replayLiteralFixturesSyntheticHTTPAccountJSON   = "fixtures/synthetic/http/account-*.json"
	replayLiteralFixturesSyntheticHTTPDriveJSON     = "fixtures/synthetic/http/drive-*.json"
	replayDriveBinaryFixturePath                    = "fixtures/synthetic/http/drive-download-data_token-binary.json"
	replayDriveRootFixturePath                      = "fixtures/synthetic/http/drive-root-listing-1.json"
	replayLiteralFixturesSyntheticHTTPFindmyJSON    = "fixtures/synthetic/http/findmy-*.json"
	replayLiteralFixturesSyntheticHTTPReminders     = "fixtures/synthetic/http/reminders-"
	replayLiteralFixturesSyntheticSocketJSON        = "fixtures/synthetic/socket/*.json"
	replayLiteralGetAppData                         = "get_app_data"
	replayLiteralInitialState                       = "initial_state"
	replayLiteralInteriorClose                      = "interior_close"
	replayLiteralIsRetryable                        = "isRetryable"
	replayLiteralItemType                           = "itemType"
	replayLiteralJSONRedacted                       = "json-redacted"
	replayLiteralKeywordInputs                      = "keyword_inputs"
	replayLiteralLikeCount                          = "like_count"
	replayLiteralMasterID                           = "masterID"
	replayLiteralModified                           = "modified"
	replayLiteralMonotonic                          = "monotonic"
	replayLiteralMoveItemsToTrash                   = "move_items_to_trash"
	replayLiteralMoveNodesToNode                    = "move_nodes_to_node"
	replayLiteralMultipart                          = "multipart"
	replayLiteralMutatedResult                      = "mutated-result"
	replayLiteralNextStep                           = "next_step"
	replayLiteralNoMatchers                         = "no_matchers"
	replayNodeErrorFormat                           = "node replay: %w"
	replayAssetFailureFormat                        = "photo asset read failed: %v"
	replayLiteralPhotoAssetScenarioInventoryChanged = "photo asset scenario inventory changed"
	replayEnumerationFailureMessage                 = "photo enumeration returned partial results on failure"
	replayLiteralPhotosAssetsPaginationJSON         = "photos-assets-pagination.json"
	replayLiteralPhotosUploadBytesBinaryJSON        = "photos-upload-bytes-binary.json"
	replayLiteralPhotosUploadReserve1JSON           = "photos-upload-reserve-1.json"
	replayLiteralPreamble                           = "preamble"
	replayLiteralRecordError                        = "record-error"
	replayLiteralRecordName                         = "record_name"
	replayLiteralRecordType                         = "record_type"
	replayLiteralRecoverItemsFromTrash              = "recover_items_from_trash"
	replayLiteralRefreshAuthState                   = "refresh_auth_state"
	replayLiteralReminders                          = "reminders"
	replayLiteralRenameItems                        = "rename_items"
	replayLiteralResponse                           = "response"
	replayLiteralRetryable                          = "retryable"
	replayLiteralSendBinary                         = "send_binary"
	replayLiteralServiceDir                         = "service_dir"
	replayLiteralServiceGetitem                     = "service_getitem"
	replayLiteralSessionAlpha                       = "session=alpha"
	replayLiteralSessionBeta                        = "session=beta"
	replayLiteralSessionNewOtherSecond              = "session=new; other=second"
	replayLiteralSessionOldOtherSecond              = "session=old; other=second"
	replayLiteralSessionUpdated                     = "session=updated-"
	replayLiteralSharedStreamsOrigin                = "shared_streams_origin"
	replayLiteralSingleFile                         = "singleFile"
	replaySocketActionErrorFormat                   = "socket action: %w"
	replaySocketOperationErrorFormat                = "socket operation: %w"
	replayLiteralStartDate                          = "startDate"
	replayLiteralStreamAlbums                       = "stream_albums"
	replayLiteralStreamCount                        = "stream_count"
	replayLiteralStreamDownload                     = "stream_download"
	replayLiteralStreamGet                          = "stream_get"
	replayLiteralStreamPhotos                       = "stream_photos"
	replayLiteralSyncToken                          = "syncToken"
	replayLiteralSyntheticFailure                   = "synthetic failure"
	replayLiteralSyntheticUpload                    = "synthetic upload"
	replayLiteralSyntheticBuild                     = "synthetic-build"
	replayLiteralSyntheticDocument                  = "synthetic-document"
	replayLiteralSyntheticMastering                 = "synthetic-mastering"
	replayLiteralSyntheticStream0                   = "synthetic-stream-0"
	replayLiteralSyntheticTxt                       = "synthetic.txt"
	replayLiteralTimeZone                           = "time_zone"
	replayLiteralTotalBytes                         = "total_bytes"
	replayLiteralTrailing                           = "trailing"
	replayLiteralUpdateAttachment                   = "update_attachment"
	replayLiteralUpdateHashtag                      = "update_hashtag"
	replayLiteralUpdated                            = "updated-"
	replayLiteralUsedBytes                          = "used_bytes"
)
