package replay_test

// Independent literals preserve synthetic controls and Source spellings.
const (
	replayExpectedExampleInvalid                             = ".example.invalid"
	replayExpectedAlbumRecordBytes                           = "AAECAwQFBgcICQoLDA0ODw=="
	replayExpectedChangesResponseValidationFailed            = "Changes response validation failed"
	replayExpectedContentType                                = "Content-Type"
	replayExpectedPyiCloudAPIResponseException               = "PyiCloudAPIResponseException"
	replayExpectedPyiCloudServiceNotActivatedException       = "PyiCloudServiceNotActivatedException"
	replayExpectedReadTimeout                                = "ReadTimeout"
	replayExpectedSynthetic0                                 = "Synthetic 0"
	replayExpectedAccount                                    = "account-"
	replayExpectedAccountCountry                             = "account_country"
	replayExpectedAlbumDelete                                = "album_delete"
	replayExpectedAlbumRename                                = "album_rename"
	replayExpectedJSONMedia                                  = "application/json"
	replayExpectedBinaryMedia                                = "application/octet-stream"
	replayExpectedAttachmentsFor                             = "attachments_for"
	replayExpectedAuthAuthenticateCached                     = "auth-authenticate-cached"
	replayExpectedConnectionClose                            = "connection_close"
	replayExpectedContent                                    = "content-"
	replayExpectedCreateAlbum                                = "create_album"
	replayExpectedEncoding                                   = "encoding"
	replayExpectedEscapedPath                                = "escaped_path"
	replayExpectedExchanges                                  = "exchanges"
	replayExpectedRelatedCallFormat                          = "execute related reminder scenario: %w"
	replayExpectedExtraHeader                                = "extra_header"
	replayExpectedFileAssetURL                               = "fileAssetURL"
	replayExpectedFileSize                                   = "fileSize"
	replayExpectedFileAssetUrl                               = "file_asset_url"
	replayExpectedFixtures                                   = "fixtures"
	replayExpectedFixturesSyntheticHttp                      = "fixtures/synthetic/http"
	replayExpectedFixturesSyntheticHttpPhotosCreateAlbumJson = "fixtures/synthetic/http/photos-create-album.json"
	replayExpectedForceQuery                                 = "force_query"
	replayExpectedFragment                                   = "fragment"
	replayExpectedFullName                                   = "fullName"
	replayExpectedFullname                                   = "fullname"
	replayExpectedHeaderLength                               = "header_length"
	replayExpectedInvented                                   = "invented"
	replayExpectedNoOutcome                                  = "no_outcome"
	replayExpectedOperation                                  = "operation"
	replayExpectedOtherInvalid                               = "other.invalid"
	replayExpectedPhotosAddToAlbum                           = "photos-add-to-album"
	replayExpectedPhotosCreateAlbum                          = "photos-create-album"
	replayExpectedPhotosCreateFolder                         = "photos-create-folder"
	replayExpectedPhotosDeleteAlbum                          = "photos-delete-album"
	replayExpectedPhotosDeleteAsset                          = "photos-delete-asset"
	replayExpectedPhotosDeleteAssetRecordRejection           = "photos-delete-asset-record-rejection"
	replayExpectedPhotosFavoriteTrue                         = "photos-favorite-true"
	replayExpectedPhotosRenameAlbum                          = "photos-rename-album"
	replayExpectedPluginFields                               = "pluginFields"
	replayExpectedQueryOrder                                 = "query_order"
	replayExpectedRecurrenceRulesFor                         = "recurrence_rules_for"
	replayExpectedRepresentation                             = "representation"
	replayExpectedResOriginalFileSize                        = "resOriginalFileSize"
	replayExpectedSession                                    = "session="
	replayExpectedSessionUploaded                            = "session=uploaded-"
	replayExpectedSessionData                                = "session_data"
	replayExpectedSessionStateField                          = "session_token"
	replayExpectedCursorField                                = "sync_token"
	replayExpectedSynthetic                                  = "synthetic"
	replayExpectedSyntheticClient                            = "synthetic-client"
	replayExpectedTagsFor                                    = "tags_for"
	replayExpectedTrustedStateField                          = "trust_token"
	replayExpectedUnknownLength                              = "unknown_length"
	replayExpectedUserinfo                                   = "userinfo"
)
