package replay_test

const (
	nativeCloudKitDiscoveryFixture     = "auth-authenticate-cloudkit-discovery"
	nativePausedAuthenticationFixture  = "auth-authenticate-paused"
	nativeStaleTokenFixture            = "auth-authenticate-stale-token"
	nativeRefresh202Fixture            = "auth-authenticate-refresh-202"
	nativeEmptyHeadersFixture          = "auth-authenticate-empty-headers"
	nativeExplicitCookieFixture        = "auth-authenticate-explicit-cookie"
	nativeTermsRefusedFixture          = "auth-terms-refused"
	nativeBridgeSMSFallbackFixture     = "auth-bridge-sms-fallback"
	nativeRefreshAuthenticationFixture = "auth-authenticate-refresh"
	nativeUntrustedRefreshFixture      = "auth-authenticate-untrusted-refresh"
	nativeTokenRotationFixture         = "auth-token-cookie-rotation" //nolint:gosec // G101: replay scenario name.
	nativeValidation201Fixture         = "auth-authenticate-validation-201"
	nativeEmptyHeadersRefreshFixture   = "auth-authenticate-empty-headers-refresh"
	nativeQuotedCookieFixture          = "auth-authenticate-quoted-cookie"
	nativeQuotedCookieRotationFixture  = "auth-authenticate-quoted-cookie-rotation"
	nativeKeyDeviceID                  = "synthetic-device"
	nativeKeyDeviceName                = "Synthetic key"
	nativeKeyAcceptedFixture           = "auth-security-key-assertion-accepted"
	nativeKeyChallengeControl          = "challenge"
	nativeKeyOriginControl             = "origin"
	nativeKeyClientTypeControl         = "client type"
	nativeKeyCredentialControl         = "credential"
	nativeKeyCrossOriginControl        = "cross origin"
	nativeKeySignatureControl          = "empty signature"
	nativeKeyRPHashControl             = "rp hash"
	nativeKeyShortAuthenticatorControl = "short authenticator"
	nativeSRPEmptyContextControl       = "empty context"
	nativeSRPEmptySaltControl          = "empty salt"
	nativeSRPProtocolControl           = "unknown protocol"
	nativeSRPZeroIterationsControl     = "zero iterations"
	nativeSRPZeroServerControl         = "zero server"
	nativeLogoutDefaultFixture         = "auth-logout-default"
	nativePCSEnabledFixture            = "auth-pcs-enabled"
	nativePCSLaterConsentFixture       = "auth-pcs-consent-later"
	nativePCSFalseConsentFixture       = "auth-pcs-consent-false"
	nativePCSNullConsentFixture        = "auth-pcs-consent-null"
	nativePCSLaterCookiesFixture       = "auth-pcs-cookies-later"
	nativePCSExhaustedFixture          = "auth-pcs-retries-exhausted"
	nativeOneFactorFixture             = "auth-one-factor-service"
)

const (
	nativeValidateTwoFactorOperation = "validate_2fa_code"
	nativeRequestTwoFactorOperation  = "request_2fa_code"
	nativeMutationProbe              = "mutation-probe"
	nativeBridgeMutation             = "synthetic-mutation"
	nativeBridgeRotatedScnt          = "synthetic-rotated-scnt"
	nativeBridgeRotatedSession       = "synthetic-rotated-session"
	nativeBridgeRotatedTrust         = "synthetic-rotated-trust"
)
