// Package referenceconfig provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package referenceconfig

// Defines values for AcceptValue.
const (
	AnyAccept AcceptValue = "*/*"
)

// Valid indicates whether the value is a known member of the AcceptValue enum.
func (e AcceptValue) Valid() bool {
	switch e {
	case AnyAccept:
		return true
	default:
		return false
	}
}

// Defines values for BrowserUserAgent.
const (
	SafariUserAgent BrowserUserAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3.1 Safari/605.1.15"
)

// Valid indicates whether the value is a known member of the BrowserUserAgent enum.
func (e BrowserUserAgent) Valid() bool {
	switch e {
	case SafariUserAgent:
		return true
	default:
		return false
	}
}

// Defines values for ConnectionValue.
const (
	KeepAlive ConnectionValue = "keep-alive"
)

// Valid indicates whether the value is a known member of the ConnectionValue enum.
func (e ConnectionValue) Valid() bool {
	switch e {
	case KeepAlive:
		return true
	default:
		return false
	}
}

// Defines values for CookieJarMagic.
const (
	LWPCookies2 CookieJarMagic = "#LWP-Cookies-2.0"
)

// Valid indicates whether the value is a known member of the CookieJarMagic enum.
func (e CookieJarMagic) Valid() bool {
	switch e {
	case LWPCookies2:
		return true
	default:
		return false
	}
}

// Defines values for CookieRecordPrefix.
const (
	CookieRecord CookieRecordPrefix = "Set-Cookie3:"
)

// Valid indicates whether the value is a known member of the CookieRecordPrefix enum.
func (e CookieRecordPrefix) Valid() bool {
	switch e {
	case CookieRecord:
		return true
	default:
		return false
	}
}

// Defines values for EncodingValue.
const (
	GzipDeflate EncodingValue = "gzip, deflate"
)

// Valid indicates whether the value is a known member of the EncodingValue enum.
func (e EncodingValue) Valid() bool {
	switch e {
	case GzipDeflate:
		return true
	default:
		return false
	}
}

// Defines values for ExcludedCookieName.
const (
	DiscardFindMyCookie ExcludedCookieName = "X-APPLE-WEBAUTH-FMIP"
)

// Valid indicates whether the value is a known member of the ExcludedCookieName enum.
func (e ExcludedCookieName) Valid() bool {
	switch e {
	case DiscardFindMyCookie:
		return true
	default:
		return false
	}
}

// Defines values for HeaderName.
const (
	AcceptHeader     HeaderName = "Accept"
	ConnectionHeader HeaderName = "Connection"
	EncodingHeader   HeaderName = "Accept-Encoding"
	OriginHeader     HeaderName = "Origin"
	RefererHeader    HeaderName = "Referer"
	UserAgentHeader  HeaderName = "User-Agent"
)

// Valid indicates whether the value is a known member of the HeaderName enum.
func (e HeaderName) Valid() bool {
	switch e {
	case AcceptHeader:
		return true
	case ConnectionHeader:
		return true
	case EncodingHeader:
		return true
	case OriginHeader:
		return true
	case RefererHeader:
		return true
	case UserAgentHeader:
		return true
	default:
		return false
	}
}

// Defines values for HomeOrigin.
const (
	ChinaHome  HomeOrigin = "https://www.icloud.com.cn"
	GlobalHome HomeOrigin = "https://www.icloud.com"
)

// Valid indicates whether the value is a known member of the HomeOrigin enum.
func (e HomeOrigin) Valid() bool {
	switch e {
	case ChinaHome:
		return true
	case GlobalHome:
		return true
	default:
		return false
	}
}

// Defines values for RefererValue.
const (
	ChinaReferer  RefererValue = "https://www.icloud.com.cn/"
	GlobalReferer RefererValue = "https://www.icloud.com/"
)

// Valid indicates whether the value is a known member of the RefererValue enum.
func (e RefererValue) Valid() bool {
	switch e {
	case ChinaReferer:
		return true
	case GlobalReferer:
		return true
	default:
		return false
	}
}

// Defines values for SetupOrigin.
const (
	ChinaSetup  SetupOrigin = "https://setup.icloud.com.cn"
	GlobalSetup SetupOrigin = "https://setup.icloud.com"
)

// Valid indicates whether the value is a known member of the SetupOrigin enum.
func (e SetupOrigin) Valid() bool {
	switch e {
	case ChinaSetup:
		return true
	case GlobalSetup:
		return true
	default:
		return false
	}
}

// AcceptValue Reference default Accept header.
type AcceptValue string

// BrowserUserAgent User agent from the pinned reference browser profile.
type BrowserUserAgent string

// ConnectionValue Reference default persistent HTTP connection preference.
type ConnectionValue string

// CookieJarMagic Pinned reference persisted cookie file marker.
type CookieJarMagic string

// CookieRecordPrefix Prefix for each saved LWP cookie record.
type CookieRecordPrefix string

// EncodingValue Content encodings negotiated by the pinned Requests dependency.
type EncodingValue string

// ExcludedCookieName Source discards this cookie on import regardless of its scope.
type ExcludedCookieName string

// HeaderName Header names used by reference session construction.
type HeaderName string

// HomeOrigin Browser origins reconstructed for saved credentials.
type HomeOrigin string

// RefererValue Browser root referer including its trailing slash.
type RefererValue string

// SetupOrigin Setup origins used by the pinned reference login.
type SetupOrigin string
