package: accountapi
generate:
  models: true
  client: true
output: pkg/dependencies/webtransport/accountapi/client.gen.go
output-options:
  user-templates:
    client.tmpl: api/templates/http-request-builders.tmpl
    client-with-responses.tmpl: api/templates/http-response-parsers.tmpl
  nullable-type: true
import-mapping:
  ./account-models.openapi.yaml: github.com/portpowered/go-icloud/pkg/dependencymodels/account
