// Package sharedphotosapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package sharedphotosapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	externalRef2 "github.com/portpowered/go-icloud/pkg/dependencymodels/sharedphotos"
)

// Defines values for PhotosGetCurrentSyncToken.
const (
	PhotosGetCurrentSyncTokenTrue PhotosGetCurrentSyncToken = "True"
)

// Valid indicates whether the value is a known member of the PhotosGetCurrentSyncToken enum.
func (e PhotosGetCurrentSyncToken) Valid() bool {
	switch e {
	case PhotosGetCurrentSyncTokenTrue:
		return true
	default:
		return false
	}
}

// Defines values for PhotosRemapEnums.
const (
	PhotosRemapEnumsTrue PhotosRemapEnums = "True"
)

// Valid indicates whether the value is a known member of the PhotosRemapEnums enum.
func (e PhotosRemapEnums) Valid() bool {
	switch e {
	case PhotosRemapEnumsTrue:
		return true
	default:
		return false
	}
}

// Defines values for SharedCountParamsRemapEnums.
const (
	SharedCountParamsRemapEnumsTrue SharedCountParamsRemapEnums = "True"
)

// Valid indicates whether the value is a known member of the SharedCountParamsRemapEnums enum.
func (e SharedCountParamsRemapEnums) Valid() bool {
	switch e {
	case SharedCountParamsRemapEnumsTrue:
		return true
	default:
		return false
	}
}

// Defines values for SharedCountParamsGetCurrentSyncToken.
const (
	SharedCountParamsGetCurrentSyncTokenTrue SharedCountParamsGetCurrentSyncToken = "True"
)

// Valid indicates whether the value is a known member of the SharedCountParamsGetCurrentSyncToken enum.
func (e SharedCountParamsGetCurrentSyncToken) Valid() bool {
	switch e {
	case SharedCountParamsGetCurrentSyncTokenTrue:
		return true
	default:
		return false
	}
}

// Defines values for SharedAssetsParamsRemapEnums.
const (
	SharedAssetsParamsRemapEnumsTrue SharedAssetsParamsRemapEnums = "True"
)

// Valid indicates whether the value is a known member of the SharedAssetsParamsRemapEnums enum.
func (e SharedAssetsParamsRemapEnums) Valid() bool {
	switch e {
	case SharedAssetsParamsRemapEnumsTrue:
		return true
	default:
		return false
	}
}

// Defines values for SharedAssetsParamsGetCurrentSyncToken.
const (
	SharedAssetsParamsGetCurrentSyncTokenTrue SharedAssetsParamsGetCurrentSyncToken = "True"
)

// Valid indicates whether the value is a known member of the SharedAssetsParamsGetCurrentSyncToken enum.
func (e SharedAssetsParamsGetCurrentSyncToken) Valid() bool {
	switch e {
	case SharedAssetsParamsGetCurrentSyncTokenTrue:
		return true
	default:
		return false
	}
}

// Defines values for SharedAlbumsParamsRemapEnums.
const (
	SharedAlbumsParamsRemapEnumsTrue SharedAlbumsParamsRemapEnums = "True"
)

// Valid indicates whether the value is a known member of the SharedAlbumsParamsRemapEnums enum.
func (e SharedAlbumsParamsRemapEnums) Valid() bool {
	switch e {
	case SharedAlbumsParamsRemapEnumsTrue:
		return true
	default:
		return false
	}
}

// Defines values for SharedAlbumsParamsGetCurrentSyncToken.
const (
	SharedAlbumsParamsGetCurrentSyncTokenTrue SharedAlbumsParamsGetCurrentSyncToken = "True"
)

// Valid indicates whether the value is a known member of the SharedAlbumsParamsGetCurrentSyncToken enum.
func (e SharedAlbumsParamsGetCurrentSyncToken) Valid() bool {
	switch e {
	case SharedAlbumsParamsGetCurrentSyncTokenTrue:
		return true
	default:
		return false
	}
}

// PhotosAccept defines model for PhotosAccept.
type PhotosAccept = string

// PhotosAcceptEncoding defines model for PhotosAcceptEncoding.
type PhotosAcceptEncoding = string

// PhotosClientBuildNumber defines model for PhotosClientBuildNumber.
type PhotosClientBuildNumber = string

// PhotosClientId defines model for PhotosClientId.
type PhotosClientId = string

// PhotosClientMasteringNumber defines model for PhotosClientMasteringNumber.
type PhotosClientMasteringNumber = string

// PhotosConnection defines model for PhotosConnection.
type PhotosConnection = string

// PhotosContentType defines model for PhotosContentType.
type PhotosContentType = string

// PhotosCookie defines model for PhotosCookie.
type PhotosCookie = string

// PhotosDsid defines model for PhotosDsid.
type PhotosDsid = string

// PhotosGetCurrentSyncToken defines model for PhotosGetCurrentSyncToken.
type PhotosGetCurrentSyncToken string

// PhotosOrigin defines model for PhotosOrigin.
type PhotosOrigin = string

// PhotosReferer defines model for PhotosReferer.
type PhotosReferer = string

// PhotosRemapEnums defines model for PhotosRemapEnums.
type PhotosRemapEnums string

// PhotosUserAgent defines model for PhotosUserAgent.
type PhotosUserAgent = string

// SharedCountParams defines parameters for SharedCount.
type SharedCountParams struct {
	ClientId PhotosClientId `form:"clientId" json:"clientId"`
	Dsid     PhotosDsid     `form:"dsid" json:"dsid"`

	// RemapEnums Photos initialization forces this query control to the Python boolean text True.
	RemapEnums SharedCountParamsRemapEnums `form:"remapEnums" json:"remapEnums"`

	// GetCurrentSyncToken Photos initialization forces this query control to the Python boolean text True.
	GetCurrentSyncToken SharedCountParamsGetCurrentSyncToken `form:"getCurrentSyncToken" json:"getCurrentSyncToken"`

	// ClientBuildNumber Optional authentication client build parameter; preserve omission and the exact supplied value.
	ClientBuildNumber *PhotosClientBuildNumber `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`

	// ClientMasteringNumber Optional authentication client mastering parameter; preserve omission and the exact supplied value.
	ClientMasteringNumber *PhotosClientMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *PhotosAccept                `json:"Accept,omitempty"`
	ContentType           *PhotosContentType           `json:"Content-Type,omitempty"`
	Cookie                *PhotosCookie                `json:"Cookie,omitempty"`
	Origin                *PhotosOrigin                `json:"Origin,omitempty"`
	Referer               *PhotosReferer               `json:"Referer,omitempty"`
	UserAgent             *PhotosUserAgent             `json:"User-Agent,omitempty"`
	AcceptEncoding        *PhotosAcceptEncoding        `json:"Accept-Encoding,omitempty"`
	Connection            *PhotosConnection            `json:"Connection,omitempty"`
}

// SharedCountParamsRemapEnums defines parameters for SharedCount.
type SharedCountParamsRemapEnums string

// SharedCountParamsGetCurrentSyncToken defines parameters for SharedCount.
type SharedCountParamsGetCurrentSyncToken string

// SharedAssetsParams defines parameters for SharedAssets.
type SharedAssetsParams struct {
	ClientId PhotosClientId `form:"clientId" json:"clientId"`
	Dsid     PhotosDsid     `form:"dsid" json:"dsid"`

	// RemapEnums Photos initialization forces this query control to the Python boolean text True.
	RemapEnums SharedAssetsParamsRemapEnums `form:"remapEnums" json:"remapEnums"`

	// GetCurrentSyncToken Photos initialization forces this query control to the Python boolean text True.
	GetCurrentSyncToken SharedAssetsParamsGetCurrentSyncToken `form:"getCurrentSyncToken" json:"getCurrentSyncToken"`

	// ClientBuildNumber Optional authentication client build parameter; preserve omission and the exact supplied value.
	ClientBuildNumber *PhotosClientBuildNumber `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`

	// ClientMasteringNumber Optional authentication client mastering parameter; preserve omission and the exact supplied value.
	ClientMasteringNumber *PhotosClientMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *PhotosAccept                `json:"Accept,omitempty"`
	ContentType           *PhotosContentType           `json:"Content-Type,omitempty"`
	Cookie                *PhotosCookie                `json:"Cookie,omitempty"`
	Origin                *PhotosOrigin                `json:"Origin,omitempty"`
	Referer               *PhotosReferer               `json:"Referer,omitempty"`
	UserAgent             *PhotosUserAgent             `json:"User-Agent,omitempty"`
	AcceptEncoding        *PhotosAcceptEncoding        `json:"Accept-Encoding,omitempty"`
	Connection            *PhotosConnection            `json:"Connection,omitempty"`
}

// SharedAssetsParamsRemapEnums defines parameters for SharedAssets.
type SharedAssetsParamsRemapEnums string

// SharedAssetsParamsGetCurrentSyncToken defines parameters for SharedAssets.
type SharedAssetsParamsGetCurrentSyncToken string

// SharedAlbumsParams defines parameters for SharedAlbums.
type SharedAlbumsParams struct {
	ClientId PhotosClientId `form:"clientId" json:"clientId"`
	Dsid     PhotosDsid     `form:"dsid" json:"dsid"`

	// RemapEnums Photos initialization forces this query control to the Python boolean text True.
	RemapEnums SharedAlbumsParamsRemapEnums `form:"remapEnums" json:"remapEnums"`

	// GetCurrentSyncToken Photos initialization forces this query control to the Python boolean text True.
	GetCurrentSyncToken SharedAlbumsParamsGetCurrentSyncToken `form:"getCurrentSyncToken" json:"getCurrentSyncToken"`

	// ClientBuildNumber Optional authentication client build parameter; preserve omission and the exact supplied value.
	ClientBuildNumber *PhotosClientBuildNumber `form:"clientBuildNumber,omitempty" json:"clientBuildNumber,omitempty"`

	// ClientMasteringNumber Optional authentication client mastering parameter; preserve omission and the exact supplied value.
	ClientMasteringNumber *PhotosClientMasteringNumber `form:"clientMasteringNumber,omitempty" json:"clientMasteringNumber,omitempty"`
	Accept                *PhotosAccept                `json:"Accept,omitempty"`
	ContentType           *PhotosContentType           `json:"Content-Type,omitempty"`
	Cookie                *PhotosCookie                `json:"Cookie,omitempty"`
	Origin                *PhotosOrigin                `json:"Origin,omitempty"`
	Referer               *PhotosReferer               `json:"Referer,omitempty"`
	UserAgent             *PhotosUserAgent             `json:"User-Agent,omitempty"`
	AcceptEncoding        *PhotosAcceptEncoding        `json:"Accept-Encoding,omitempty"`
	Connection            *PhotosConnection            `json:"Connection,omitempty"`
}

// SharedAlbumsParamsRemapEnums defines parameters for SharedAlbums.
type SharedAlbumsParamsRemapEnums string

// SharedAlbumsParamsGetCurrentSyncToken defines parameters for SharedAlbums.
type SharedAlbumsParamsGetCurrentSyncToken string

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// SharedCountWithBody Read shared photo count
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /webgetassetcount (the `SharedCount` operationId).
	SharedCountWithBody(ctx context.Context, params *SharedCountParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SharedAssetsWithBody Read shared photo assets
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /webgetassets (the `SharedAssets` operationId).
	SharedAssetsWithBody(ctx context.Context, params *SharedAssetsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SharedAlbumsWithBody Read shared photo albums
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /{accountID}/sharedstreams/webgetalbumslist (the `SharedAlbums` operationId).
	SharedAlbumsWithBody(ctx context.Context, accountID string, params *SharedAlbumsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// SharedCountWithBody Read shared photo count
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /webgetassetcount (the `SharedCount` operationId).
func (c *Client) SharedCountWithBody(ctx context.Context, params *SharedCountParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSharedCountRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SharedAssetsWithBody Read shared photo assets
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /webgetassets (the `SharedAssets` operationId).
func (c *Client) SharedAssetsWithBody(ctx context.Context, params *SharedAssetsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSharedAssetsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SharedAlbumsWithBody Read shared photo albums
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /{accountID}/sharedstreams/webgetalbumslist (the `SharedAlbums` operationId).
func (c *Client) SharedAlbumsWithBody(ctx context.Context, accountID string, params *SharedAlbumsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSharedAlbumsRequestWithBody(c.Server, accountID, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSharedCountRequestWithBody constructs an http.Request for the SharedCount method, with any body, and a specified content type
func NewSharedCountRequestWithBody(server string, params *SharedCountParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/webgetassetcount")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "remapEnums", params.RemapEnums, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "getCurrentSyncToken", params.GetCurrentSyncToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.ContentType != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", *params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Content-Type", headerParam1)
		}

		if params.Cookie != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam2)
		}

		if params.Origin != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam3)
		}

		if params.Referer != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam4)
		}

		if params.UserAgent != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam5)
		}

		if params.AcceptEncoding != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam6)
		}

		if params.Connection != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam7)
		}

	}

	return req, nil
}

// NewSharedAssetsRequestWithBody constructs an http.Request for the SharedAssets method, with any body, and a specified content type
func NewSharedAssetsRequestWithBody(server string, params *SharedAssetsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/webgetassets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "remapEnums", params.RemapEnums, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "getCurrentSyncToken", params.GetCurrentSyncToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.ContentType != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", *params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Content-Type", headerParam1)
		}

		if params.Cookie != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam2)
		}

		if params.Origin != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam3)
		}

		if params.Referer != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam4)
		}

		if params.UserAgent != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam5)
		}

		if params.AcceptEncoding != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam6)
		}

		if params.Connection != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam7)
		}

	}

	return req, nil
}

// NewSharedAlbumsRequestWithBody constructs an http.Request for the SharedAlbums method, with any body, and a specified content type
func NewSharedAlbumsRequestWithBody(server string, accountID string, params *SharedAlbumsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "accountID", accountID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/sharedstreams/webgetalbumslist", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientId", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dsid", params.Dsid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "remapEnums", params.RemapEnums, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "getCurrentSyncToken", params.GetCurrentSyncToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.ClientBuildNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientBuildNumber", *params.ClientBuildNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ClientMasteringNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "clientMasteringNumber", *params.ClientMasteringNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

		if params.ContentType != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", *params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Content-Type", headerParam1)
		}

		if params.Cookie != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Cookie", *params.Cookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Cookie", headerParam2)
		}

		if params.Origin != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Origin", *params.Origin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Origin", headerParam3)
		}

		if params.Referer != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "Referer", *params.Referer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Referer", headerParam4)
		}

		if params.UserAgent != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", *params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("User-Agent", headerParam5)
		}

		if params.AcceptEncoding != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Accept-Encoding", *params.AcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept-Encoding", headerParam6)
		}

		if params.Connection != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "Connection", *params.Connection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Connection", headerParam7)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// SharedCountWithBodyWithResponse Read shared photo count
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /webgetassetcount (the `SharedCount` operationId).
	SharedCountWithBodyWithResponse(ctx context.Context, params *SharedCountParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SharedCountResponse, error)

	// SharedAssetsWithBodyWithResponse Read shared photo assets
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /webgetassets (the `SharedAssets` operationId).
	SharedAssetsWithBodyWithResponse(ctx context.Context, params *SharedAssetsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SharedAssetsResponse, error)

	// SharedAlbumsWithBodyWithResponse Read shared photo albums
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /{accountID}/sharedstreams/webgetalbumslist (the `SharedAlbums` operationId).
	SharedAlbumsWithBodyWithResponse(ctx context.Context, accountID string, params *SharedAlbumsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SharedAlbumsResponse, error)
}

type SharedCountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *externalRef2.SharedCountResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SharedCountResponse) GetJSON200() *externalRef2.SharedCountResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r SharedCountResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SharedCountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SharedCountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SharedCountResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SharedAssetsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *externalRef2.SharedRecordsResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SharedAssetsResponse) GetJSON200() *externalRef2.SharedRecordsResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r SharedAssetsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SharedAssetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SharedAssetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SharedAssetsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SharedAlbumsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *externalRef2.SharedAlbumsResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SharedAlbumsResponse) GetJSON200() *externalRef2.SharedAlbumsResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r SharedAlbumsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SharedAlbumsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SharedAlbumsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SharedAlbumsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SharedCountWithBodyWithResponse Read shared photo count
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /webgetassetcount (the `SharedCount` operationId).
func (c *ClientWithResponses) SharedCountWithBodyWithResponse(ctx context.Context, params *SharedCountParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SharedCountResponse, error) {
	rsp, err := c.SharedCountWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSharedCountResponse(rsp)
}

// SharedAssetsWithBodyWithResponse Read shared photo assets
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /webgetassets (the `SharedAssets` operationId).
func (c *ClientWithResponses) SharedAssetsWithBodyWithResponse(ctx context.Context, params *SharedAssetsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SharedAssetsResponse, error) {
	rsp, err := c.SharedAssetsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSharedAssetsResponse(rsp)
}

// SharedAlbumsWithBodyWithResponse Read shared photo albums
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /{accountID}/sharedstreams/webgetalbumslist (the `SharedAlbums` operationId).
func (c *ClientWithResponses) SharedAlbumsWithBodyWithResponse(ctx context.Context, accountID string, params *SharedAlbumsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SharedAlbumsResponse, error) {
	rsp, err := c.SharedAlbumsWithBody(ctx, accountID, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSharedAlbumsResponse(rsp)
}

// ParseSharedCountResponse parses an HTTP response from a SharedCountWithResponse call
func ParseSharedCountResponse(rsp *http.Response) (*SharedCountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SharedCountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef2.SharedCountResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSharedAssetsResponse parses an HTTP response from a SharedAssetsWithResponse call
func ParseSharedAssetsResponse(rsp *http.Response) (*SharedAssetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SharedAssetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef2.SharedRecordsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSharedAlbumsResponse parses an HTTP response from a SharedAlbumsWithResponse call
func ParseSharedAlbumsResponse(rsp *http.Response) (*SharedAlbumsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SharedAlbumsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef2.SharedAlbumsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
