// Package icloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package icloud

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/nullable"
)

// Defines values for ErrorKind.
const (
	Canceled        ErrorKind = "canceled"
	Configuration   ErrorKind = "configuration"
	Forbidden       ErrorKind = "forbidden"
	InvalidResponse ErrorKind = "invalid-response"
	NotFound        ErrorKind = "not-found"
	Provider        ErrorKind = "provider"
	RateLimited     ErrorKind = "rate-limited"
	Timeout         ErrorKind = "timeout"
	Transport       ErrorKind = "transport"
	Unauthorized    ErrorKind = "unauthorized"
	Unavailable     ErrorKind = "unavailable"
)

// Valid indicates whether the value is a known member of the ErrorKind enum.
func (e ErrorKind) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Configuration:
		return true
	case Forbidden:
		return true
	case InvalidResponse:
		return true
	case NotFound:
		return true
	case Provider:
		return true
	case RateLimited:
		return true
	case Timeout:
		return true
	case Transport:
		return true
	case Unauthorized:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// AccountDevice Known device metadata fields are optional; future provider fields are preserved.
type AccountDevice struct {
	Imei *string `json:"imei,omitempty"`

	// LatestBackup Provider backup timestamp text; no timestamp format is inferred.
	LatestBackup         *string `json:"latestBackup,omitempty"`
	Model                *string `json:"model,omitempty"`
	ModelDisplayName     *string `json:"modelDisplayName,omitempty"`
	ModelLargePhotoURL1x *string `json:"modelLargePhotoURL1x,omitempty"`
	ModelLargePhotoURL2x *string `json:"modelLargePhotoURL2x,omitempty"`
	ModelSmallPhotoURL1x *string `json:"modelSmallPhotoURL1x,omitempty"`
	ModelSmallPhotoURL2x *string `json:"modelSmallPhotoURL2x,omitempty"`
	Name                 *string `json:"name,omitempty"`
	OsVersion            *string `json:"osVersion,omitempty"`

	// PaymentMethods Associated payment-method identifiers.
	PaymentMethods       *[]string                   `json:"paymentMethods,omitempty"`
	SerialNumber         *string                     `json:"serialNumber,omitempty"`
	Udid                 *string                     `json:"udid,omitempty"`
	AdditionalProperties map[string]UnknownJSONValue `json:"-"`
}

// AccountFamilyMember defines model for AccountFamilyMember.
type AccountFamilyMember struct {
	// AgeClassification An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	AgeClassification   nullable.Nullable[NullableJSONValue] `json:"ageClassification,omitempty"`
	AppleId             nullable.Nullable[string]            `json:"appleId,omitempty"`
	AppleIdForPurchases nullable.Nullable[string]            `json:"appleIdForPurchases,omitempty"`
	Dsid                nullable.Nullable[string]            `json:"dsid,omitempty"`

	// DsidForPurchases An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	DsidForPurchases nullable.Nullable[NullableJSONValue] `json:"dsidForPurchases,omitempty"`

	// FamilyId An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	FamilyId  nullable.Nullable[NullableJSONValue] `json:"familyId,omitempty"`
	FirstName nullable.Nullable[string]            `json:"firstName,omitempty"`
	FullName  nullable.Nullable[string]            `json:"fullName,omitempty"`

	// HasAskToBuyEnabled An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	HasAskToBuyEnabled nullable.Nullable[NullableJSONValue] `json:"hasAskToBuyEnabled,omitempty"`

	// HasParentalPrivileges An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	HasParentalPrivileges nullable.Nullable[NullableJSONValue] `json:"hasParentalPrivileges,omitempty"`

	// HasScreenTimeEnabled An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	HasScreenTimeEnabled nullable.Nullable[NullableJSONValue] `json:"hasScreenTimeEnabled,omitempty"`

	// HasShareMyLocationEnabled An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	HasShareMyLocationEnabled nullable.Nullable[NullableJSONValue] `json:"hasShareMyLocationEnabled,omitempty"`

	// HasSharePurchasesEnabled An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	HasSharePurchasesEnabled nullable.Nullable[NullableJSONValue] `json:"hasSharePurchasesEnabled,omitempty"`
	LastName                 nullable.Nullable[string]            `json:"lastName,omitempty"`
	OriginalInvitationEmail  nullable.Nullable[string]            `json:"originalInvitationEmail,omitempty"`

	// ShareMyLocationEnabledFamilyMembers An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
	ShareMyLocationEnabledFamilyMembers nullable.Nullable[NullableJSONValue] `json:"shareMyLocationEnabledFamilyMembers,omitempty"`
	AdditionalProperties                map[string]UnknownJSONValue          `json:"-"`
}

// AccountMediaUsage defines model for AccountMediaUsage.
type AccountMediaUsage struct {
	// DisplayColor Provider display color text; no encoding is inferred.
	DisplayColor *string `json:"displayColor,omitempty"`
	DisplayLabel *string `json:"displayLabel,omitempty"`
	MediaKey     string  `json:"mediaKey"`

	// UsageInBytes Storage used by this media category in bytes.
	UsageInBytes         *int64                      `json:"usageInBytes,omitempty"`
	AdditionalProperties map[string]UnknownJSONValue `json:"-"`
}

// AccountMetadata Additional uninterpreted account-level provider fields; nulls and original JSON numbers remain intact.
type AccountMetadata map[string]UnknownJSONValue

// AccountPaymentMethod defines model for AccountPaymentMethod.
type AccountPaymentMethod struct {
	BalanceStatus        *string                     `json:"balanceStatus,omitempty"`
	Id                   *string                     `json:"id,omitempty"`
	IsCarKey             *bool                       `json:"isCarKey,omitempty"`
	LastFourDigits       *string                     `json:"lastFourDigits,omitempty"`
	SuspensionReason     *string                     `json:"suspensionReason,omitempty"`
	Type                 *string                     `json:"type,omitempty"`
	AdditionalProperties map[string]UnknownJSONValue `json:"-"`
}

// AccountQuota defines model for AccountQuota.
type AccountQuota struct {
	AlmostFull           *bool                       `json:"almost-full,omitempty"`
	HaveMaxQuotaTier     *bool                       `json:"haveMaxQuotaTier,omitempty"`
	OverQuota            *bool                       `json:"overQuota,omitempty"`
	PaidQuota            *bool                       `json:"paidQuota,omitempty"`
	AdditionalProperties map[string]UnknownJSONValue `json:"-"`
}

// AccountStorageUsage defines model for AccountStorageUsage.
type AccountStorageUsage struct {
	// CommerceStorageInBytes Provider commerce storage in bytes.
	CommerceStorageInBytes *int64 `json:"commerceStorageInBytes,omitempty"`

	// CompStorageInBytes Provider comp storage in bytes.
	CompStorageInBytes *int64 `json:"compStorageInBytes,omitempty"`

	// TotalStorageInBytes Total storage in bytes; used storage may exceed quota.
	TotalStorageInBytes int64 `json:"totalStorageInBytes"`

	// UsedStorageInBytes Used storage in bytes.
	UsedStorageInBytes   int64                       `json:"usedStorageInBytes"`
	AdditionalProperties map[string]UnknownJSONValue `json:"-"`
}

// AuthContext Caller-owned account identity and web authentication headers. The reusable client never saves this state.
type AuthContext struct {
	// AccountID Authenticated account identifier returned by login.
	AccountID string `json:"accountID"`

	// AccountServiceURL HTTPS account origin returned by authenticated service discovery.
	AccountServiceURL string `json:"accountServiceURL"`

	// ChinaMainland Authenticated account region; true selects the mainland China subscription gateway.
	ChinaMainland *bool `json:"chinaMainland,omitempty"`

	// ClientBuildNumber Optional build parameter from the authentication context; omission remains omission.
	ClientBuildNumber *string `json:"clientBuildNumber,omitempty"`

	// ClientID Client identifier reused by this account session.
	ClientID string `json:"clientID"`

	// ClientMasteringNumber Optional mastering parameter from the authentication context; omission remains omission.
	ClientMasteringNumber *string `json:"clientMasteringNumber,omitempty"`

	// Headers Account-specific cookie and web headers; an absent Accept value defaults to the reference wildcard.
	Headers []Header `json:"headers"`
}

// ErrorKind Inspectable client failure class; errors preserve their cause separately from their safe display message.
type ErrorKind string

// GetAccountDevicesRequest Example: {"auth":{"accountID":"synthetic-account","accountServiceURL":"https://account.example.invalid","clientID":"synthetic-client","headers":[]}}
type GetAccountDevicesRequest struct {
	// Auth Caller-owned account identity and web authentication headers. The reusable client never saves this state.
	Auth AuthContext `json:"auth"`
}

// GetAccountDevicesResult Fresh account devices and payment-method details. Empty devices are successful; no shared cache is used.
//
// Example: {"additionalMetadata":{},"devices":[{"modelDisplayName":"Synthetic Model","name":"synthetic-device"}],"metadata":{"headers":[],"statusCode":200},"paymentMethods":[]}
type GetAccountDevicesResult struct {
	// AdditionalMetadata Additional uninterpreted account-level provider fields; nulls and original JSON numbers remain intact.
	AdditionalMetadata AccountMetadata `json:"additionalMetadata"`
	Devices            []AccountDevice `json:"devices"`

	// Metadata Response status and headers, including Set-Cookie values for caller-owned session updates.
	Metadata       ResponseMetadata       `json:"metadata"`
	PaymentMethods []AccountPaymentMethod `json:"paymentMethods"`
}

// GetAccountFamilyRequest Example: {"auth":{"accountID":"synthetic-account","accountServiceURL":"https://account.example.invalid","clientID":"synthetic-client","headers":[]}}
type GetAccountFamilyRequest struct {
	// Auth Caller-owned account identity and web authentication headers. The reusable client never saves this state.
	Auth AuthContext `json:"auth"`
}

// GetAccountFamilyResult Fresh family records; an omitted family list is successful and empty.
//
// Example: {"additionalMetadata":{},"members":[],"metadata":{"headers":[],"statusCode":200}}
type GetAccountFamilyResult struct {
	// AdditionalMetadata Additional uninterpreted account-level provider fields; nulls and original JSON numbers remain intact.
	AdditionalMetadata AccountMetadata       `json:"additionalMetadata"`
	Members            []AccountFamilyMember `json:"members"`

	// Metadata Response status and headers, including Set-Cookie values for caller-owned session updates.
	Metadata ResponseMetadata `json:"metadata"`
}

// GetAccountMemberPhotoRequest Example: {"auth":{"accountID":"synthetic-account","accountServiceURL":"https://account.example.invalid","clientID":"synthetic-client","headers":[]},"memberID":"synthetic-member"}
type GetAccountMemberPhotoRequest struct {
	// Auth Caller-owned account identity and web authentication headers. The reusable client never saves this state.
	Auth AuthContext `json:"auth"`

	// MemberID Member DSID returned by GetAccountFamily; no complete member object is needed.
	MemberID string `json:"memberID"`
}

// GetAccountMemberPhotoResult Exact member-photo bytes, including an empty successful body, and their HTTP metadata.
//
// Example: {"content":"","metadata":{"headers":[],"statusCode":200}}
type GetAccountMemberPhotoResult struct {
	// Content Exact response bytes; do not infer an image format from the provider label.
	Content []byte `json:"content"`

	// Metadata Response status and headers, including Set-Cookie values for caller-owned session updates.
	Metadata ResponseMetadata `json:"metadata"`
}

// GetAccountPlanSummaryRequest Example: {"auth":{"accountID":"synthetic-account","accountServiceURL":"https://account.example.invalid","chinaMainland":false,"clientID":"synthetic-client","headers":[]}}
type GetAccountPlanSummaryRequest struct {
	// Auth Caller-owned account identity and web authentication headers. The reusable client never saves this state.
	Auth AuthContext `json:"auth"`
}

// GetAccountPlanSummaryResult Opaque subscription JSON; no unobserved plan fields are inferred.
//
// Example: {"metadata":{"headers":[],"statusCode":200},"summary":{}}
type GetAccountPlanSummaryResult struct {
	// Metadata Response status and headers, including Set-Cookie values for caller-owned session updates.
	Metadata ResponseMetadata `json:"metadata"`

	// Summary Uninterpreted provider metadata, preserved as its original JSON value; its shape is genuinely unknown.
	Summary UnknownJSONValue `json:"summary"`
}

// GetAccountStorageRequest Example: {"auth":{"accountID":"synthetic-account","accountServiceURL":"https://account.example.invalid","clientID":"synthetic-client","headers":[]}}
type GetAccountStorageRequest struct {
	// Auth Caller-owned account identity and web authentication headers. The reusable client never saves this state.
	Auth AuthContext `json:"auth"`
}

// GetAccountStorageResult Fresh storage usage and available quota/media metadata. Byte counts remain absolute, including zero totals and usage above quota.
//
// Example: {"additionalMetadata":{},"media":[],"metadata":{"headers":[],"statusCode":200},"usage":{"totalStorageInBytes":100,"usedStorageInBytes":15}}
type GetAccountStorageResult struct {
	// AdditionalMetadata Additional uninterpreted account-level provider fields; nulls and original JSON numbers remain intact.
	AdditionalMetadata AccountMetadata     `json:"additionalMetadata"`
	Media              []AccountMediaUsage `json:"media"`

	// Metadata Response status and headers, including Set-Cookie values for caller-owned session updates.
	Metadata ResponseMetadata    `json:"metadata"`
	Quota    *AccountQuota       `json:"quota,omitempty"`
	Usage    AccountStorageUsage `json:"usage"`
}

// Header One HTTP response or caller-owned authentication header value; repeated headers remain separate entries.
type Header struct {
	// Name Header name.
	Name string `json:"name"`

	// Value Header value; authentication values may contain secrets.
	Value string `json:"value"`
}

// NullableJSONValue An uninterpreted named provider value; distinguish omitted values from explicit JSON null.
type NullableJSONValue = json.RawMessage

// ResponseMetadata Response status and headers, including Set-Cookie values for caller-owned session updates.
type ResponseMetadata struct {
	// Headers Header entries sorted by name; repeated values retain order within each name.
	Headers []Header `json:"headers"`

	// StatusCode Provider HTTP response status.
	StatusCode int `json:"statusCode"`
}

// UnknownJSONValue Uninterpreted provider metadata, preserved as its original JSON value; its shape is genuinely unknown.
type UnknownJSONValue = json.RawMessage

// Getter for additional properties for AccountDevice. Returns the specified
// element and whether it was found
func (a AccountDevice) Get(fieldName string) (value UnknownJSONValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AccountDevice
func (a *AccountDevice) Set(fieldName string, value UnknownJSONValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AccountDevice to handle AdditionalProperties
func (a *AccountDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["imei"]; found {
		err = json.Unmarshal(raw, &a.Imei)
		if err != nil {
			return fmt.Errorf("error reading 'imei': %w", err)
		}
		delete(object, "imei")
	}

	if raw, found := object["latestBackup"]; found {
		err = json.Unmarshal(raw, &a.LatestBackup)
		if err != nil {
			return fmt.Errorf("error reading 'latestBackup': %w", err)
		}
		delete(object, "latestBackup")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["modelDisplayName"]; found {
		err = json.Unmarshal(raw, &a.ModelDisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'modelDisplayName': %w", err)
		}
		delete(object, "modelDisplayName")
	}

	if raw, found := object["modelLargePhotoURL1x"]; found {
		err = json.Unmarshal(raw, &a.ModelLargePhotoURL1x)
		if err != nil {
			return fmt.Errorf("error reading 'modelLargePhotoURL1x': %w", err)
		}
		delete(object, "modelLargePhotoURL1x")
	}

	if raw, found := object["modelLargePhotoURL2x"]; found {
		err = json.Unmarshal(raw, &a.ModelLargePhotoURL2x)
		if err != nil {
			return fmt.Errorf("error reading 'modelLargePhotoURL2x': %w", err)
		}
		delete(object, "modelLargePhotoURL2x")
	}

	if raw, found := object["modelSmallPhotoURL1x"]; found {
		err = json.Unmarshal(raw, &a.ModelSmallPhotoURL1x)
		if err != nil {
			return fmt.Errorf("error reading 'modelSmallPhotoURL1x': %w", err)
		}
		delete(object, "modelSmallPhotoURL1x")
	}

	if raw, found := object["modelSmallPhotoURL2x"]; found {
		err = json.Unmarshal(raw, &a.ModelSmallPhotoURL2x)
		if err != nil {
			return fmt.Errorf("error reading 'modelSmallPhotoURL2x': %w", err)
		}
		delete(object, "modelSmallPhotoURL2x")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["osVersion"]; found {
		err = json.Unmarshal(raw, &a.OsVersion)
		if err != nil {
			return fmt.Errorf("error reading 'osVersion': %w", err)
		}
		delete(object, "osVersion")
	}

	if raw, found := object["paymentMethods"]; found {
		err = json.Unmarshal(raw, &a.PaymentMethods)
		if err != nil {
			return fmt.Errorf("error reading 'paymentMethods': %w", err)
		}
		delete(object, "paymentMethods")
	}

	if raw, found := object["serialNumber"]; found {
		err = json.Unmarshal(raw, &a.SerialNumber)
		if err != nil {
			return fmt.Errorf("error reading 'serialNumber': %w", err)
		}
		delete(object, "serialNumber")
	}

	if raw, found := object["udid"]; found {
		err = json.Unmarshal(raw, &a.Udid)
		if err != nil {
			return fmt.Errorf("error reading 'udid': %w", err)
		}
		delete(object, "udid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
		for fieldName, fieldBuf := range object {
			var fieldVal UnknownJSONValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AccountDevice to handle AdditionalProperties
func (a AccountDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Imei != nil {
		object["imei"], err = json.Marshal(a.Imei)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'imei': %w", err)
		}
	}

	if a.LatestBackup != nil {
		object["latestBackup"], err = json.Marshal(a.LatestBackup)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'latestBackup': %w", err)
		}
	}

	if a.Model != nil {
		object["model"], err = json.Marshal(a.Model)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'model': %w", err)
		}
	}

	if a.ModelDisplayName != nil {
		object["modelDisplayName"], err = json.Marshal(a.ModelDisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelDisplayName': %w", err)
		}
	}

	if a.ModelLargePhotoURL1x != nil {
		object["modelLargePhotoURL1x"], err = json.Marshal(a.ModelLargePhotoURL1x)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelLargePhotoURL1x': %w", err)
		}
	}

	if a.ModelLargePhotoURL2x != nil {
		object["modelLargePhotoURL2x"], err = json.Marshal(a.ModelLargePhotoURL2x)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelLargePhotoURL2x': %w", err)
		}
	}

	if a.ModelSmallPhotoURL1x != nil {
		object["modelSmallPhotoURL1x"], err = json.Marshal(a.ModelSmallPhotoURL1x)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelSmallPhotoURL1x': %w", err)
		}
	}

	if a.ModelSmallPhotoURL2x != nil {
		object["modelSmallPhotoURL2x"], err = json.Marshal(a.ModelSmallPhotoURL2x)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelSmallPhotoURL2x': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.OsVersion != nil {
		object["osVersion"], err = json.Marshal(a.OsVersion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'osVersion': %w", err)
		}
	}

	if a.PaymentMethods != nil {
		object["paymentMethods"], err = json.Marshal(a.PaymentMethods)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'paymentMethods': %w", err)
		}
	}

	if a.SerialNumber != nil {
		object["serialNumber"], err = json.Marshal(a.SerialNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'serialNumber': %w", err)
		}
	}

	if a.Udid != nil {
		object["udid"], err = json.Marshal(a.Udid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'udid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for AccountFamilyMember. Returns the specified
// element and whether it was found
func (a AccountFamilyMember) Get(fieldName string) (value UnknownJSONValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AccountFamilyMember
func (a *AccountFamilyMember) Set(fieldName string, value UnknownJSONValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AccountFamilyMember to handle AdditionalProperties
func (a *AccountFamilyMember) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ageClassification"]; found {
		err = json.Unmarshal(raw, &a.AgeClassification)
		if err != nil {
			return fmt.Errorf("error reading 'ageClassification': %w", err)
		}
		delete(object, "ageClassification")
	}

	if raw, found := object["appleId"]; found {
		err = json.Unmarshal(raw, &a.AppleId)
		if err != nil {
			return fmt.Errorf("error reading 'appleId': %w", err)
		}
		delete(object, "appleId")
	}

	if raw, found := object["appleIdForPurchases"]; found {
		err = json.Unmarshal(raw, &a.AppleIdForPurchases)
		if err != nil {
			return fmt.Errorf("error reading 'appleIdForPurchases': %w", err)
		}
		delete(object, "appleIdForPurchases")
	}

	if raw, found := object["dsid"]; found {
		err = json.Unmarshal(raw, &a.Dsid)
		if err != nil {
			return fmt.Errorf("error reading 'dsid': %w", err)
		}
		delete(object, "dsid")
	}

	if raw, found := object["dsidForPurchases"]; found {
		err = json.Unmarshal(raw, &a.DsidForPurchases)
		if err != nil {
			return fmt.Errorf("error reading 'dsidForPurchases': %w", err)
		}
		delete(object, "dsidForPurchases")
	}

	if raw, found := object["familyId"]; found {
		err = json.Unmarshal(raw, &a.FamilyId)
		if err != nil {
			return fmt.Errorf("error reading 'familyId': %w", err)
		}
		delete(object, "familyId")
	}

	if raw, found := object["firstName"]; found {
		err = json.Unmarshal(raw, &a.FirstName)
		if err != nil {
			return fmt.Errorf("error reading 'firstName': %w", err)
		}
		delete(object, "firstName")
	}

	if raw, found := object["fullName"]; found {
		err = json.Unmarshal(raw, &a.FullName)
		if err != nil {
			return fmt.Errorf("error reading 'fullName': %w", err)
		}
		delete(object, "fullName")
	}

	if raw, found := object["hasAskToBuyEnabled"]; found {
		err = json.Unmarshal(raw, &a.HasAskToBuyEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'hasAskToBuyEnabled': %w", err)
		}
		delete(object, "hasAskToBuyEnabled")
	}

	if raw, found := object["hasParentalPrivileges"]; found {
		err = json.Unmarshal(raw, &a.HasParentalPrivileges)
		if err != nil {
			return fmt.Errorf("error reading 'hasParentalPrivileges': %w", err)
		}
		delete(object, "hasParentalPrivileges")
	}

	if raw, found := object["hasScreenTimeEnabled"]; found {
		err = json.Unmarshal(raw, &a.HasScreenTimeEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'hasScreenTimeEnabled': %w", err)
		}
		delete(object, "hasScreenTimeEnabled")
	}

	if raw, found := object["hasShareMyLocationEnabled"]; found {
		err = json.Unmarshal(raw, &a.HasShareMyLocationEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'hasShareMyLocationEnabled': %w", err)
		}
		delete(object, "hasShareMyLocationEnabled")
	}

	if raw, found := object["hasSharePurchasesEnabled"]; found {
		err = json.Unmarshal(raw, &a.HasSharePurchasesEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'hasSharePurchasesEnabled': %w", err)
		}
		delete(object, "hasSharePurchasesEnabled")
	}

	if raw, found := object["lastName"]; found {
		err = json.Unmarshal(raw, &a.LastName)
		if err != nil {
			return fmt.Errorf("error reading 'lastName': %w", err)
		}
		delete(object, "lastName")
	}

	if raw, found := object["originalInvitationEmail"]; found {
		err = json.Unmarshal(raw, &a.OriginalInvitationEmail)
		if err != nil {
			return fmt.Errorf("error reading 'originalInvitationEmail': %w", err)
		}
		delete(object, "originalInvitationEmail")
	}

	if raw, found := object["shareMyLocationEnabledFamilyMembers"]; found {
		err = json.Unmarshal(raw, &a.ShareMyLocationEnabledFamilyMembers)
		if err != nil {
			return fmt.Errorf("error reading 'shareMyLocationEnabledFamilyMembers': %w", err)
		}
		delete(object, "shareMyLocationEnabledFamilyMembers")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
		for fieldName, fieldBuf := range object {
			var fieldVal UnknownJSONValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AccountFamilyMember to handle AdditionalProperties
func (a AccountFamilyMember) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AgeClassification != nil {
		object["ageClassification"], err = json.Marshal(a.AgeClassification)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ageClassification': %w", err)
		}
	}

	if a.AppleId != nil {
		object["appleId"], err = json.Marshal(a.AppleId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'appleId': %w", err)
		}
	}

	if a.AppleIdForPurchases != nil {
		object["appleIdForPurchases"], err = json.Marshal(a.AppleIdForPurchases)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'appleIdForPurchases': %w", err)
		}
	}

	if a.Dsid != nil {
		object["dsid"], err = json.Marshal(a.Dsid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dsid': %w", err)
		}
	}

	if a.DsidForPurchases != nil {
		object["dsidForPurchases"], err = json.Marshal(a.DsidForPurchases)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dsidForPurchases': %w", err)
		}
	}

	if a.FamilyId != nil {
		object["familyId"], err = json.Marshal(a.FamilyId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'familyId': %w", err)
		}
	}

	if a.FirstName != nil {
		object["firstName"], err = json.Marshal(a.FirstName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'firstName': %w", err)
		}
	}

	if a.FullName != nil {
		object["fullName"], err = json.Marshal(a.FullName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fullName': %w", err)
		}
	}

	if a.HasAskToBuyEnabled != nil {
		object["hasAskToBuyEnabled"], err = json.Marshal(a.HasAskToBuyEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hasAskToBuyEnabled': %w", err)
		}
	}

	if a.HasParentalPrivileges != nil {
		object["hasParentalPrivileges"], err = json.Marshal(a.HasParentalPrivileges)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hasParentalPrivileges': %w", err)
		}
	}

	if a.HasScreenTimeEnabled != nil {
		object["hasScreenTimeEnabled"], err = json.Marshal(a.HasScreenTimeEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hasScreenTimeEnabled': %w", err)
		}
	}

	if a.HasShareMyLocationEnabled != nil {
		object["hasShareMyLocationEnabled"], err = json.Marshal(a.HasShareMyLocationEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hasShareMyLocationEnabled': %w", err)
		}
	}

	if a.HasSharePurchasesEnabled != nil {
		object["hasSharePurchasesEnabled"], err = json.Marshal(a.HasSharePurchasesEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hasSharePurchasesEnabled': %w", err)
		}
	}

	if a.LastName != nil {
		object["lastName"], err = json.Marshal(a.LastName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lastName': %w", err)
		}
	}

	if a.OriginalInvitationEmail != nil {
		object["originalInvitationEmail"], err = json.Marshal(a.OriginalInvitationEmail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'originalInvitationEmail': %w", err)
		}
	}

	if a.ShareMyLocationEnabledFamilyMembers != nil {
		object["shareMyLocationEnabledFamilyMembers"], err = json.Marshal(a.ShareMyLocationEnabledFamilyMembers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'shareMyLocationEnabledFamilyMembers': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for AccountMediaUsage. Returns the specified
// element and whether it was found
func (a AccountMediaUsage) Get(fieldName string) (value UnknownJSONValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AccountMediaUsage
func (a *AccountMediaUsage) Set(fieldName string, value UnknownJSONValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AccountMediaUsage to handle AdditionalProperties
func (a *AccountMediaUsage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["displayColor"]; found {
		err = json.Unmarshal(raw, &a.DisplayColor)
		if err != nil {
			return fmt.Errorf("error reading 'displayColor': %w", err)
		}
		delete(object, "displayColor")
	}

	if raw, found := object["displayLabel"]; found {
		err = json.Unmarshal(raw, &a.DisplayLabel)
		if err != nil {
			return fmt.Errorf("error reading 'displayLabel': %w", err)
		}
		delete(object, "displayLabel")
	}

	if raw, found := object["mediaKey"]; found {
		err = json.Unmarshal(raw, &a.MediaKey)
		if err != nil {
			return fmt.Errorf("error reading 'mediaKey': %w", err)
		}
		delete(object, "mediaKey")
	}

	if raw, found := object["usageInBytes"]; found {
		err = json.Unmarshal(raw, &a.UsageInBytes)
		if err != nil {
			return fmt.Errorf("error reading 'usageInBytes': %w", err)
		}
		delete(object, "usageInBytes")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
		for fieldName, fieldBuf := range object {
			var fieldVal UnknownJSONValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AccountMediaUsage to handle AdditionalProperties
func (a AccountMediaUsage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DisplayColor != nil {
		object["displayColor"], err = json.Marshal(a.DisplayColor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'displayColor': %w", err)
		}
	}

	if a.DisplayLabel != nil {
		object["displayLabel"], err = json.Marshal(a.DisplayLabel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'displayLabel': %w", err)
		}
	}

	object["mediaKey"], err = json.Marshal(a.MediaKey)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mediaKey': %w", err)
	}

	if a.UsageInBytes != nil {
		object["usageInBytes"], err = json.Marshal(a.UsageInBytes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'usageInBytes': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for AccountPaymentMethod. Returns the specified
// element and whether it was found
func (a AccountPaymentMethod) Get(fieldName string) (value UnknownJSONValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AccountPaymentMethod
func (a *AccountPaymentMethod) Set(fieldName string, value UnknownJSONValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AccountPaymentMethod to handle AdditionalProperties
func (a *AccountPaymentMethod) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["balanceStatus"]; found {
		err = json.Unmarshal(raw, &a.BalanceStatus)
		if err != nil {
			return fmt.Errorf("error reading 'balanceStatus': %w", err)
		}
		delete(object, "balanceStatus")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["isCarKey"]; found {
		err = json.Unmarshal(raw, &a.IsCarKey)
		if err != nil {
			return fmt.Errorf("error reading 'isCarKey': %w", err)
		}
		delete(object, "isCarKey")
	}

	if raw, found := object["lastFourDigits"]; found {
		err = json.Unmarshal(raw, &a.LastFourDigits)
		if err != nil {
			return fmt.Errorf("error reading 'lastFourDigits': %w", err)
		}
		delete(object, "lastFourDigits")
	}

	if raw, found := object["suspensionReason"]; found {
		err = json.Unmarshal(raw, &a.SuspensionReason)
		if err != nil {
			return fmt.Errorf("error reading 'suspensionReason': %w", err)
		}
		delete(object, "suspensionReason")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
		for fieldName, fieldBuf := range object {
			var fieldVal UnknownJSONValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AccountPaymentMethod to handle AdditionalProperties
func (a AccountPaymentMethod) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BalanceStatus != nil {
		object["balanceStatus"], err = json.Marshal(a.BalanceStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'balanceStatus': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.IsCarKey != nil {
		object["isCarKey"], err = json.Marshal(a.IsCarKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isCarKey': %w", err)
		}
	}

	if a.LastFourDigits != nil {
		object["lastFourDigits"], err = json.Marshal(a.LastFourDigits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lastFourDigits': %w", err)
		}
	}

	if a.SuspensionReason != nil {
		object["suspensionReason"], err = json.Marshal(a.SuspensionReason)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'suspensionReason': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for AccountQuota. Returns the specified
// element and whether it was found
func (a AccountQuota) Get(fieldName string) (value UnknownJSONValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AccountQuota
func (a *AccountQuota) Set(fieldName string, value UnknownJSONValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AccountQuota to handle AdditionalProperties
func (a *AccountQuota) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["almost-full"]; found {
		err = json.Unmarshal(raw, &a.AlmostFull)
		if err != nil {
			return fmt.Errorf("error reading 'almost-full': %w", err)
		}
		delete(object, "almost-full")
	}

	if raw, found := object["haveMaxQuotaTier"]; found {
		err = json.Unmarshal(raw, &a.HaveMaxQuotaTier)
		if err != nil {
			return fmt.Errorf("error reading 'haveMaxQuotaTier': %w", err)
		}
		delete(object, "haveMaxQuotaTier")
	}

	if raw, found := object["overQuota"]; found {
		err = json.Unmarshal(raw, &a.OverQuota)
		if err != nil {
			return fmt.Errorf("error reading 'overQuota': %w", err)
		}
		delete(object, "overQuota")
	}

	if raw, found := object["paidQuota"]; found {
		err = json.Unmarshal(raw, &a.PaidQuota)
		if err != nil {
			return fmt.Errorf("error reading 'paidQuota': %w", err)
		}
		delete(object, "paidQuota")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
		for fieldName, fieldBuf := range object {
			var fieldVal UnknownJSONValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AccountQuota to handle AdditionalProperties
func (a AccountQuota) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AlmostFull != nil {
		object["almost-full"], err = json.Marshal(a.AlmostFull)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'almost-full': %w", err)
		}
	}

	if a.HaveMaxQuotaTier != nil {
		object["haveMaxQuotaTier"], err = json.Marshal(a.HaveMaxQuotaTier)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'haveMaxQuotaTier': %w", err)
		}
	}

	if a.OverQuota != nil {
		object["overQuota"], err = json.Marshal(a.OverQuota)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'overQuota': %w", err)
		}
	}

	if a.PaidQuota != nil {
		object["paidQuota"], err = json.Marshal(a.PaidQuota)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'paidQuota': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for AccountStorageUsage. Returns the specified
// element and whether it was found
func (a AccountStorageUsage) Get(fieldName string) (value UnknownJSONValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AccountStorageUsage
func (a *AccountStorageUsage) Set(fieldName string, value UnknownJSONValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AccountStorageUsage to handle AdditionalProperties
func (a *AccountStorageUsage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["commerceStorageInBytes"]; found {
		err = json.Unmarshal(raw, &a.CommerceStorageInBytes)
		if err != nil {
			return fmt.Errorf("error reading 'commerceStorageInBytes': %w", err)
		}
		delete(object, "commerceStorageInBytes")
	}

	if raw, found := object["compStorageInBytes"]; found {
		err = json.Unmarshal(raw, &a.CompStorageInBytes)
		if err != nil {
			return fmt.Errorf("error reading 'compStorageInBytes': %w", err)
		}
		delete(object, "compStorageInBytes")
	}

	if raw, found := object["totalStorageInBytes"]; found {
		err = json.Unmarshal(raw, &a.TotalStorageInBytes)
		if err != nil {
			return fmt.Errorf("error reading 'totalStorageInBytes': %w", err)
		}
		delete(object, "totalStorageInBytes")
	}

	if raw, found := object["usedStorageInBytes"]; found {
		err = json.Unmarshal(raw, &a.UsedStorageInBytes)
		if err != nil {
			return fmt.Errorf("error reading 'usedStorageInBytes': %w", err)
		}
		delete(object, "usedStorageInBytes")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
		for fieldName, fieldBuf := range object {
			var fieldVal UnknownJSONValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AccountStorageUsage to handle AdditionalProperties
func (a AccountStorageUsage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CommerceStorageInBytes != nil {
		object["commerceStorageInBytes"], err = json.Marshal(a.CommerceStorageInBytes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'commerceStorageInBytes': %w", err)
		}
	}

	if a.CompStorageInBytes != nil {
		object["compStorageInBytes"], err = json.Marshal(a.CompStorageInBytes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'compStorageInBytes': %w", err)
		}
	}

	object["totalStorageInBytes"], err = json.Marshal(a.TotalStorageInBytes)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'totalStorageInBytes': %w", err)
	}

	object["usedStorageInBytes"], err = json.Marshal(a.UsedStorageInBytes)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'usedStorageInBytes': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
