// Package icloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package icloud

import (
	"encoding/json"
	"fmt"
)

// Defines values for ErrorKind.
const (
	Canceled        ErrorKind = "canceled"
	Configuration   ErrorKind = "configuration"
	Forbidden       ErrorKind = "forbidden"
	InvalidResponse ErrorKind = "invalid-response"
	NotFound        ErrorKind = "not-found"
	Provider        ErrorKind = "provider"
	RateLimited     ErrorKind = "rate-limited"
	Timeout         ErrorKind = "timeout"
	Transport       ErrorKind = "transport"
	Unauthorized    ErrorKind = "unauthorized"
	Unavailable     ErrorKind = "unavailable"
)

// Valid indicates whether the value is a known member of the ErrorKind enum.
func (e ErrorKind) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Configuration:
		return true
	case Forbidden:
		return true
	case InvalidResponse:
		return true
	case NotFound:
		return true
	case Provider:
		return true
	case RateLimited:
		return true
	case Timeout:
		return true
	case Transport:
		return true
	case Unauthorized:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// AccountDevice Known device metadata fields are optional; future provider fields are preserved.
type AccountDevice struct {
	Imei *string `json:"imei,omitempty"`

	// LatestBackup Provider backup timestamp text; no timestamp format is inferred.
	LatestBackup         *string `json:"latestBackup,omitempty"`
	Model                *string `json:"model,omitempty"`
	ModelDisplayName     *string `json:"modelDisplayName,omitempty"`
	ModelLargePhotoURL1x *string `json:"modelLargePhotoURL1x,omitempty"`
	ModelLargePhotoURL2x *string `json:"modelLargePhotoURL2x,omitempty"`
	ModelSmallPhotoURL1x *string `json:"modelSmallPhotoURL1x,omitempty"`
	ModelSmallPhotoURL2x *string `json:"modelSmallPhotoURL2x,omitempty"`
	Name                 *string `json:"name,omitempty"`
	OsVersion            *string `json:"osVersion,omitempty"`

	// PaymentMethods Associated payment-method identifiers.
	PaymentMethods       *[]string                   `json:"paymentMethods,omitempty"`
	SerialNumber         *string                     `json:"serialNumber,omitempty"`
	Udid                 *string                     `json:"udid,omitempty"`
	AdditionalProperties map[string]UnknownJSONValue `json:"-"`
}

// AccountMetadata Additional uninterpreted account-level provider fields; nulls and original JSON numbers remain intact.
type AccountMetadata map[string]UnknownJSONValue

// AccountPaymentMethod defines model for AccountPaymentMethod.
type AccountPaymentMethod struct {
	BalanceStatus        *string                     `json:"balanceStatus,omitempty"`
	Id                   *string                     `json:"id,omitempty"`
	IsCarKey             *bool                       `json:"isCarKey,omitempty"`
	LastFourDigits       *string                     `json:"lastFourDigits,omitempty"`
	SuspensionReason     *string                     `json:"suspensionReason,omitempty"`
	Type                 *string                     `json:"type,omitempty"`
	AdditionalProperties map[string]UnknownJSONValue `json:"-"`
}

// AuthContext Caller-owned account identity and web authentication headers. The reusable client never saves this state.
type AuthContext struct {
	// AccountID Authenticated account identifier returned by login.
	AccountID string `json:"accountID"`

	// AccountServiceURL HTTPS account origin returned by authenticated service discovery.
	AccountServiceURL string `json:"accountServiceURL"`

	// ClientBuildNumber Optional build parameter from the authentication context; omission remains omission.
	ClientBuildNumber *string `json:"clientBuildNumber,omitempty"`

	// ClientID Client identifier reused by this account session.
	ClientID string `json:"clientID"`

	// ClientMasteringNumber Optional mastering parameter from the authentication context; omission remains omission.
	ClientMasteringNumber *string `json:"clientMasteringNumber,omitempty"`

	// Headers Account-specific cookie and web headers; an absent Accept value defaults to the reference wildcard.
	Headers []Header `json:"headers"`
}

// ErrorKind Inspectable client failure class; errors preserve their cause separately from their safe display message.
type ErrorKind string

// GetAccountDevicesRequest Example: {"auth":{"accountID":"synthetic-account","accountServiceURL":"https://account.example.invalid","clientID":"synthetic-client","headers":[]}}
type GetAccountDevicesRequest struct {
	// Auth Caller-owned account identity and web authentication headers. The reusable client never saves this state.
	Auth AuthContext `json:"auth"`
}

// GetAccountDevicesResult Fresh account devices and payment-method details. Empty devices are successful; no shared cache is used.
//
// Example: {"additionalMetadata":{},"devices":[{"modelDisplayName":"Synthetic Model","name":"synthetic-device"}],"metadata":{"headers":[],"statusCode":200},"paymentMethods":[]}
type GetAccountDevicesResult struct {
	// AdditionalMetadata Additional uninterpreted account-level provider fields; nulls and original JSON numbers remain intact.
	AdditionalMetadata AccountMetadata `json:"additionalMetadata"`
	Devices            []AccountDevice `json:"devices"`

	// Metadata Response status and headers, including Set-Cookie values for caller-owned session updates.
	Metadata       ResponseMetadata       `json:"metadata"`
	PaymentMethods []AccountPaymentMethod `json:"paymentMethods"`
}

// Header One HTTP response or caller-owned authentication header value; repeated headers remain separate entries.
type Header struct {
	// Name Header name.
	Name string `json:"name"`

	// Value Header value; authentication values may contain secrets.
	Value string `json:"value"`
}

// ResponseMetadata Response status and headers, including Set-Cookie values for caller-owned session updates.
type ResponseMetadata struct {
	// Headers Header entries sorted by name; repeated values retain order within each name.
	Headers []Header `json:"headers"`

	// StatusCode Provider HTTP response status.
	StatusCode int `json:"statusCode"`
}

// UnknownJSONValue Uninterpreted provider metadata, preserved as its original JSON value; its shape is genuinely unknown.
type UnknownJSONValue = json.RawMessage

// Getter for additional properties for AccountDevice. Returns the specified
// element and whether it was found
func (a AccountDevice) Get(fieldName string) (value UnknownJSONValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AccountDevice
func (a *AccountDevice) Set(fieldName string, value UnknownJSONValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AccountDevice to handle AdditionalProperties
func (a *AccountDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["imei"]; found {
		err = json.Unmarshal(raw, &a.Imei)
		if err != nil {
			return fmt.Errorf("error reading 'imei': %w", err)
		}
		delete(object, "imei")
	}

	if raw, found := object["latestBackup"]; found {
		err = json.Unmarshal(raw, &a.LatestBackup)
		if err != nil {
			return fmt.Errorf("error reading 'latestBackup': %w", err)
		}
		delete(object, "latestBackup")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["modelDisplayName"]; found {
		err = json.Unmarshal(raw, &a.ModelDisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'modelDisplayName': %w", err)
		}
		delete(object, "modelDisplayName")
	}

	if raw, found := object["modelLargePhotoURL1x"]; found {
		err = json.Unmarshal(raw, &a.ModelLargePhotoURL1x)
		if err != nil {
			return fmt.Errorf("error reading 'modelLargePhotoURL1x': %w", err)
		}
		delete(object, "modelLargePhotoURL1x")
	}

	if raw, found := object["modelLargePhotoURL2x"]; found {
		err = json.Unmarshal(raw, &a.ModelLargePhotoURL2x)
		if err != nil {
			return fmt.Errorf("error reading 'modelLargePhotoURL2x': %w", err)
		}
		delete(object, "modelLargePhotoURL2x")
	}

	if raw, found := object["modelSmallPhotoURL1x"]; found {
		err = json.Unmarshal(raw, &a.ModelSmallPhotoURL1x)
		if err != nil {
			return fmt.Errorf("error reading 'modelSmallPhotoURL1x': %w", err)
		}
		delete(object, "modelSmallPhotoURL1x")
	}

	if raw, found := object["modelSmallPhotoURL2x"]; found {
		err = json.Unmarshal(raw, &a.ModelSmallPhotoURL2x)
		if err != nil {
			return fmt.Errorf("error reading 'modelSmallPhotoURL2x': %w", err)
		}
		delete(object, "modelSmallPhotoURL2x")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["osVersion"]; found {
		err = json.Unmarshal(raw, &a.OsVersion)
		if err != nil {
			return fmt.Errorf("error reading 'osVersion': %w", err)
		}
		delete(object, "osVersion")
	}

	if raw, found := object["paymentMethods"]; found {
		err = json.Unmarshal(raw, &a.PaymentMethods)
		if err != nil {
			return fmt.Errorf("error reading 'paymentMethods': %w", err)
		}
		delete(object, "paymentMethods")
	}

	if raw, found := object["serialNumber"]; found {
		err = json.Unmarshal(raw, &a.SerialNumber)
		if err != nil {
			return fmt.Errorf("error reading 'serialNumber': %w", err)
		}
		delete(object, "serialNumber")
	}

	if raw, found := object["udid"]; found {
		err = json.Unmarshal(raw, &a.Udid)
		if err != nil {
			return fmt.Errorf("error reading 'udid': %w", err)
		}
		delete(object, "udid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
		for fieldName, fieldBuf := range object {
			var fieldVal UnknownJSONValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AccountDevice to handle AdditionalProperties
func (a AccountDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Imei != nil {
		object["imei"], err = json.Marshal(a.Imei)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'imei': %w", err)
		}
	}

	if a.LatestBackup != nil {
		object["latestBackup"], err = json.Marshal(a.LatestBackup)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'latestBackup': %w", err)
		}
	}

	if a.Model != nil {
		object["model"], err = json.Marshal(a.Model)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'model': %w", err)
		}
	}

	if a.ModelDisplayName != nil {
		object["modelDisplayName"], err = json.Marshal(a.ModelDisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelDisplayName': %w", err)
		}
	}

	if a.ModelLargePhotoURL1x != nil {
		object["modelLargePhotoURL1x"], err = json.Marshal(a.ModelLargePhotoURL1x)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelLargePhotoURL1x': %w", err)
		}
	}

	if a.ModelLargePhotoURL2x != nil {
		object["modelLargePhotoURL2x"], err = json.Marshal(a.ModelLargePhotoURL2x)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelLargePhotoURL2x': %w", err)
		}
	}

	if a.ModelSmallPhotoURL1x != nil {
		object["modelSmallPhotoURL1x"], err = json.Marshal(a.ModelSmallPhotoURL1x)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelSmallPhotoURL1x': %w", err)
		}
	}

	if a.ModelSmallPhotoURL2x != nil {
		object["modelSmallPhotoURL2x"], err = json.Marshal(a.ModelSmallPhotoURL2x)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'modelSmallPhotoURL2x': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.OsVersion != nil {
		object["osVersion"], err = json.Marshal(a.OsVersion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'osVersion': %w", err)
		}
	}

	if a.PaymentMethods != nil {
		object["paymentMethods"], err = json.Marshal(a.PaymentMethods)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'paymentMethods': %w", err)
		}
	}

	if a.SerialNumber != nil {
		object["serialNumber"], err = json.Marshal(a.SerialNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'serialNumber': %w", err)
		}
	}

	if a.Udid != nil {
		object["udid"], err = json.Marshal(a.Udid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'udid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for AccountPaymentMethod. Returns the specified
// element and whether it was found
func (a AccountPaymentMethod) Get(fieldName string) (value UnknownJSONValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AccountPaymentMethod
func (a *AccountPaymentMethod) Set(fieldName string, value UnknownJSONValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AccountPaymentMethod to handle AdditionalProperties
func (a *AccountPaymentMethod) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["balanceStatus"]; found {
		err = json.Unmarshal(raw, &a.BalanceStatus)
		if err != nil {
			return fmt.Errorf("error reading 'balanceStatus': %w", err)
		}
		delete(object, "balanceStatus")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["isCarKey"]; found {
		err = json.Unmarshal(raw, &a.IsCarKey)
		if err != nil {
			return fmt.Errorf("error reading 'isCarKey': %w", err)
		}
		delete(object, "isCarKey")
	}

	if raw, found := object["lastFourDigits"]; found {
		err = json.Unmarshal(raw, &a.LastFourDigits)
		if err != nil {
			return fmt.Errorf("error reading 'lastFourDigits': %w", err)
		}
		delete(object, "lastFourDigits")
	}

	if raw, found := object["suspensionReason"]; found {
		err = json.Unmarshal(raw, &a.SuspensionReason)
		if err != nil {
			return fmt.Errorf("error reading 'suspensionReason': %w", err)
		}
		delete(object, "suspensionReason")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]UnknownJSONValue)
		for fieldName, fieldBuf := range object {
			var fieldVal UnknownJSONValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AccountPaymentMethod to handle AdditionalProperties
func (a AccountPaymentMethod) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BalanceStatus != nil {
		object["balanceStatus"], err = json.Marshal(a.BalanceStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'balanceStatus': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.IsCarKey != nil {
		object["isCarKey"], err = json.Marshal(a.IsCarKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isCarKey': %w", err)
		}
	}

	if a.LastFourDigits != nil {
		object["lastFourDigits"], err = json.Marshal(a.LastFourDigits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lastFourDigits': %w", err)
		}
	}

	if a.SuspensionReason != nil {
		object["suspensionReason"], err = json.Marshal(a.SuspensionReason)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'suspensionReason': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
