// Package bridgewebsocket provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bridgewebsocket

import (
	bridgepb "github.com/portpowered/go-icloud/pkg/dependencymodels/bridgepb"
)

// Defines values for AcceptHeader.
const (
	UpgradeAcceptHeader AcceptHeader = "Sec-WebSocket-Accept"
)

// Valid indicates whether the value is a known member of the AcceptHeader enum.
func (e AcceptHeader) Valid() bool {
	switch e {
	case UpgradeAcceptHeader:
		return true
	default:
		return false
	}
}

// Defines values for DefaultPort.
const (
	SecurePort DefaultPort = "443"
)

// Valid indicates whether the value is a known member of the DefaultPort enum.
func (e DefaultPort) Valid() bool {
	switch e {
	case SecurePort:
		return true
	default:
		return false
	}
}

// Defines values for ExtensionLengths.
const (
	LongLengthBytes   ExtensionLengths = 8
	MediumLengthBytes ExtensionLengths = 2
)

// Valid indicates whether the value is a known member of the ExtensionLengths enum.
func (e ExtensionLengths) Valid() bool {
	switch e {
	case LongLengthBytes:
		return true
	case MediumLengthBytes:
		return true
	default:
		return false
	}
}

// Defines values for HeaderLine.
const (
	ConnectionLine HeaderLine = "Connection: Upgrade"
	HostLine       HeaderLine = "Host: %s"
	KeyLine        HeaderLine = "Sec-WebSocket-Key: %s"
	OriginLine     HeaderLine = "Origin: %s"
	UpgradeLine    HeaderLine = "Upgrade: websocket"
	UserAgentLine  HeaderLine = "User-Agent: %s"
	VersionLine    HeaderLine = "Sec-WebSocket-Version: 13"
)

// Valid indicates whether the value is a known member of the HeaderLine enum.
func (e HeaderLine) Valid() bool {
	switch e {
	case ConnectionLine:
		return true
	case HostLine:
		return true
	case KeyLine:
		return true
	case OriginLine:
		return true
	case UpgradeLine:
		return true
	case UserAgentLine:
		return true
	case VersionLine:
		return true
	default:
		return false
	}
}

// Defines values for HeaderPosition.
const (
	FrameLengthPosition HeaderPosition = 1
	FrameOpcodePosition HeaderPosition = 0
)

// Valid indicates whether the value is a known member of the HeaderPosition enum.
func (e HeaderPosition) Valid() bool {
	switch e {
	case FrameLengthPosition:
		return true
	case FrameOpcodePosition:
		return true
	default:
		return false
	}
}

// Defines values for LineSeparator.
const (
	CarriageReturn LineSeparator = 13
	LineFeed       LineSeparator = 10
)

// Valid indicates whether the value is a known member of the LineSeparator enum.
func (e LineSeparator) Valid() bool {
	switch e {
	case CarriageReturn:
		return true
	case LineFeed:
		return true
	default:
		return false
	}
}

// Defines values for Network.
const (
	DialNetwork Network = "tcp"
)

// Valid indicates whether the value is a known member of the Network enum.
func (e Network) Valid() bool {
	switch e {
	case DialNetwork:
		return true
	default:
		return false
	}
}

// Defines values for OpcodeMask.
const (
	FrameOpcodeMask OpcodeMask = 15
)

// Valid indicates whether the value is a known member of the OpcodeMask enum.
func (e OpcodeMask) Valid() bool {
	switch e {
	case FrameOpcodeMask:
		return true
	default:
		return false
	}
}

// Defines values for PayloadLimit.
const (
	MaxMessageBytes PayloadLimit = 6.7108864e+07
)

// Valid indicates whether the value is a known member of the PayloadLimit enum.
func (e PayloadLimit) Valid() bool {
	switch e {
	case MaxMessageBytes:
		return true
	default:
		return false
	}
}

// Defines values for RequestLine.
const (
	UpgradeRequestLine RequestLine = "GET %s HTTP/1.1"
)

// Valid indicates whether the value is a known member of the RequestLine enum.
func (e RequestLine) Valid() bool {
	switch e {
	case UpgradeRequestLine:
		return true
	default:
		return false
	}
}

// Defines values for RequestTargetPattern.
const (
	CanonicalRequestTarget RequestTargetPattern = "^/v2/[0-9a-f]+$"
)

// Valid indicates whether the value is a known member of the RequestTargetPattern enum.
func (e RequestTargetPattern) Valid() bool {
	switch e {
	case CanonicalRequestTarget:
		return true
	default:
		return false
	}
}

// Defines values for Scheme.
const (
	SecureScheme Scheme = "wss"
)

// Valid indicates whether the value is a known member of the Scheme enum.
func (e Scheme) Valid() bool {
	switch e {
	case SecureScheme:
		return true
	default:
		return false
	}
}

// Defines values for UpgradeBridgeParamsUpgrade.
const (
	Websocket UpgradeBridgeParamsUpgrade = "websocket"
)

// Valid indicates whether the value is a known member of the UpgradeBridgeParamsUpgrade enum.
func (e UpgradeBridgeParamsUpgrade) Valid() bool {
	switch e {
	case Websocket:
		return true
	default:
		return false
	}
}

// Defines values for UpgradeBridgeParamsConnection.
const (
	Upgrade UpgradeBridgeParamsConnection = "Upgrade"
)

// Valid indicates whether the value is a known member of the UpgradeBridgeParamsConnection enum.
func (e UpgradeBridgeParamsConnection) Valid() bool {
	switch e {
	case Upgrade:
		return true
	default:
		return false
	}
}

// Defines values for UpgradeBridgeParamsSecWebSocketVersion.
const (
	N13 UpgradeBridgeParamsSecWebSocketVersion = "13"
)

// Valid indicates whether the value is a known member of the UpgradeBridgeParamsSecWebSocketVersion enum.
func (e UpgradeBridgeParamsSecWebSocketVersion) Valid() bool {
	switch e {
	case N13:
		return true
	default:
		return false
	}
}

// AcceptHeader defines model for AcceptHeader.
type AcceptHeader string

// DefaultPort defines model for DefaultPort.
type DefaultPort string

// ExtensionLengths defines model for ExtensionLengths.
type ExtensionLengths int

// Frame defines model for Frame.
type Frame struct {
	Finished bool            `json:"finished"`
	Opcode   bridgepb.Opcode `json:"opcode"`
	Payload  []byte          `json:"payload"`
}

// HeaderLine defines model for HeaderLine.
type HeaderLine string

// HeaderPosition defines model for HeaderPosition.
type HeaderPosition int

// LineSeparator defines model for LineSeparator.
type LineSeparator int

// Mask defines model for Mask.
type Mask = []byte

// Network defines model for Network.
type Network string

// OpcodeMask defines model for OpcodeMask.
type OpcodeMask int

// PayloadLimit SDK local 64 MiB receive resource policy (GO-06), not a Source or provider wire limit.
type PayloadLimit int

// RequestLine defines model for RequestLine.
type RequestLine string

// RequestTargetPattern defines model for RequestTargetPattern.
type RequestTargetPattern string

// Scheme defines model for Scheme.
type Scheme string

// UpgradeBridgeParams defines parameters for UpgradeBridge.
type UpgradeBridgeParams struct {
	Origin              string                                 `json:"Origin"`
	UserAgent           string                                 `json:"User-Agent"`
	Upgrade             UpgradeBridgeParamsUpgrade             `json:"Upgrade"`
	Connection          UpgradeBridgeParamsConnection          `json:"Connection"`
	SecWebSocketVersion UpgradeBridgeParamsSecWebSocketVersion `json:"Sec-WebSocket-Version"`
	SecWebSocketKey     []byte                                 `json:"Sec-WebSocket-Key"`
}

// UpgradeBridgeParamsUpgrade defines parameters for UpgradeBridge.
type UpgradeBridgeParamsUpgrade string

// UpgradeBridgeParamsConnection defines parameters for UpgradeBridge.
type UpgradeBridgeParamsConnection string

// UpgradeBridgeParamsSecWebSocketVersion defines parameters for UpgradeBridge.
type UpgradeBridgeParamsSecWebSocketVersion string
