// Package bridgeprover provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bridgeprover

// Defines values for ConfirmationLabel.
const (
	ConfirmationInfo ConfirmationLabel = "ConfirmationKeys"
)

// Valid indicates whether the value is a known member of the ConfirmationLabel enum.
func (e ConfirmationLabel) Valid() bool {
	switch e {
	case ConfirmationInfo:
		return true
	default:
		return false
	}
}

// Defines values for ContextLabel.
const (
	SPAKEContext ContextLabel = "SPAKE2Web"
)

// Valid indicates whether the value is a known member of the ContextLabel enum.
func (e ContextLabel) Valid() bool {
	switch e {
	case SPAKEContext:
		return true
	default:
		return false
	}
}

// Defines values for DerivedLength.
const (
	PasswordKeyLength DerivedLength = 64
)

// Valid indicates whether the value is a known member of the DerivedLength enum.
func (e DerivedLength) Valid() bool {
	switch e {
	case PasswordKeyLength:
		return true
	default:
		return false
	}
}

// Defines values for KeyLength.
const (
	BridgeKeyLength KeyLength = 32
)

// Valid indicates whether the value is a known member of the KeyLength enum.
func (e KeyLength) Valid() bool {
	switch e {
	case BridgeKeyLength:
		return true
	default:
		return false
	}
}

// Defines values for MaskM.
const (
	SPAKEM MaskM = "02886e2f97ace46e55ba9dd7242579f2993b64e16ef3dcab95afd497333d8fa12f"
)

// Valid indicates whether the value is a known member of the MaskM enum.
func (e MaskM) Valid() bool {
	switch e {
	case SPAKEM:
		return true
	default:
		return false
	}
}

// Defines values for MaskN.
const (
	SPAKEN MaskN = "03d8bbd6c639c62937b04d997f38c3770719c629d7014d49a24b4f98baa1292b49"
)

// Valid indicates whether the value is a known member of the MaskN enum.
func (e MaskN) Valid() bool {
	switch e {
	case SPAKEN:
		return true
	default:
		return false
	}
}

// Defines values for NonceLength.
const (
	GCMNonceLength NonceLength = 12
)

// Valid indicates whether the value is a known member of the NonceLength enum.
func (e NonceLength) Valid() bool {
	switch e {
	case GCMNonceLength:
		return true
	default:
		return false
	}
}

// Defines values for PayloadVersion.
const (
	GCMVersion PayloadVersion = 0
)

// Valid indicates whether the value is a known member of the PayloadVersion enum.
func (e PayloadVersion) Valid() bool {
	switch e {
	case GCMVersion:
		return true
	default:
		return false
	}
}

// Defines values for ProverIdentity.
const (
	ClientIdentity ProverIdentity = "com.apple.security.webprover"
)

// Valid indicates whether the value is a known member of the ProverIdentity enum.
func (e ProverIdentity) Valid() bool {
	switch e {
	case ClientIdentity:
		return true
	default:
		return false
	}
}

// Defines values for ProverLabel.
const (
	ProverInfo ProverLabel = "webProver"
)

// Valid indicates whether the value is a known member of the ProverLabel enum.
func (e ProverLabel) Valid() bool {
	switch e {
	case ProverInfo:
		return true
	default:
		return false
	}
}

// Defines values for ScryptN.
const (
	ScryptCost ScryptN = 16384
)

// Valid indicates whether the value is a known member of the ScryptN enum.
func (e ScryptN) Valid() bool {
	switch e {
	case ScryptCost:
		return true
	default:
		return false
	}
}

// Defines values for ScryptP.
const (
	ScryptParallelism ScryptP = 1
)

// Valid indicates whether the value is a known member of the ScryptP enum.
func (e ScryptP) Valid() bool {
	switch e {
	case ScryptParallelism:
		return true
	default:
		return false
	}
}

// Defines values for ScryptR.
const (
	ScryptBlockSize ScryptR = 8
)

// Valid indicates whether the value is a known member of the ScryptR enum.
func (e ScryptR) Valid() bool {
	switch e {
	case ScryptBlockSize:
		return true
	default:
		return false
	}
}

// Defines values for SharedLabel.
const (
	SharedInfo SharedLabel = "SharedKey"
)

// Valid indicates whether the value is a known member of the SharedLabel enum.
func (e SharedLabel) Valid() bool {
	switch e {
	case SharedInfo:
		return true
	default:
		return false
	}
}

// Defines values for TagLength.
const (
	GCMTagLength TagLength = 16
)

// Valid indicates whether the value is a known member of the TagLength enum.
func (e TagLength) Valid() bool {
	switch e {
	case GCMTagLength:
		return true
	default:
		return false
	}
}

// Defines values for VerifierIdentity.
const (
	ServerIdentity VerifierIdentity = "com.apple.security.webverifier"
)

// Valid indicates whether the value is a known member of the VerifierIdentity enum.
func (e VerifierIdentity) Valid() bool {
	switch e {
	case ServerIdentity:
		return true
	default:
		return false
	}
}

// Defines values for VerifierLabel.
const (
	VerifierInfo VerifierLabel = "webVerifier"
)

// Valid indicates whether the value is a known member of the VerifierLabel enum.
func (e VerifierLabel) Valid() bool {
	switch e {
	case VerifierInfo:
		return true
	default:
		return false
	}
}

// ConfirmationLabel defines model for ConfirmationLabel.
type ConfirmationLabel string

// ContextLabel defines model for ContextLabel.
type ContextLabel string

// DerivedLength defines model for DerivedLength.
type DerivedLength int

// KeyLength defines model for KeyLength.
type KeyLength int

// MaskM defines model for MaskM.
type MaskM string

// MaskN defines model for MaskN.
type MaskN string

// NonceLength defines model for NonceLength.
type NonceLength int

// PayloadVersion defines model for PayloadVersion.
type PayloadVersion int

// ProverIdentity defines model for ProverIdentity.
type ProverIdentity string

// ProverLabel defines model for ProverLabel.
type ProverLabel string

// ScryptN defines model for ScryptN.
type ScryptN int

// ScryptP defines model for ScryptP.
type ScryptP int

// ScryptR defines model for ScryptR.
type ScryptR int

// SharedLabel defines model for SharedLabel.
type SharedLabel string

// TagLength defines model for TagLength.
type TagLength int

// VerifierIdentity defines model for VerifierIdentity.
type VerifierIdentity string

// VerifierLabel defines model for VerifierLabel.
type VerifierLabel string
